### ISSUE TITLE
Style property does not contain invalid CSS

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#101]
The `Style` property does not seem to include CSS properties that have invalid values but they are included in the HTML string. OTOH, unknown properties are exposed through `Style`:

``` C#
var html = "<Div style=\"foo: bar; background-color: http://www.codeplex.com?url=<SCRIPT>a=/XSS/alert(a.source)</SCRIPT>\">";
var parser = new HtmlParser(html, new Configuration().WithCss());
var dom = parser.Parse();
var div = (IHtmlElement)dom.QuerySelector("div");
var n = div.Style.Length; // 1, includes only foo, not background-color
var s = div.ToHtml(); // same as original html
```

Is it possible to access all CSS properties as key-value-pairs?

**Comment by FlorianRappl** [comment]
That's certainly possible and since I am in the process of making the CSSOM much better anyway, I will include that as well.

**Comment by FlorianRappl** [comment]
One more remark to this issue. The behavior you are seeing is the same as every browser has. What you get serialized in HTML is the value of the attribute. However, what you see in the CSSOM is not the value of the attribute, but the objects inside. Both may differ.

If you change the CSSOM then the value of the attribute will also change. Both without changing the CSSOM the DOM will remain unchanged.

**Comment by mganss** [comment]
Can you explain how the change enables the above scenario? I can't seem to get it to work. In fact, now even unknown properties ("foo") are no longer included in the `Style` property.

**Comment by FlorianRappl** [comment]
What are you trying to do? If you want to exclusively use the CSS parser then just use it and supply a `CssParserOptions` instance. You can then activate `IsIncludingUnknownRules` or `IsIncludingUnknownDeclarations`. Additionally you may also go for `IsToleratingInvalidValues`, which deactivates value checking altogether. As a result the obtained stylesheet will the unknown rules / properties / values.

**Comment by mganss** [comment]
I want to access (and manipulate) inline declarations of an `IHtmlElement` as key-value pairs (including invalid and unknown declarations and values). It's not clear to me how I would go about using `CssParser` under these circumstances. Do I have to set up a fake rule from the `style` attribute of the element and construct a `CssParser` instance from it?

**Comment by FlorianRappl** [comment]
Why don't you register the parser for your custom needs? Its all there. Instead of using the provided `WithCss`, which uses the parser with the default options, you can just provide your own.

All you need to do is to implement `IStyleEngine` (similar to `CssStyleEngine`, but with using the desired options when calling the `Parse` method of the parser) and then to use, e.g., the default `StylingService` with the custom engine.

**Comment by mganss** [comment]
The implementation of `CssStyleEngine` depends on all kinds of internal classes so I can't just copy it and replace the one line where `CssParser.Parse()` is called. But even if I implement my own `IStyleEngine` and register it in an instance of `StylingService`, its methods aren't called:

``` C#
var service = new StylingService();
service.Register(new MyStyleEngine());

var html = "<Div style=\"color: black; foo: bar; background-color: http://www.codeplex.com?url=<SCRIPT>a=/XSS/alert(a.source)</SCRIPT>\">";
var parser = new HtmlParser(html, new Configuration().With(service));
var dom = parser.Parse();
var div = (IHtmlElement)dom.QuerySelector("div");
var a = div.GetAttribute("style");
var n = div.Style.Length; // still 1, methods of MyStyleEngine not called
```

**Comment by FlorianRappl** [comment]
Alright - I am sorry. It is all my fault! The reason is both, simple and tricky. Unfortunately the `Style` property rlies on the `CssStyleDeclaration`, which uses _direct_ update methods, i.e. without asking for a specific engine.

This is the corresponding code snippet:

```
internal void Update(String value)
{
  _declarations.Clear();

  if (!String.IsNullOrEmpty(value))
    CssParser.AppendDeclarations(this, value);
}
```

There are two problems:
1. Direct call to the `CssParser`, which may not be the one you want.
2. Call without attaching any options.

Especially the latter is disturbing at that point. So I'll make it work and I will release a v0.8.7. What I did in the meantime is to extend the existing `CssStyleEngine` with the ability to set options (and a different base stylesheet). You don't have to go the long way, it can be all set up in the configuration (similar to `...WithCss(engine => engine.Options = new CssParserOptions { ... })`).

Again I am sorry and I will patch this soon.

**Comment by mganss** [comment]
Thanks, it's much better now. But there are still some declarations that are not included in the `Style` property but are included in the output of `ToHtml()`. Is it possible to either have them included in the `Style` property or excluded from the `ToHtml()` output?

``` C#
var html = "<div style=\"background-image: url(javascript:alert(1))\"></div>";
var parser = new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidConstraints = true,
    IsToleratingInvalidValues = true
}));
var dom = parser.Parse(html);
var div = (IHtmlElement)dom.QuerySelector("div");
var n = div.Style.Length; // zero
var s = div.ToHtml(); // same as original html
```

**Comment by FlorianRappl** [comment]
I think this is a misconception. As explained above the `ToHtml` never looks at the `Style` - just at the attribute. The attribute's value is what is transferred to the CSS parser. They do not have to look the same. This is all as specified and the behavior is equal to any browser.

However, if you modify the `Style` the changes will be reflected in the attribute. At this point in time the attribute contains the actual serialization - hence both, the `Style` and the attribute, are equal (checked with the string representation).

Apart from that (which won't change) the scenario you show seems fishy. I would expect the length of the `Style` to be 1 (with the provided options). I'll check that.
