### ISSUE TITLE
Problem with CssText output of "text-decoration"

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#103]
For css definiton:  a {text-decoration:underline;}
The parsed CssText output is:
 a { text-decoration-line: underline; text-decoration-style: initial; text-decoration-color: initial; }
Since the later is not supported in most major browsers, the rendering result in browser is totally different.

Is there any specific reason for rendering the CssText the current way?

**Comment by FlorianRappl** [comment]
Not supported in major browsers? `text-decoration` was a longhand in CSS 2 but changed with CSS 3 to a shorthand. Every modern browser should support this.

What you see here is the expansion as it is stored inside the `StyleDeclaration`. What obviously does not work (but that is only due to some bugs in the conversion process; which is new in v0.8.5 and will become more mature until v0.9) is the back transformation from longhands to shorthand properties for serialization.

So this is a minor bug that has only (afaik) cosmetic consequences in form of an uglier serialization.

**Comment by D92130** [comment]
Thanks for your quick response.

I was saying "text-decoration-line" is not supported by major browsers. Thus the longhand CssText output of the parsed css definition will generate different look in browser.

You can check it out here: http://www.w3schools.com/cssref/css3_pr_text-decoration-line.asp .  My test in IE, Chrome and Firefox confirmed it, too.

**Comment by FlorianRappl** [comment]
Apparently only Firefox follows the specification here. Either way the serialization will be fixed in the upcoming release.
