### ISSUE TITLE
How to load HTML document from local filesystem?

### ISSUE THREAD

**Issue by IanKemp** [AngleSharp/AngleSharp#1048]
Using AngleSharp 0.17.1 in a .NET 6 console app.

test.html lives in the same directory as my Program.cs and has "Copy to Output Directory" set to "Copy always". I've also verified that it appears in the bin\Debug\net6.0 directory alongside the compiled EXE. And if I copy the contents of htmlFile and paste it into a browser URL bar and press Enter, the page does indeed appear.

Thus I would expect the following code to load my HTML file, yet in practice document is always NULL. Where am I going wrong?

```csharp
var config = Configuration.Default
    .WithDefaultLoader(new LoaderOptions { IsResourceLoadingEnabled = true });

var context = BrowsingContext.New(config);
var htmlFile = $"file:{Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!, "test.html")}";

var document = await context.OpenAsync(htmlFile)
```

**Comment by FlorianRappl** [comment]
What is `file:`? That is a custom scheme. The only scheme that the core lib understands is `http` (and `https`).

I think what you want is to add additional loaders brought in by [AngleSharp.Io](https://github.com/AngleSharp/AngleSharp.Io).

**Comment by FlorianRappl** [comment]
(There is also no need to use the custom scheme. You could just read the file yourself, e.g., as a `FileStream`).

**Comment by IanKemp** [comment]
I would expect that instead of doing nothing and returning a `null` document instance, `OpenAsync` would throw if it encounters a protocol it does not understand.

**Comment by FlorianRappl** [comment]
Nope. That would be destructive. An exception destroys everything bottom up, so there is no way to recover - your browser also does not emit an exception.

**Comment by IanKemp** [comment]
> Nope. That would be destructive

That's the entire point of an exception!

> An exception destroys everything bottom up, so there is no way to recover

Of course there's a way to recover: catch that exception type!

> your browser also does not emit an exception.

AngleSharp isn't a browser used by ordinary users, it's an API used by programmers who want to parse HTML documents. And programmers expect APIs to tell them when they're trying to do something that said API doesn't support. Returning `null` is a terrible way to communicate that.

**Comment by FlorianRappl** [comment]
> Of course there's a way to recover: catch that exception type!

You don't seem to understand how an exception works. It unwinds the stack trace. So first, you'd need to catch the exception, otherwise it is destructive on your application, too. Second (and that is my original comment, please read more carefully in the future) any work following up the step where the exception is emitted won't be done. So the main browsing context will have a dangling subcontext with incomplete state that was never returned to the user.

Please read the description of AngleSharp first and understand what it does and why it does like that. Then you'll see that your comments does not make any sense in context of AngleSharp. Thanks!

> And programmers expect APIs to tell them when they're trying to do something that said API doesn't support. 

I think your main issue is that you only think in your use case. This is a browser engine and it encounters things like resources pointing to invalid addresses or using invalid schemes (like the document address you gave it). If we'd emit exceptions in any of these cases then it would not be useful. We emit error events instead.
