### ISSUE TITLE
Update Event to support latest standard

### ISSUE THREAD

**Issue by egil** [AngleSharp/AngleSharp#1053]
# New Feature Proposal

The Event type seem to have drifted a bit from the [current standard](https://developer.mozilla.org/en-US/docs/Web/API/Event). It should be updated.

## Description

As far as I can see, the following are missing or incorrectly named:

1. [`composed`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composed) property is missing.
2. [`originalTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/originalTarget) property  should be renamed to [`target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target). The first is non-standard, and the latter seems to do the same.
3. [`composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) method is missing.

The two methods, `Stop` and `Cancel`, confused me. I had to look at the source to figure out they represented `stopPropagation` and `preventDefault`. I would probably have named them after their JavaScript counter parts.

## Specification

https://developer.mozilla.org/en-US/docs/Web/API/Event

**Comment by FlorianRappl** [comment]
The `originalTarget` does not exist - we already only have `target`:

![image](https://user-images.githubusercontent.com/1766191/211158207-b7a453f0-efde-4e0a-afe0-d7cbe7cbb18f.png)

I think there you confused that it's actually about the behavior - not about the name. We picked the spec name whereever applicable - in this case it made more sense to have it (in .NET) named "OriginalTarget", because it represents a nice symmetry to "CurrentTarget" (otherwise, no one knows the difference between "Target" and "CurrentTarget" - shouldn't the latter be the same as the former?).

The other two (`composed` and `composedPath()`) are now implemented and available in `devel`.
