### ISSUE TITLE
Parsed css stylesheet does not contain media

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#109]
Not sure if I'm doing something wrong.

Tried to parse http://cdn.sstatic.net/stackoverflow/all.css?v=5a386bc7d85d using AngleSharp.

There seem to be many issues, for instance StyleSheet.Media is empty even though the css has many `@media` declarations. So the rules within `@media` declarations are missing.

**Comment by FlorianRappl** [comment]
Hm I don't know which version of AngleSharp you are using. The current version (v0.8.5) has some problems - hopefully most have been reported and closed (in particular see #99). I will have a look at that particular stylesheet to see if there is anything that has not been issued and should be fixed.

**Comment by FlorianRappl** [comment]
I checked the sheet and yes, the handling of `@media` rules has been fixed already (will be made available via v0.8.6). I didn't see any other critical issues, just a few cosmetic ones:
- CSS Media settings with `and` conjunctions (or others) that contain invalid (in this case due to vendor prefixes) constraints should be considered invalid -- at the moment the invalid part is only dropped. An invalid Medium then is either dropped or left alone depending on the parser's setting
- The serialization should be done via a formatter as in HTML with the `IMarkupFormatter`. It would allow both, standard and special formatting without any problem and it would be very consistent
- Apparently the `background-image` declaration does not accept multiple values - at least the ones that were specified similar to `url(...), none` were dropped. I'll investigate
