### ISSUE TITLE
Rule has empty selector after parsing (button:focus-visible)

### ISSUE THREAD

**Issue by betfix** [AngleSharp/AngleSharp#1121]
I have the following function (using AngleSharp.Css 0.16.4):

```
public static void MakeTest()
    {
        var css = @"
button { outline: 0 }
button, input { outline: 0 }
button:focus-visible { outline: 0 }
button, button:focus-visible { outline: 0 }
";        
        var parser = new CssParser();
        var sheet = parser.ParseStyleSheet(css);
        for (var i=0; i<sheet.Rules.Length; i++)
        {
            if (sheet.Rules[i] is ICssStyleRule styleRule)
            {
                Console.WriteLine(i + " " + styleRule.SelectorText);
            }
        }
    }
```

The console output is:

> 0 button
> 1 button, input
> 2
> 3

The last two rules have no selector after parsing, why? Even if the `button:focus-visible` selector is problematic for some reason, the last rule contains also `button` selector, but the selector is empty after parsing.

**Comment by FlorianRappl** [comment]
Because those two selectors (specifically the one with the `:focus-visible` pseudo class) are not supported.

This comes with selectors L4 which is only partially implemented. Any unknown selector is invalid - as it is in the browser.

Only these are implemented: https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Css/PseudoClassNames.cs

Open for PRs (selectors are part of the core library)!

**Comment by FlorianRappl** [comment]
Part of the 1.0.4 preview and next release.
