### ISSUE TITLE
Tag <br/> ignored, new lines ignored

### ISSUE THREAD

**Issue by fox112358** [AngleSharp/AngleSharp#1129]
### Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

### Description

```

<p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>

```

In browser this looks like:

<p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>

when I try to get text content from it like this

```
            var parser = new HtmlParser();
            var doc = parser.ParseDocument(data.Body);

            result = doc.Body?.TextContent;
```

I see in the output this: "Heading 1This is test line 1This is test line 2Body accepts HTML"

It ignores all new lines. Is there any other approach to get the text like it is parsed in browser? 

### Steps to Reproduce

Take this piece of html and get the text content from it

```
               <p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>
```

### Expected Behavior

<p
                    style="
                  margin-right: 0in;
                  margin-left: 0in;
                  font-size: 15px;
                  font-family: 'Arial', sans-serif;
                  line-height: 115%;
                ">
                    <h1>Heading 1</h1><br/><p>This is test line 1</p><p>This is test line 2</p><p>Body accepts HTML</p>
                </p>

### Actual Behavior

Heading 1This is test line 1This is test line 2Body accepts HTML

**Comment by FlorianRappl** [comment]
I think you confuse two things:

1. The rendering of a page (using the computed render tree, which takes the information from the CSSOM and the DOM)
2. The structural code of a page (HTML code, which is then parsed and computed into the DOM)

The `TextContent` property is not meant to give you what the rendering of text would give you. It is just a concatenation of the text nodes (so only using 2, since text nodes are nodes of the DOM).

`InnerText` (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText) is a better approximation, but also just that - an approximation (it would be using infos from (1)). You'll need *AngleSharp.Css* to use that for the information sources specified above.

Hope that helps!
