### ISSUE TITLE
HtmlButtonElement value does not send as form field value

### ISSUE THREAD

**Issue by tsu1980** [AngleSharp/AngleSharp#119]
Hi, i found another problem.

here is html.

``` html
<form method="post" action="./Login.php" >
  <input type="text" name="username" value="">
  <input type="password" name="password" value="">
  <button type="submit" name="login" value="Login">
</from>
```

http request body by AngleSharp v0.8.8:

```
username=foo&password=bar&login=
```

http request body by Chrome:

```
username=foo&password=bar&login=Login
```

Missing button's value. I faced login fail some server. so changed source(HtmlButtonElement.cs) as below and then it works.

``` cs
        public String Value
        {
            get { return _value ?? GetOwnAttribute(AttributeNames.Value) ?? String.Empty; }
            //get { return _value ?? String.Empty; }
            set { _value = value; }
        }
```

AngleSharp v0.8.8

**Comment by FlorianRappl** [comment]
Thanks for spotting this. However, the solution is not as easy as you might think. The correct outcome (in both, Chrome and AngleSharp) is:

```
username=foo&password=bar
```

The one you see in Chrome is only generated, because you actually trigger the form submission by _clicking the button_. 

A MWE:

``` html
<!doctype html>
<form method="post" action="http://anglesharp.azurewebsites.net/echo">
  <input type="text" name="username" value="foo">
  <input type="password" name="password" value="bar">
  <button type="submit" name="login" value="Login">Submit via button!</button>
  <a href="#" onclick="this.parentElement.submit();">Submit via form</a>
</form>
```

Using the button I get:

![image](https://cloud.githubusercontent.com/assets/1766191/8978863/34811332-36a6-11e5-8c8f-fa3ec1f9eb0a.png)

Using the link (form directly) I get:

![image](https://cloud.githubusercontent.com/assets/1766191/8978883/590f48e0-36a6-11e5-94c2-532c7b1c2023.png)

What I am going to do is to expose another `Submit()` method on the form, which allows you to pass in some "submitting element". Please note, however, that the `HtmlButtonElement` has also a `DoClick` method, which will has nearly same effect (if the `HtmlButtonElement` is of `submit` type), but does not return a `Task<IDocument>`.

**Comment by tsu1980** [comment]
Thank you!

**Comment by tsu1980** [comment]
I realized input[type=submit] has similar problem to this case. I don't know other input type elements but type=submit has similar problem.

here is html.

``` html
<form method="POST" action="/item/confirm" enctype="multipart/form-data">
  (omit)
  <INPUT type=submit value="Edit" name="edit_btn">
  <INPUT type=submit value="Commit" name="commit_btn">
</from>
```

then run below code.

``` cs
var commitBtn = doc.QuerySelector<IHtmlInputElement>("input[name=commit_btn]");
await commitBtn.Form.Submit(commitBtn);
```

http request body by AngleSharp v0.8.8:

```
(omit)
--2c65388e-a8c5-4283-956d-3bb4836f263a
Content-Disposition: form-data; name="edit_btn"

Edit
--2c65388e-a8c5-4283-956d-3bb4836f263a
Content-Disposition: form-data; name="commit_btn"

Commit
--2c65388e-a8c5-4283-956d-3bb4836f263a--
```

http request body by Chrome:

```
(omit)
------WebKitFormBoundaryMWbWWqhoNde2EJOl
Content-Disposition: form-data; name="commit_btn"

Commit
------WebKitFormBoundaryMWbWWqhoNde2EJOl--
```

AngleSharp send "edit_btn" value that not clicked. I faced 500 error from some server. so i changed source as below and then it works.

HtmlInputElement.cs

``` cs
        internal override void ConstructDataSet(FormDataSet dataSet, IHtmlElement submitter)
        {
            var type = Type;

            if (type.IsOneOf(InputTypeNames.Submit, InputTypeNames.Reset))
            {
                if (Object.ReferenceEquals(this, submitter))
                    _type.ConstructDataSet(dataSet);
            }
            else
                _type.ConstructDataSet(dataSet);
        }
```

**Comment by FlorianRappl** [comment]
Can you open another issue for this?

**Comment by tsu1980** [comment]
ok
