### ISSUE TITLE
CSS color codes

### ISSUE THREAD

**Issue by mretlenj** [AngleSharp/AngleSharp#132]
Hi,
we use AngleSharp and have feature suggestion.

Currently, If the lib parses CSS colors, it replaces the hex codes (e.g. #FF00AA) by a rgba() function. This is not supported by email readers and so it has to reverted by us in the code (we're using some regex expressions to find what needs converting back). It would be nice if the original hex codes are not changed, so is it possible to have extra option when parsing?

**Comment by FlorianRappl** [comment]
I think this is related to #131. The upcoming version (v0.9) of AngleSharp will be more agile in that regard. Practically you can have access to the original representation, which will be the hex representation in your case.

Note that this applies to everything in CSS - not only to colors. In effect it will allow round-trip #38.

Since I closed the other issue (#131) I will leave this one open.

**Comment by Lavdaft** [comment]
Hello Florian, so... I have the version v0.14.0 of AngleSharp and that is still happening: it replaces the hex codes (e.g. #FF00AA) by a rgba() function. It also replace text like "red" or "green" to it's respective rgba. How can I disable that?

**Comment by FlorianRappl** [comment]
I think you mix up the stringified version (e.g., by using `ToCss()`) with the object model of CSS. Through the object model you can obtain the original representation; but the string representation is fixed (as is in the browser).

The stringified version, however, can be controlled by *you*. If you use it directly (i.e., without any arguments) you get a *default* formatter, which follows fixed rules (e.g., presenting every color as its `rgba`). You could create your own formatter, which essentially just uses the default formatter except for stringifying CSS color values.
