### ISSUE TITLE
Parsed CSS can have extra whitespace

### ISSUE THREAD

**Issue by mganss** [AngleSharp/AngleSharp#134]
Example:

``` C#
var html = "<Div style=\"background-color: http://www.codeplex.com?url=<!--[if gte IE 4]><SCRIPT>alert('XSS');</SCRIPT><![endif]-->\">";
var parser = new HtmlParser(new Configuration().WithCss(e => e.Options = new CssParserOptions
{
    IsIncludingUnknownDeclarations = true,
    IsIncludingUnknownRules = true,
    IsToleratingInvalidConstraints = true,
    IsToleratingInvalidValues = true
}));
var dom = parser.Parse(html);
var div = (IHtmlElement)dom.QuerySelector("div");
var bg = div.Style.First().Value; // "http   "
var css = div.Style.ToCss(); // "background-color: http   ;"
```

If this is expected behavior because the input is already invalid, is there an easy way to customize the output and trim whitespace from the value?

**Comment by FlorianRappl** [comment]
The easiest way would be to create your own `IStyleFormatter`, which is composed of the original one, but has a different implementation (wrapper) for the `Declaration` method. You would pass a trimmed value on.

But you need to supply an instance of your converter when calling `ToCss` - otherwise it won't work.

In general I think what you are trying to do will become easier in v0.9. With the same parser options as above you would generate a much more "literal" output. I don't know if I can finish it tonight, but it is on its way.

**Comment by mganss** [comment]
:+1:
