### ISSUE TITLE
File names with the wrong case

### ISSUE THREAD

**Issue by joelverhagen** [AngleSharp/AngleSharp#138]
I am tinkering with building AngleSharp on Mono. I have found that some files have a different case in their file name versus their reference in the .csproj. I got the AngleSharp.Core.dll and the associate test assembly to build with the following changes:

```
renamed:    AngleSharp.Core.Tests/Html/HtmlWithSVG.cs -> AngleSharp.Core.Tests/Html/HtmlWithSvg.cs
renamed:    AngleSharp/Dom/Html/HtmlHRElement.cs -> AngleSharp/Dom/Html/HtmlHrElement.cs
renamed:    AngleSharp/Dom/Html/HtmlRPElement.cs -> AngleSharp/Dom/Html/HtmlRpElement.cs
renamed:    AngleSharp/Dom/Html/HtmlRTElement.cs -> AngleSharp/Dom/Html/HtmlRtElement.cs
renamed:    AngleSharp/Dom/Xml/XMLDocument.cs -> AngleSharp/Dom/Xml/XmlDocument.cs
renamed:    AngleSharp/Dom/Xml/XMLElement.cs -> AngleSharp/Dom/Xml/XmlElement.cs
renamed:    AngleSharp/Html/InputTypes/DateTimeInputType.cs -> AngleSharp/Html/InputTypes/DatetimeInputType.cs
renamed:    AngleSharp/Interfaces/Css/ICSSStyleSheet.cs -> AngleSharp/Interfaces/Css/ICssStyleSheet.cs
```

I can submit a pull request if you'd like, but I am not sure if you'd rather rename the files or update the project files. Either way, they need to match since Unix systems are case sensitive in their file name.

My only concern is that I am not sure how Git on Windows treats changing just the case of a file.

**Comment by FlorianRappl** [comment]
Yes please. Since I do most AngleSharp dev on Windows machine (filenames ci) I only see these subtle errors here on GitHub (or via inspection of the git tree). I already named a few outliers in the past but I seemed I missed the ones you've indicated here.

A PR would be much appreciated! (git on Windows should be fine I guess, I did the former renaming also on Windows)
