### ISSUE TITLE
Split AngleSharp.Core

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#139]
As outlined in the blog (http://anglesharp.github.io/blog.html) I will try to split the _AngleSharp.Core_ library in some smaller pieces (3-4). I think the NuGet distribution won't be affected until (shortly before) v1.0.

Also in the future there may be a complete version of AngleSharp (single library) using ILMerge (http://www.microsoft.com/en-us/download/details.aspx?id=17630). I don't know if it will be distributed, but in principle there is no argument against it. In theory the currently distributed version will remain the complete core (either by containing all core libraries, or by containing the merged libraries).

Hence for users there is nothing that changes. I think that this change could give authors more freedom. They could, e.g., just pick the HTML parser and therefore skip the CSS parser. Or the other way round. Or they provide their own DOM implementation. Maybe they don't care about the parser at all and they only want the interface specifications. I think all these scenarios can be enabled more lightweight by splitting the core.

Currently proposed are the following parts:
- Common,
- Html
- Css
- Extensions / Complete

They form a diamond with Common having no dependency. Any thoughts, wishes or comments?

**Comment by corliss** [comment]
Just wanted to state that as a user i find the single assembly extremely convenient. I really dislike the packages out there that create separate assemblies for different features, which makes them awkward to use and test. I don't see any benefit to this. All the choice-related benefits in the post above are already available. Each additional assembly increases the complexity with which people have to wrap their heads around your product.

The ILMerge proposal will not work with non-Windows solutions, as it says on the download page. I've previously experimented with ILMerge and found it to pretty worthless.

So please, reconsider this and continue AngleSharp as a single library. It is already in a nirvanic state :)

**Comment by FlorianRappl** [comment]
I think it depends what you want as a user. If you want everything in AngleSharp then the single assembly is certainly appealing. If you only care, e.g., about the HTML5 part then you get a lot of unused functionality with the current approach.

The ILMerge approach would be incorporated into the build process. Users would not see it or have to use it. They only get the current package and have everything in a single library.

So the idea would be to have more fine-grained packages; AngleSharp.Core.Common, AngleSharp.Core.Html, ..., but also a single core package AngleSharp - which is the currently delivered one. But maybe it would be too confusing. I guess I need more opinions.

Work on this item has not started so there is plenty of room for discussion.

**Comment by Suchiman** [comment]
An alternative to ILMerge i've seen today also would be [IL-Repack](https://github.com/gluck/il-repack).

Anyway i have related feelings to splitting like @corliss .
Single assemblies are convenient, often even promoted and makes the development easier for us and you (no additional work on decoupling stuff that is currently more tightly coupled or even hard to decouple).

Sure there are always features that aren't always used, JSON.NET is certainly in most cases just used for (de)serialization, rather rarely for JSON Path.

Since the JIT provides a pay-as-you-use principle on CPU Overhead and AngleSharp is also still pretty small with ~500kB, nothing compared to the megabyte sized roslyn assemblies, it would be probably hard to measure the CPU/RAM overhead before and after the split.

**Comment by SOHODeveloper** [comment]
I have fought the modularization issue since I started .NET programing with version 1.0 back in the dark ages.  Over the years I have created a large private library to provide common code across numerous products and solutions.  I started with the concept that each namespace was a different assembly/dll under the theory that they would be small and would not require unnecessary references, (for instance WPF modules in a services).  Over the years, I have discovered that I made my design too modular, but undoing would take weeks due to its numerous uses.

That said, I do still like some degree of modularity.  With NUGet being able to auto load dependencies, it is not an overbearing issue for developers to include one or two pieces and auto install the core portion.  Given that currently all parts of AngleSharp have only one set of dependencies, the splitting is probably unnecessary.  If the individual functionalities become large (or say one of them does), then splitting should be revisited

**Comment by ghost** [comment]
I vote for leave it all as one. It's still small size wise and in any library/package how often do you use the majority of the features, most of the time its just a small percentage.
Also, having 360k nuget downloads gives people confidence and promotes Anglesharp, whereas if you split it up there will be more packages with less downloads

**Comment by FlorianRappl** [comment]
Certainly, yes. But, e.g., if the HTML library depends on the Core (which provides the interfaces / contracts and the whole configuration system / ceremony), then the Core will at least have as many downloads as the HTML part. Similarly, if there is a "full" package (i.e., containing CSS, HTML, Core, and maybe some of the official addons), then all of the individual ones will have at least as many downloads as this "full" package.

But I am certainly with you on the size aspect: It's not too large and currently the size of the NuGet (> 1 MB) is mostly determined by having three AngleSharp libraries (the PCL, the SL, and the .NET 4 version) in it.

**Comment by qaqz111** [comment]
I am sorry that I did not consider this question thoughtfully.

Split a core is not a wrong idea, since many works may only need one or two functionalities. However, to most projects, it's sooooooooo ugly that tons of dlls have to go with the final .exe files!

In my case, I wrote a small tool to grab data from the internet, the final exe file is less than 200KB but with a so big dll which was bigger than 1200KB. This just make me feel...er, a little weird. After all the program uses only a small part of the dll, but I have to bundle a dll that was far bigger than the main exe file!

**Comment by qaqz111** [comment]
Generally, there are several ways the library can be provided:
- An all-in-one lib
- Splitted libs
- Source code with a machenism to include/exclude specified functionalites into/from final build

To the coder users, I think the best way is a switchable source code, but in **JUST ONLY ONE** file. This is possible for c# libs.

There's an example here:

> functionA.cs :

``` C#
#if FUNC_A
namespace MYLIB.FUNC_A
{
    using System.XXX;
    using System.YYY;

    //code goes on...
}
#endif
```

> functionB.cs :

``` C#
#if NO_FUNC_B
#else
namespace MYLIB.FUNC_B
{
    using System.ZZZ;

    //code goes on...
}
#endif
```

There are 2 points here:
1. Use compiler directive #define and #if to control inclusions/exclusions
2. Put 'using' statements IN namespace scope!

Thus, the final all-in-one code file is easy to produce, just copy all the codes into a single file, and insert '#define's into it:

> MyLib.cs

``` C#
#define FUNC_A // if you do NOT need this functionality, comment out this line
#define NO_FUNC_B // if you NEED this functionality, comment out this line

/* content of functionA.cs */

/* content of functionB.cs */
```

To the library developers, they can manage their project as usual, separate different parts into different .cs files, and the published all-in-one source code file can be generated with a script automatically.

This is an attractive idea, but not friendly to nuget, in other words the coder users can not recive the version update information and manage the lib through nuget package manager.

The famous sqlite library used a similar form to publish the lib, they call it amalgamation, but this project is written in C.
I have to say, it IS comfortable to use that kind of 3rd-party libraries in my project.
You can take a look at here: [Sqlite amalgamation](http://www.sqlite.org/download.html)

But of couse I am not requesting the author to change AS into this form, after all there will be a lot of boring work to do ;)

**Comment by qaqz111** [comment]
The 'all-in-one lib' and 'splitted libs', in most case, I prefer the all-in-one lib too.

To the final users of productions, rather than the size of each single file, they will prefer a clean bunble which contains as fewer files as possible, that makes people feel tidy, clean and robust.

To the coder users, the multiple libs of one library can confuse them, especially to newbie coders. And in fact, tons of 3rd-party dlls increase the difficulty of project management works.

So, if there will be only one form exist between all-in-one and splitted libs, I vote for leave it all as one, too.

As for my case mentioned above, it really is a small problem, there ARE solutions to make the final output into a single smaller file, if it really needs to be.

At last, the comments I posted are just for discussion, not a feature request.
To me, it was both acceptable of an all-in-one lib and splitted libs :)

**Comment by FlorianRappl** [comment]
For a .NET application there is nothing wrong with a really small executable (compared to much larger libraries). Simple reason: You may put _all_ the functionality _independent_ of the platform being used in a library. The executable then just provides the platform dependent interfaces (e.g., output to `Console.WriteLine` and input via `Console.ReadLine`). This design is the client application equivalent of having a (Web / REST) API and some application (web, mobile, ...) accessing it.

Personally, I am still looking into the topic, even though my feeling tells me that we already settled on the current solution.

**Comment by Code-Grump** [comment]
As a **consumer** (thanks to the power of NuGet), the difference between a package containing a single assembly or having references to multiple dependencies is largely academic. If you look at popular package **[Microsoft.AspNet.WebApi](https://www.nuget.org/packages/Microsoft.AspNet.WebApi/)** you'll find it's just a container package which references the various component dependencies. It gives me the luxury to choose the parts which are relevant to my use-case or just grab the big "give me everything" package.

As a **producer** having multiple packages is a significant burden, as each needs to be maintained as a separate deliverable with its own version number (hopefully following semantic versioning). Managing compatibility between packages is the biggest headache. Semantic versioning can help here if you can truly keep to the rules to avoid breaking changes, but it's a significant burden on the producer.

The biggest advantage to this kind of packaging-by-feature approach is that you can develop and deploy those features to a different release cycle without impacting users that aren't involved with that component. For example, the core components are likely to be relatively stable at some point, where the satellite components will continue to shift. If I only use the core components, I don't have to keep going through an upgrade process.

There's also a significant usability advantage where there is a need to swap out components; it gives the opportunity to create packages which are tailored for that specific configuration. My current scenario involves using AngleSharp to automate some SpecFlow tests and I'm using Microsoft's OWIN TestServer package to run everything in memory. Having an AngleSharp package which targets `HttpClient` or `HttpMessageHandler` would be a convenient way to get an in-memory test project going quickly.

It's also worth mentioning that the NET Core platform is delivered by NuGet packages to select the features you need. As the features of AngleSharp grow, it makes sense to consider the advantages of breaking it down by feature, but it's not a free lunch.

**Comment by EamonNerbonne** [comment]
I'd advise against this unless you really know the upsides:
- There is a build-time hit the more assemblies your project references. That is, the more nuget packages (i.e. assemblies) you split this into, the longer people that reference AngleSharp will need to wait for builds; the slowdown does add up to humanly (barely) noticable differences in realistic projects (from experience) even on fast machines.  Personally, I really dislike slow builds.
- Also, you're going to have to consider the possiblity that people will run different versions in that diamond inheritance hierarchy - binding assembly redirects are a hassle, and issues won't make your users happy even if its not your fault.
- of course nuget restores tend to take longer.  
- it's probably more work for you
- if you get the split wrong for any reason; i.e. some bit of the html parser is needed by css or vice versa despite your expectations, you're going to be facing breaking changes to the api requiring a major version bump in nuget.
- I suspect (but haven't measured) that application startup time is faster if you merge assemblies.

Unless you expect the size savings to be significant to many users, I'd advise against this.  It's true that microsoft themselves do this kind of thing too, but well, (A) they don't always make the best choices so that's no guarrantee this is a good option, and (B) something like asp.net mvc is a much larger project for which the advantages of splitting up are probably much more significant than for you.  They may really have separate maintainers, and occasionally separate release cycles, and at the very least a more diverse functionality base where users using only parts of the system (e.g. bundling and minification without the rest) are quite common.  How many of your users will use the css parser but not the html parser?

**Comment by drungrin** [comment]
I believe that you should aim to use extensions methods, like ASP.Net's configuration.

I don't like the With(Anything) approach, I need to check the sources to replace the ICookieProvider, for example.

I believe you should have:

WithMemoryCookieProvider()
WithCookieProvider(ICookieProvider provider)

WithDefaultRequester()
WithRequester(IRequester requester)

the HttpClientRequester NuGet should provide an:

WithHttpClientRequester() extension method

now I use:

```
BrowsingContext.New(Configuration.Default
                .With(new HttpClientRequester(_httpClientFactory.CreateHttpClient()))
                .WithDefaultLoader()
                .WithLocaleBasedEncoding());
```

But it can be, on a custom config:

```
BrowsingContext.New()
                .WithDefaultHtmlParser() // From his NuGet
                .WithDefaultCssSelector() // From his NuGet
                .WithHttpClientRequester() // From his NuGet
                .WithDefaultLoader()           
                .WithLocaleBasedEncoding())
                .WithoutSvgElements()); // maybe removing this service there or receiving options on WithHtmlParser, to have a way to remove "default services"
```

**Comment by FlorianRappl** [comment]
It is *NuGet* (single g) and the *AngleSharp.Io* library (I guess that is what you called "HttpClientRequester nugget") contains an appropriate extension method. The second approach is used already (the `With` is just the most generic approach, which is used directly or indirectly by other extension methods - this is all the same/similar approach).

Default services can be removed. Actually, it is just an enumerable and you can decide to leave out certain items in the enumeration.

**Comment by drungrin** [comment]
Edited, the double g was from auto correction. 

The HttpClientRequester isn't on devel branch. It has only a few With* extensions methods, that was why I suggested that.

But since you are aware of that, I believe that'll be well done.

And thanks for the library.

**Comment by Athari** [comment]
@EamonNerbonne Splitting versions and releasing different versions of subpackages is unnecessary. All packages can have the same version. This solves all problems with "burden" and whatnot. It doesn't solve the problem with "diamonds", but the end result is absolutely the same as with a monolithic package.

The only case when increasing a version even without any actual changes can break more things is when a dependency has max supported version set, but usually that's not the case.

That being said, AngleSharp isn't exactly a huge library (1.2 MB dll, 3MB nupkg) and its subparts don't have third-party dependencies, so I don't think there're any practical benefits in splitting. Furthermore, the most common case would probably be parsing HTML, which would exclude only 1, maybe 2 assemblies from the proposed set.

**Comment by EamonNerbonne** [comment]
@Athari It's a little far fetched, but sure, splitting makes diamonds worse.

For example:

You depend on packages A and B
A depends on AngleSharpX
B depends on AngleSharpY
AngleSharpX and AngleSharpY depend on AngleSharpCore

Now you suggest X, Y and Core have the same version numbering scheme.  But if A depends on 2.3 and B depends on 3.7 - what is nuget to do?  It may well be that 3.7 would work fine - but it's not going to figure that out.  At best it'll try AngleSharp*Core* at 3.7, but it'll leave AngleSharpA at 2.3 - and that's going to be mess.

Not to mention the fact that all this interacts with a host of other factors, including which framework tooling you're running on - not all tooling is equally great in this scenario.

This kind of stuff is just a hassle with little upside.  The only way this is going to work well if the packages truly are loosely coupled, and even then - people using multiple AngleSharp package will have slower builds.  So you want decent size savings and for this to be worth it, and need loose coupling.

It's not as bad as it used to be, incidentally - perhaps because asp.net core tried this route and they needed to improve the tooling.  But still; just noting all the issues people had with those packages despite the fact they probably considered *specifically* that usecase when designing the tooling merely confirms it's not an entirely free lunch.

I'd still suggest at the very least caution with assembly splitting.

**Comment by Athari** [comment]
@EamonNerbonne Both split and monolithic packages cause issues in that case. It's the choice between "will package A which depends on AngleSharpX 2.3 work with AngleSharpX 3.7" and "will AngleSharpX 2.3 which depends on AngleSharpCore 2.3 work with AngleSharpCore 3.7". If major versions are different, I'd say both are unlikely, so you get broken solution and have to resolve the conflict manually in either case, most likely by upgrading A.

Actually, if you have split packages, you have more options. You can force "monolithic" version by adding dependency on AngleSharpFull 3.7 to your root project, you can nudge AngleSharpX's version forward and try finding a compatible combination. Not that it's a good thing to do or likely to succeed in general case, but it's still more tools at your disposal, at least in theory.

(Core builds currently don't support any modes other than "minimum" when resolving dependencies, so your prediction is exactly what will happen. With classic builds versions may resolve differently depending on how dependencies in your root project are specified.)

**Comment by 304NotModified** [comment]
As this feature is open for a while, isn't a better idea to move this to 2.0 (or just drop it)

**Comment by EamonNerbonne** [comment]
I vote to drop it, obviously ;-).

**Comment by FlorianRappl** [comment]
So the split is done and will be real with v0.10, however, it is not as big as outlined in the OP. We have:

- Common, Html, Extensions
- Css

There is no complete package planned, however, `AngleSharp.Browser` (or similar, name tbd) could aggregate all these already.

**Comment by 304NotModified** [comment]
Cool, so this one could be closed? 👼

**Comment by FlorianRappl** [comment]
Yeah let's close it!

**Comment by 304NotModified** [comment]
🎉 great!

PS: A bit related to this change, I made https://github.com/AngleSharp/AngleSharp/issues/709
