### ISSUE TITLE
Behavior of OpenAsync

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#158]
The `OpenAsync` extension methods of `IBrowsingContext` work fine, but are (in my opinion) problematic with asynchronous requests beyond the loading document. Should these resources be awaited as well? If not, then, e.g., stylesheets would (potentially) not be ready after resuming execution.

In my opinion the `OpenAsync` should really wait until all resources are downloaded / failed / timed-out.  If one really cares about the resources as fast as they are, one can query the document already in the browsing context after issuing `OpenAsync` (the document is already available directly after receiving the response headers, it will then be populated asynchronously).

However, I see potential problems. If a user is not careful a whole webpage (including many / all resources) are downloaded. This will for sure take longer than downloading only the requested document. Now complaints about bad performance (even though parsing was finished after a few milliseconds the rest of the downloads takes a couple of magnitudes longer) are imminent.

Opinions?

**Comment by merthsoft** [comment]
What about an `OpenAllAsync` (or something better named (: ), that awaits until everything is loaded in. Or, an optional parameter on `OpenAllAsync` that's `waitForAllResources` or something, and when it's true it waits for everything. That was you can preserve both use cases. Sometimes the performance penalty of loading in everything is okay, because what you really need is everything (or, like in my case, it's a nightly task that scrapes a page, so I'm not terribly concerned with performance as much as easy to code/maintain).

**Comment by FlorianRappl** [comment]
Yes - I believe that in the future there may be additional comfort options to specify subsets of resources to load easier (right now you can use filters to limit the resources).

**Comment by FlorianRappl** [comment]
That will be already part of v0.9.5.

**Comment by FlorianRappl** [comment]
This has been implemented already in #178.
