### ISSUE TITLE
Erorr: System.Net.HttpWebRequest.set_UserAgent cannot be used on the current platform.

### ISSUE THREAD

**Issue by silverbird** [AngleSharp/AngleSharp#16]
Hi, I am new to AngleSharp. First of all, I would like to say to the author, Great Job, thanks!

I am using AngleSharp to write a small Windows Store app. I've tried to call DocumentBuilder.HtmlAsync() to get a html document object, but I got a runtime error:

A first chance exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
Additional information: The API 'System.Net.HttpWebRequest.set_UserAgent(System.String)' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.

Here is what I am doing. Am I missing something?

```
        AngleSharp.Configuration.UseDefaultHttpRequester = true;
        var document = await AngleSharp.DocumentBuilder.HtmlAsync(new Uri("http://stackoverflow.com/questions/20115672/how-does-the-static-type-affect-this-code"));
```

My developing environment is Windows 8.1 and Visual Studio 2013 express for Windows Store app.
Thanks

**Comment by FlorianRappl** [comment]
Thanks for the report!

Hm, the problem is the implementation of the `HttpRequest`  for Windows store apps. I did not get that error executing it in a .NET 4.5 environment. However, I know that there might be problems, since the implementation for Windows Store apps is slightly different and has a lot of issues.
Right now I do not have a silver bullet. I could remove this field from the default fields (and I will most likely do that). However, you do not have to wait for me doing this update (I am currently busy on another project, which is why AngleSharp has not received any major updates lately - but there will be some!).

You could just remove the User-Agent field by setting a new, empty dictionary or removing the key from the existing dictionary. With the latest version (available as of now) the DefaultHeaders property of the default requester gives you access to a static variable. This means that changing the default headers will change the behavior for all upcoming requests.

An example:

```
    static void Main(string[] args)
    {
        TestUserAgent();
        Console.ReadLine();
    }

    static async Task TestUserAgent()
    {
        var headers = new Dictionary<string, string>();
        headers.Add("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3");
        Configuration.UseDefaultHttpRequester = true;
        Configuration.GetHttpRequester().DefaultHeaders = headers;
        var document = await AngleSharp.DocumentBuilder.HtmlAsync(new Uri("http://whatsmyuseragent.com/"));

        Console.WriteLine(document.QuerySelector("#body_lbUserAgent").TextContent);
    }
```

So in your case the easiest way would be to do the following:

```
AngleSharp.Configuration.UseDefaultHttpRequester = true;
AngleSharp.Configuration.GetHttpRequester().DefaultHeaders = new Dictionary<string, string>();
var document = await AngleSharp.DocumentBuilder.HtmlAsync(new Uri("http://stackoverflow.com/questions/20115672/how-does-the-static-type-affect-this-code"));
```

Hope this solves your problem - otherwise I will take a much deeper look at it!

Florian

**Comment by FlorianRappl** [comment]
Just to emphasize: The Configuration is global, i.e. once you changed it all future requests will use this. The same is true for the DefaultHeaders property of the default HTTP requester. So the shown configuration has just to be applied once.

Doing it when your app starts should be sufficient.

**Comment by silverbird** [comment]
Hi, Florian, thanks for the quick reply. I have been using DocumentBuilder.Html() instead since I find this issue and it works great. I've also tested the solution in your answer. It indeed fixed the problem.Great job!

btw, I have download the project source code as zip file, but I cannot open the AngleSharp.csproj(in AngleSharp folder) in Visual studio 2013 express for Windows Store app. It says:

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 

Whatever,I would say, this project is of great importance to Windows developers, it fills a huge gap. It's awesome and you're a Hero.Thanks!

**Comment by FlorianRappl** [comment]
Hm maybe VS 2013 express does not support portable class libraries. I will have a look at that!

Again thanks for your nice words. I will try to bring in more features and make it as complete as possible.
