### ISSUE TITLE
Is the feature "GetComputedStyle" ongoing?

### ISSUE THREAD

**Issue by GCCFeli** [AngleSharp/AngleSharp#18]

**Comment by GCCFeli** [comment]
I'm very interested in this feature. I wonder if I can join you to develop this feature :)

**Comment by FlorianRappl** [comment]
That would be wonderful. Recently I did not find the time to continue developing, which is why I am way back beyond my schedule on this project. However, I still plan on continuing with this project. I would appreciate some help : )
I already wrote a little renderer a couple of months back, so I have at least some experience and plan how to implement style computation of elements.

**Comment by GCCFeli** [comment]
Could you please share your your work and plan to me? My email address is feli#gccfeli.ccn

**Comment by FlorianRappl** [comment]
I'll write you a mail tonight!
