### ISSUE TITLE
[Q] selecting by some style value

### ISSUE THREAD

**Issue by useruser1** [AngleSharp/AngleSharp#180]
var source = @"&lt;!doctype html&gt;
&lt;html&gt;
&lt;style&gt;
.class1 {
font-size: 10pt;
}
.class2 {
font-size: 15pt;
}
&lt;/style&gt;
&lt;body&gt;
&lt;div class=class1&gt;somediv1&lt;/div&gt;
&lt;div class=class2&gt;somediv2&lt;/div&gt;
&lt;/body&gt;";

var document = parser.Parse(source);

How can I select only div with 15pt font size ?

**Comment by useruser1** [comment]
maybe document.StyleSheets ?

**Comment by useruser1** [comment]
I found solution like that - 
  doc.QuerySelector((css.Rules[0] as ICssStyleRule).SelectorText) ...

**Comment by FlorianRappl** [comment]
What you are doing is a little bit too complicated ... Why not just use

``` csharp
var theOnlyDivWithClass2 = document.QuerySelector("div.class2");
```

**Comment by useruser1** [comment]
because I need to make a selection by style

**Comment by FlorianRappl** [comment]
Then you need to do it the hard way - go over all styles, obtain the selectors of all styles that fit, aggregate all selectors into one, and use the resulting selector for your query.

**Comment by TechnikEmpire** [comment]
I just needed to do this now and came across this thread in a quick search for a lazy solution before trying my own solution. My own solution is actually a really simple and fast one, provided you don't have enormous HTML input. Just grab the whole style entry, split it and then build out a string with each style name prepended by `"data-"`. 

Complete code example:

``` C#
private static readonly Regex htmlSourceRegex = new Regex("style=\"([^\"]+\")");

// Run regex against input HTML to capture all instances of `style="...."`
var styleMatches = htmlSourceRegex.Matches(htmlSource);

// Iterate over matches
foreach(Match match in styleMatches)
{
    // Our regex has a single capture group. Group 0 is always there, and is the full captured text. So we want >= 2, because `Groups[0]` will be everything in between the quotes for the style attribute.
    if(match.Groups.Count >= 2)
    {
        //Grab the string of everything in between the style attribute quotes.
        var value = match.Groups[1].Value;

        StringBuilder result = new StringBuilder();

        // We split by the style delimiter, the semi-colon.
        var split = value.Split(';');

        foreach (var splitAttr in split)
        {
            // In here, we'll our splitAttr will be values like "font-size: 30px", so we split by the key/value delimiter, the colon.
            var keyValueSplit = splitAttr.Trim().Split(':');

            if (keyValueSplit.Length == 2)
            {
                // Now just convert the key and value to a unique attribute and append it to our new string.
                result.Append(" data-" + keyValueSplit[0].Trim() + "=\"" + keyValueSplit[1].Trim() + "\"");
            }
        }
        // Finally, replace the whole style="..." entry with our new custom attributes string.
        htmlSource = htmlSource.Replace(match.Value, result.ToString());                    
    }
}

// Now, let's parse our modified source
var document = parser.Parse(htmlSource);
```

You can then simply build selectors such as:

``` C#
var results = document.QuerySelectorAll("div[data-font-family=\"monospace\"][data-font-size^=\"34\"]");
```

This will successfully select elements like this:

``` HTML
<div data-canvas-width="34.377263075" style="left: 116.683px; top: 336.495px; font-size: 34.9751px; font-family: monospace; transform: scaleX(0.920005);">50</div>
```

Of course the above is the original input HTML before conversion using the above method. The transformed and thus selected HTML will, after the conversion, look like this:

``` HTML
<div data-canvas-width="34.377263075" data-left="116.683px" data-top="336.495px" data-font-size="34.9751px" data-font-family="monospace" data-transform="scaleX(0.920005)">50</div>
```

If you're terrified about using a regex on HTML, you can do a first-pass and use AngleSharp to collect the style attribute string value, then use that as your captured find/replace source instead of relying on regex. I have very strict control over the HTML I'm processing so it's not a concern for me.
