### ISSUE TITLE
AngleSharp with NET 4.0 on VS2010 under Windows 7

### ISSUE THREAD

**Issue by lgaudouen** [AngleSharp/AngleSharp#184]
Is it possible ?
(and how ?)

**Comment by FlorianRappl** [comment]
Sure. .NET 4 is supported. Either you compile it from the sources (_AngleSharp.Legacy_) or you'll use NuGet. Either way, you'll need additional dependencies (_Bcl.Async_) (which should be resolved automatically via NuGet).

Compiling with VS2010 requires C# 5. Naturally, VS2010 does not ship with C# 5. There is, however, the possibility to take the RC of C# 5, which replaces the used compiler. Since I guess you don't want to do this, I would recommend using the NuGet package.
