### ISSUE TITLE
'windows-1252' is not a supported encoding name. Parameter name: name

### ISSUE THREAD

**Issue by riplakish** [AngleSharp/AngleSharp#19]
The error is thrown when trying to retrieve a web page via HtmlAsync in a Windows Phone project. I am using version 0.5 via NuGet.

Example:
var document = await AngleSharp.DocumentBuilder.HtmlAsync(new Uri("http://stackoverflow.com"));

**Comment by FlorianRappl** [comment]
Thanks for reporting this error. I will try to look into that. It sounds like this is not per-se an AngleSharp error, but comes from the reduced .NET package. I will try to find a good solution such that a proper fallback encoding will be used. Of course such an error should never hit a user. Will be fixed in the next release (coming next week, if not v0.6 then a minor fix to v0.5.1).

**Comment by FlorianRappl** [comment]
Unfortunately that encoding is not valid on the WP platform. As there is no `GetEncodings()` method the only chance is to use a try-catch and return a default encoding. I will use UTF-8 as default encoding. Hope this will fix your problem to your needs. I will push an update on Monday or Tuesday the latest.

**Comment by devmondo** [comment]
if i may say, UTF-8 will be adequate enough for all cases.

thanks in advanced for any updates, i like this project :)

**Comment by FlorianRappl** [comment]
This has been fixed in AngleSharp v0.5.1.
