### ISSUE TITLE
DOM Click

### ISSUE THREAD

**Issue by zedr0n** [AngleSharp/AngleSharp#196]
Hi

I've been using button.Form.Submit() to login to the website but as a headless browser it would make more sense to click the login button. Looking at DoClick() though

```
    public override void DoClick()
    {
        var form = Form;

        if (IsClickedCancelled() == false && form != null)
        {
            var type = Type;

            if (type.Is(InputTypeNames.Submit))
                form.Submit(this);
            else if (type.Is(InputTypeNames.Reset))
                form.Reset();
        }
    }
```

it doesn't return Task<IDocument>. Doesn't it make sense to change this to async Task<IDocument> method which would return the new document or existing one if it's a reset after awaiting the method? 

At the moment an async method is kicked off within the method but there's no way to action on that. Or am I missing something here?

**Comment by FlorianRappl** [comment]
Makes a lot of sense for sure, but I can't present a solution due to two problems:
- Why should `DoClick` return a `Task` in general? The scenario you describe (click button -> submit form) is only one of _many_ possible outcomes.
- If I change the return value for this method (which would then be different to what the W3C spec says, but nevermind - already `Submit` from a form returns a `Task` to make things easier) returning a dummy (already finished) task from _all_ other implementations, which other methods would be required to change as well?

So the way I thought about that (and I even went so far considering `Submit` to return `void`) is that the corresponding `IBrowsingContext` will hold that task. If you want to know when the current document changes, that would be your point of interaction. This already works partially (unless my train of thoughts is completely misaligned).

All in all `IBrowsingContext` is the future for all interactions where you would think "and how to get more information about _insert internal structure here_". There are, however, some tiny steps I have to do beforehand (like making tasks / requests really transparent and well accessible + robust).

Any API suggestions (such a solution / answers to the two questions I raised) are highly welcome at this point in time.

Also thanks for your input. Much appreciated!

**Comment by zedr0n** [comment]
hm, these are valid points. In my app I'm taking a bit different approach, i'm bulding a representation of the website so 

```
public class Profile : IProfile
{
    private WebString _name;
    private WebNumber _age;
```

where WebString is a class which encapsulates the url, selector and a webclient object which will lazily async initialize the element represented by the (url, selector) pair.

```
public class WebItem<T>
{
    protected readonly AsyncLazy<IDocument> Document;

    protected readonly string _uri;
    protected readonly string _selector;

    // how long to keep the value alive for without refresh
    private readonly int _keepAlive = -1;

    protected WebClient WebClient;

    public async Task<bool> Exists()
    {
        var document = await Document;
        return document.QuerySelector(_selector) != null;
    }

    public WebItem(WebClient webClient,string uri,string selector)
    {
        _uri = uri;
        _selector = selector;
        WebClient = webClient;
        Document = new AsyncLazy<IDocument>(async () => await webClient.GetDocument(_uri));

    }

public class WebClient
{
    private ILoginService _loginService;
    private IBrowsingContext _browsingContext;
    public async Task<IDocument> GetDocument(string url)
    {
        Init();
        var document = await _browsingContext.OpenAsync(url);
        if(_loginService != null)
            document = await _loginService.WithDocument(document).DoLogin();

        _browsingContext.NavigateTo(document);
        return document;
    }
```

This is the idea which I came up with to simply wrapping the websites in an app. It allows accessing the elements as if they were local, each of them owning its own browsing context. Now the underlying webClient which wraps the browsing context can also register services ( like a login service which is going to click a button on login page ). That's why my primary object is Idocument associated with the element. Maybe it fits better to use browsing context as point of interaction. But I'll still need a way to await the state change to process the result. to keep it completely encapsulated. So given from what I've seen from Submit that's the way I went forward.

So to your question all element methods which can modify the document should return a Task. 

Not sure if that's at odds with your initial design but I've just started looking at AngleSharp so haven't understood the whole structure yet.

**Comment by zedr0n** [comment]
After looking at it in a bit more details I can see the Tasks structure on the document and can see that an element action creates a new task on the document. So is the design idea to do something like this:

```
async static Task<IDocument> Click(this IElement element)
{
    element.DoClick();
    await Task.WhenAll(element.Owner.GetTasks(element));
    // after all added tasks have completed the document is updated
    return element.Owner;
}
```

GetTasks(element) doesn't exist but there is OriginatedFrom which can be used to construct this easily. 

Or is the idea to await till all tasks complete on document? 

But then I would expect Submit() to also be a void if the expected path is to delegate all tasks handling to the owner document?

**Comment by FlorianRappl** [comment]
Sorry for my late reply. Yes, something like that would be the idea. However, the current notion of tasks won't be permanent. Actually, it looks like that one will be gone in the next version of AngleSharp. Instead, AngleSharp will place everything in the (task based) event loop (if processed in order) or downloads (if processed concurrently).

What will remain (and what will be encouraged) is the usage of events. AngleSharp currently has 2 types of events:
- DOM events
- Infrastructure events

The first one follows the DOM conventions and lives around `Event`. The second one uses the `IEventAggregator`. In the long run (potentially in the next version, otherwise in v0.9.5) I will remove the `IEventAggregator`. It will / should be more convenient to only have one type of events, which will be DOM-like event.

This also means that non-standard DOM events will be fired. They could be captured within scripting environments, e.g., JavaScript. The browsing context will fire such events as well, e.g., indicating that a new page is loading.

Potentially I'll find a solution to the problem described in this issue. But at the moment my best guess would be use events for such scenarios.
