### ISSUE TITLE
Can ATTR get data attribute value?

### ISSUE THREAD

**Issue by vickyRathee** [AngleSharp/AngleSharp#199]
Does ATTR extension method support the set only, i was looking to get some data items from element but throwing errors.

var source = "&lt;p class='some-class' data-id='32289'&gt; some text here&lt;/p&gt;&lt;p class='some-class' data-id='32290'&gt; some text here&lt;/p&gt;";

var parser = new HtmlParser();
var document = parser.Parse(source);
// with CSS selectors
var Selector = document.QuerySelectorAll("some-class").Attr("data-id");

//Throwing error

**Comment by FlorianRappl** [comment]
The problem is that this is not the same `Attr` as, e.g., `attr` in jQuery. The one you are using **sets** values decomposed from an object. The object should be an instance of an anonymous class. (This is all documented and visible from, e.g., Visual Studio)

Therefore, I recommend you to just use a `Select` and get the attribute's value for each element.

I guess there should be more extension methods to also cover the plain selection case. I'll add them in one of the next releases.

**Comment by vickyRathee** [comment]
Thank you and glad to know you are planning  to add these in new releases.
Any example how can get this using select? Because if i look on the details it has text, inner html and outer html. (i need to use QuerySelectorAll only to extract the item)

var Selector = document.QuerySelectorAll(css);
foreach (var item in Selector)
{
  Console.WriteLine(item.TextContent); // bold and italic 
 //Console.WriteLine(item.InnerHtml);  // bold <u>and</u> italic
 //Console.WriteLine(item.OuterHtml);  //<em> bold <u>and</u> italic </em>
}

**Comment by FlorianRappl** [comment]
You need to use `GetAttribute` as you want to get the attribute's value. I would do the following:

``` cs
var dataIds = document.QuerySelectorAll("some-class").Select(m => m.GetAttribute("data-id"));
```

**Comment by vickyRathee** [comment]
You're amazing... Thanks for the example and i saw you already implemented this for new releases.
FYI : We will be adding all this functionality in Data Scraping Studio (free web scraping software) - http://www.datascraping.co/

**Comment by FlorianRappl** [comment]
Very cool - thanks. I'll add it to the list of applications then!
