### ISSUE TITLE
No HTML 5 result

### ISSUE THREAD

**Issue by LeMoussel** [AngleSharp/AngleSharp#207]
I would to test AngleSharp HMTL 5 score with html5test.com site.
But I got no result `<div id="score"></div>` with this code :

``` C#
IConfiguration config = Configuration.Default.WithDefaultLoader().WithJavaScript().WithCss();
IDocument _ashDocument = await BrowsingContext.New(config).OpenAsync("http://html5test.com");
await Task.WhenAll(_ashDocument.Requests);

IElement scoreElement = _ashDocument.QuerySelector("#score");

Console.WriteLine(scoreElement.OuterHtml);
```

**Comment by FlorianRappl** [comment]
The JavaScript for HTML5Test.com is not yet working. There are several issues, but the most problematic one is the abstinence of some required objects, e.g., `Screen`. The development version of AngleSharp.Scripting tries to make it work and future versions will include dummies / placeholders for all these interfaces.

This is more an issue for AngleSharp.Scripting, which is why I close it here.

**Comment by FlorianRappl** [comment]
(Marked invalid as it concerns AngleSharp.Scripting)
