### ISSUE TITLE
No information witjh getComputedStyle()

### ISSUE THREAD

**Issue by LeMoussel** [AngleSharp/AngleSharp#213]
I got no information with `getComputedStyle()`
For example, with this code all properties of `CssStyle` are nul or empty 

``` C#
        public static async Task TestUrlASH(string address)
        {
            IConfiguration config = new Configuration().WithDefaultLoader().WithJavaScript().WithCss().WithCookies();
            IBrowsingContext context = BrowsingContext.New(config);
            IDocument document = await context.OpenAsync(address);
            // Comment of Florian : wait for the stylesheets to download and parse.
            await Task.Delay(10000);

            foreach (IElement linkElement in document.Links)
            {
                Console.WriteLine("Link : {0}   {1}", linkElement.Attributes["href"].Value, linkElement.TextContent);
                ICssStyleDeclaration CssStyle = document.DefaultView.GetComputedStyle(linkElement);
            }
        }

TestUrlASH("http://crawlbin.com/").Wait();
```

**Comment by FlorianRappl** [comment]
In general, I wouldn't bet on `GetComputedStyle` at the moment. It will be quite accurate going closer to v1 but right now the CSSOM is just not in that shape.

Nevertheless, I assume your problem is related to another topic (see #178). Are you sure that the related stylesheets are loaded when `GetComputedStyle` is invoked? You could, e.g., place an `await Task.Delay(10000);` (time set to 10s to be absolutely sure), to wait for the stylesheets to download and parse.

In the upcoming version `OpenAsync` will wait until everything has finished (i.e., `load` fires), which should simplify things.

**Comment by LeMoussel** [comment]
Florian, I place `Delay`, same result, nothing in all properties of `CssStyle`.

Rem : Excellent idea to wait until everything has finished (i.e., load fires) :+1:

**Comment by FlorianRappl** [comment]
It could be that the stylesheet does not load (i.e., fails parsing). How about the following test: parse simple HTML with the code above, containing a link to a very simple stylesheet. If that works, parse the same page, however, linking, e.g., to bootstrap as its stylesheet. In case of failure we know the reason. Alternatively, just use the CSS parser to parse the contained stylesheets of your original page.

I'll try to make sure CSS parsing / loading becomes as reliable as HTML parsing in the next version.

**Comment by FlorianRappl** [comment]
(Marked for v0.9.5 due to `GetComputedStyle`, however, CSS issues see #145)
