### ISSUE TITLE
How much of a rewind is required?

### ISSUE THREAD

**Issue by SimonCropp** [AngleSharp/AngleSharp#214]
I note in some cases you rewind the index in the input content. How much of a rewind is required?  ie if we rewind 1 character will we always read before doing another rewind. So is only 1  char required in the buffer, or do we need some higher number, or is it unbound?

**Comment by FlorianRappl** [comment]
The rewind only happens when too much was read. In most cases 1 char is enough, however, in some cases more chars have been consumed without purpose. In all these cases the method that consumed these chars knows how much to rewind. Therefore, I assume that it is alright.

Even though the `BaseTokenizer` only stores the current character, the `TextSource` has a much larger buffer (unbound; growing from the first to the last read char). Rewinds will therefore only access this reservoir and leave the underlying stream untouched.

**Comment by SimonCropp** [comment]
I ask since i would prefer not to keep such a large buffer in memory. If we can, for example, only keep a buffer of 10 chars in mem then we can move through the characters in small buffered window.

**Comment by FlorianRappl** [comment]
That is impossible since, e.g., `document.write` needs to modify that buffer. The underlying is (potentially) forward-only. Furthermore, at least "the start" (the length of this start is unknown - it may be nearly the complete document in extreme cases) needs to be stored for sanity checks in case of encoding changes.

Size-wise keeping this buffer is the least problem. If you parse a ~1MB text source (very large!) then the resulting DOM will be much larger anyway. Therefore, keeping the text source is really negligible compared to other structures, which are more dominant and even more important for the DOM.

**Comment by SimonCropp** [comment]
thanks
