### ISSUE TITLE
Login form submit problem

### ISSUE THREAD

**Issue by emrahyumuk** [AngleSharp/AngleSharp#217]
I want to submit login with my account, but there is a problem, i can't login any websites.

```
var config = Configuration.Default.WithDefaultLoader().WithCookies();
var browsingContext = BrowsingContext.New(config);

await browsingContext.OpenAsync("http://www.metalstorm.net/users/login.php");
await browsingContext.Active.QuerySelector<IHtmlFormElement>("form[action='login.php']").Submit(new
{
    login_email = "*********",
    login_password = "*********"
});
await browsingContext.OpenAsync("http://www.metalstorm.net/");

```

**Comment by FlorianRappl** [comment]
Why don't you wait until `Submit` has finished? Any reason for that?

**Comment by emrahyumuk** [comment]
I updated code. There is "await" in my code. issue continues.

**Comment by FlorianRappl** [comment]
Are you sure yet this is a problem with AngleSharp? (Most of the time it isn't).

Troubleshooting to boil down the problem at first:
- Does the form submit work?
- Are you sure you are logged-in after the form submit? (check the returned page!)
- Does the page require any JavaScript for the login to work (some pages may require this, e.g., to set some validation tokens or to retrieve third-party content)?

If the previous points (and related items) can be excluded and a MWE beyond specific pages (such as the one provided above) can be supplied, then this is indeed an issue with AngleSharp.

**Comment by emrahyumuk** [comment]
i submitted form and logged in on website. I submitted form with AngleSharp, checked returned document I'm not logged in. 

i can log in with web client like that.
http://stackoverflow.com/questions/11118712/webclient-accessing-page-with-credentials

**Comment by FlorianRappl** [comment]
Then something went wrong with your request. Potentially you are not filling out the right form fields. Again, the problem is too specific. If you can boil it down to a MWE (that is independent of that specific homepage) I can help you. Before that I am sorry - this is a free project and my resources are limited.

Logging-in / submitting arbitrary forms works in all tested scenarios for me (and others). Therefore, if anything fishy is happening (and that could definitely be) please try to distill the problem.

Remark: Since you seem not to be logged-in in the first place the problem seems to be with your form submission. Of course subsequent requests won't magically have you logged-in.

What to do next? Try another method with AngleSharp. Instead of using the convenience method of providing an anonymous object you could also explicitly select the required form fields and set their values. This way we can exclude that the decomposition of the AO into fields does not work as expected.

**Comment by FlorianRappl** [comment]
Potentially related to #274 / #280, otherwise not reproducible. Closed for the moment.
