### ISSUE TITLE
Empty CssText for simple style rule definition with version 0.6.0

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#22]
Just downloaded version 0.6.0 and found the following issue after a quick try:

For a simple style definition, the CssText property shows empty

string css = @"html{font-family:sans-serif;}";
var stylesheet = AngleSharp.Parser.Css.CssParser.ParseStyleSheet(css);

foreach (var rule in stylesheet.Rules)
{
      Console.WriteLine(rule.CssText);
}

The end result ends up something like this:   html {\r\n;;}

It used to work fine in version 0.5.1.

Anything I did wrong here?

**Comment by FlorianRappl** [comment]
Everything you do looks fine to me. I will investigate and fix this!
Thanks for your report!

**Comment by FlorianRappl** [comment]
Alright, I found and fixed the bug. I don't know yet if I'll release v0.6.1 in the next couple of days, or if v0.7.0 will be an early release.

The bug is only in the `CssText` property - everything gets parsed and therefore if you access the first rule (of the example above) as a `ICssStyleRule`, then you can access, e.g., the `CSSStyleDeclaration`. This gives you access to all properties, such as `FontFamily`.

I know right now this is inconvenient, but I'll promise to integrate further APIs that go beyond the official specification. However, these methods and properties won't be decorated with `DomNameAttribute` attributes.

Again, thanks for your report!
