### ISSUE TITLE
EMDASH in url query is translated to %14

### ISSUE THREAD

**Issue by gufi** [AngleSharp/AngleSharp#234]
IsNormalQueryCharacter in CharExtensions.cs does not consider this a normal character and % encodes it.

I have made changes to accept this character but i'm unsure if it is acceptable ( prepared locally but have not pushed to fork because if it isnt acceptable i'll just keep a local exception to the rules )

``` C#
public static Boolean IsNormalQueryCharacter(this Char c)
        {
            return (c.IsInRange(0x21, 0x7e) && c != Symbols.DoubleQuote &&
                c != Symbols.CurvedQuote && c != Symbols.Num &&
                c != Symbols.LessThan && c != Symbols.GreaterThan) || c == Symbols.EmDash;
        }

        /// <summary>
        /// EmDash character ( — )
        /// </summary>
        public const Char EmDash = (Char)0x2014;
```

**Comment by FlorianRappl** [comment]
Well, the question is why you consider that special character a normal query character. According to the specification outlined by the WHATWG group only ASCII characters are allowed in the query (see https://url.spec.whatwg.org/#urls and https://url.spec.whatwg.org/#ascii-string).

Do you have a test where this behavior of AngleSharp would result in invalid behavior? If so, are you sure that the server side is correctly setup (usually percent-encoded characters should be transformed back correctly). The query parsing is also described in greater detail at https://url.spec.whatwg.org/#query-state. Here the 0x21 is mentioned as lower boundary.

Could you please give an example of the URL you try to use? Much appreciated!

(Also [Charbase](http://www.charbase.com/2014-unicode-em-dash) mentions the URL encoding)

**Remark** But if the title of the issue is correct, then the mdash is translated to `%14`, while it should in fact be `%E2%80%94`. This would indeed be a bug, however, fixed differently. I'll look into that in the meantime.

**Comment by gufi** [comment]
after testing with %E2%80%94 in the url i was using that works as it should.. so it appears it's just incorrectly translating EMDASH.

so ya. The title is correct and that's the only issue

**Comment by FlorianRappl** [comment]
Alright, I'll fix that (but you can also go ahead and make a PR if you did that already).
