### ISSUE TITLE
Please make TagNames accessable

### ISSUE THREAD

**Issue by SOHODeveloper** [AngleSharp/AngleSharp#252]
It would be really nice to be able to use your TagNames class instead of having to use a string to access attributes etc.

Also, just a question, why is the class in in AngleSharp.Html namespace instead of the AngleSharp namespace.  The class spans all DOM types.

**Comment by FlorianRappl** [comment]
Because its only part of HTML and has nothing to do with, e.g., CSS. Its also not part of the DOM directly, however, of course indirectly. Yes, partially, it would certainly be beneficial to have it public, however, there are some things such as the `HashSet` instances, which should not be touched.

All in all, its on my road map (I actually want to make most of the classes accessible, but if its not needed for interaction I want to wait until they are stable).
