### ISSUE TITLE
Rendering?

### ISSUE THREAD

**Issue by axefrog** [AngleSharp/AngleSharp#26]
This is a fantastic project and I can definitely think of more than one place I'm interested in applying it in the not-too-distant future! What are your thoughts on the amount of work to take what you've done and render it to a surface? One application I can see for it is as the basis for user interface rendering for .Net-based games. Currently, to leverage the power of HTML and CSS for a game, you really need to embed something like Awesomium or CEF. Having a completely managed library available that can do all the work of rendering to an offscreen surface and being able to process a stream of input events (either simulated or otherwise) would be really powerful.

**Comment by FlorianRappl** [comment]
Thanks for the kind comment and your interest in the project. Yes, rendering is on my radar and I will start writing a simple renderer in the near future. First experiments tell me that it is possible and quite nicely working, however, I am not sure about the performance. Nevertheless, the original intention of the project was to provide another UI framework based on HTML and CSS with tight C# integration. That is still far away, and currently my main aim is to provide a really useful library that can easily be seen as a headless browser.

**Comment by h82258652** [comment]
You mean a browser core?! Even it is too hard, I hope it can come true. And then we can run it in any platform with .net framework.
How to render is a big problem, use local controls is a not good idea, SlimDX may be a good choice.

**Comment by Suchiman** [comment]
On my journey through the internet i've found this project: https://htmlrenderer.codeplex.com/
It's a little bit outdated on HTML and CSS support but it seems to be still developed and i wondered wether you could collaborate.

**Comment by FlorianRappl** [comment]
I think it was a year ago when I reached out to the maintainer of the project. He, however, refused due to time problems. Instead he improved his parser and then stopped maintaining the project actively. Nevertheless, the code definitely serves as a good starting point and I took one or the other idea from it. I actually have a (non-GH synced) branch that implements a renderer, which will be merged with v0.8 or shortly afterwards.

But definitely a good comment, since I like the HtmlRenderer project.

**Comment by jogibear9988** [comment]
seems the origian author gives maintenance away: http://theartofdev.com/html-renderer/
He also seems to have switched to github: https://github.com/ArthurHub/HTML-Renderer

**Comment by FlorianRappl** [comment]
Yep that is all true but please note that the links you are giving are not referring to the original author. Arthur Teplitzki was / is the current maintainer after taking the project over from Jose Manuel Menendez Poo. He started it all (and then Arthur did a great job in optimization and de-coupling).
But the project itself is incompatible with AngleSharp. It has its own (non-HTML5 non-CSS3) parsers and CSSOM included. Nevertheless it is a very nice project and certainly showcases some very good points about a possible HTML renderer implementation in .NET.

**Comment by ghost** [comment]
FlorianRappl I would like to work on a separate project from this that would be a truly pure C# browser core similar to rust/servo, I would love to open source it and include this as the parser, would you be interested in working together?

**Comment by FlorianRappl** [comment]
Yep, I would definitely be interested!

**Comment by ghost** [comment]
I've created a repo here: https://github.com/PorterX2Pro/Velocity 
We can discuss how we want to go about layout and rendering of the engine there.

**Comment by Suchiman** [comment]
@PorterX2Pro that might be just nitpicking but i wouldn't consider a library relying on OpenGL "pure" c#, it won't work without opengl hardware, drivers and support from opentk for the current platform.

**Comment by ghost** [comment]
@Suchiman, well servo considers itself pure rust however it relies on OpenGL itself... In my outline Im thinking we can create a wrapper that allows different rendering libraries to be used to create a cross platform system.

**Comment by Suchiman** [comment]
@PorterX2Pro yeah considering software and hardware rasterizer in early design might be a good choice

**Comment by ghost** [comment]
I've decided that AngleSharp->Layout->Layers->Paint->Paint_Bridge->WebView

**Comment by prepare** [comment]
Hello there!
please visit https://github.com/prepare/HtmlRenderer
I fork the project from https://github.com/ArthurHub/HTML-Renderer
I added some features.. such as
1. dynamic html dom (plan for scripting)
2. decoupling, dependency analysis
3. optimizing the html,css parser (but not Html5/Css3)
4. add svg/canvas support (not complete)
5. abstract canvas backend
   (GDI+, OpenGL) also not complete for Linux
   (for the canvas backend, I used it from 
    another project -> https://github.com/prepare/agg-sharp)

it is a C# project with permissive license( MIT,BSD, Apache2)
feel free to comment/ suggest

Nice to meet you!
WinterDev :)

**Comment by FlorianRappl** [comment]
Well, forking the HTML-Renderer is a good idea, however, it has to be decoupled from its CSS and HTML parser. They (the included parsers) are alright for conforming pages, but especially the CSS model is not sufficient for most webpages.

**Comment by FlorianRappl** [comment]
The status of this item has not changed. However, I won't be able to provide a rendering library for v0.9. Instead I'll aim to provide one on the way to v1.0.

**Comment by prepare** [comment]
Thank you for your star! on the HtmlRenderer :)

**Comment by FlorianRappl** [comment]
Of course - great that you take care of the HtmlRenderer project.

**Comment by galvesribeiro** [comment]
I would say... This is awesome @FlorianRappl! Great work!

So, we are trying to create a web engine for our embedded ARM device so the app developers can create the apps for it using modern HTML5/CSS/JS. We tried all the possible alternatives (Electron, Chromium, NW.js, CEF, you name it!) but they are either too overcomplicated or they just don't support ARM very well or it is not .Net friendly.

Our current framework for the device is based on .Net C# (we built Mono for the target and it work flawless) but our customers want Web!

We got to a point that we started to drawing a spec for a small browser that has its own Virtual DOM (like in React) and we started looking into several JS engines, etc. when we found you (I wish I did found it earlier!).

I saw this issue talking about a renderer... Did you had a progress in it? We was thinking on use Skia as our backend renderer library since it works with any framebuffer (our device has no HW accel or GL so we need draw to Linux framebuffer at /dev/fb) by just providing a pointer (`IntPtr` or `byte[]`) or any other HW accel libraly (like OpenGL) if available. Skia is REALLY FAST and Xamarin/Microsoft guys did a good job on its binding with [SkiaSharp](https://github.com/mono/SkiaSharp) so it can run on low-end devices like ours.

I would love if AngleSharp could be used on our project so that would save us A LOT of time implementing DOM.

Thanks! Keep the good work!

**Comment by FlorianRappl** [comment]
Hi @galvesribeiro - actually, yes I made some progress. But I still do not have concrete plans when to make it public. At the moment the schedule is roughly to (in order)
1. release AngleSharp v0.10.0 (separates CSS from the core, changes some of the namespaces and is quite close to being a valid v1, i.e., production ready and considered stable)
2. release AngleSharp.Css (shortly after / at the same time as the core v0.10.0)
3. update AngleSharp.Scripting.JavaScript to work even better / be more extensible
4. improve AngleSharp.Css to be fast, precise, and easy to work with / extend
5. release an initial version of AngleSharp.Rendering (currently designed to be tightly coupled to AngleSharp.Css)

Realistically, I would say that the initial version won't be published until ~March next year. I would love to lower that, but right now the project is low on manpower and prio.

**Comment by galvesribeiro** [comment]
@FlorianRappl thank you Florian, will keep an eye here

**Comment by galvesribeiro** [comment]
@FlorianRappl I had second thoughts here... 

How can we help make things faster?

Do you have a gitter chat or skype? I want to put man power in it.

**Comment by FlorianRappl** [comment]
Skype is possible as is Twitter (or even Gitter). You'll find all contact information you need on my [homepage](https://www.florian-rappl.de).

**Comment by FlorianRappl** [comment]
Continued in AngleSharp.Css!
