### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by 304NotModified** [AngleSharp/AngleSharp#270]
Are there any plans to support CoreCLR?

**Comment by FlorianRappl** [comment]
Yes there are. I will switch from the PCL to CoreCLR soon (.NET Core 5). At the moment it still seems that both would be required to be deployed separately*, however, once I see that going from a PCL to CoreCLR makes sense I will do that (hopefully soon).

*) without support in x-platform IDEs (especially Xamarin Studio) and previous versions of VS (especially VS 2013) the switch does not make sense.

**Comment by 304NotModified** [comment]
> once I see that going from a PCL to CoreCLR makes sense I will do that (hopefully soon).

Isn't the big benefit that it runs on Linux / Azure then?

**Comment by FlorianRappl** [comment]
It already runs on Linux / Azure. The benefit from CoreCLR is that the dependencies are specified in a fine-grained way making it much easier to specify a working system (the PCL approach defines targets that work with it, which is a bulky and less maintainable approach).

Since it allows you define the dependencies in rich detail it makes developing minimal products (rolled out with just a "core" functionality) easy. Currently, PCL 259 is used, which is already reduced, but far away from minimal.

I agree that CoreCLR has some benefits (never stated differently), but at the moment the lack of support is just something blocking a direct migration. I don't have the capacities to support two projects (the PCL and the CoreCLR version). Hopefully, we can switch soon, which should (ideally) also help getting rid of .NET 4 and the SL version.

**Comment by Suchiman** [comment]
CoreCLR support is already here since you support PCL Profile 259.
https://oren.codes/2015/07/29/targeting-net-core/ see `Existing Libraries` headline which also contains instructions to make the nuget package work with that.

If you want to switch to CoreCLR build, wait for ASP.NET Core RC2 which switches `DNX` against `dotnet` and allows you to target CLR and CoreCLR with one build directly using the new `NET Standard` system that supersedes PCL Profiles.

**Comment by FlorianRappl** [comment]
Sounds like a good plan. And yes, you are right about PCL 259 being compatible. I'll still need to duplicate AngleSharp in NuGet (raising the size of the NuGet package again) to be present in _\lib\dotnet_ as well. But I'll do that for v0.9.5 (I create a separate issue for that and leave this one open for switching to CoreCLR build).

**Comment by 304NotModified** [comment]
@Suchiman indeed good proposal :+1: 

Great to hear this is in the pipeline :)
