### ISSUE TITLE
SetCookies not working for more then 1 cookie

### ISSUE THREAD

**Issue by Franc2731** [AngleSharp/AngleSharp#274]
The separator for SetCookies is ',' non ';'

AngleSharp.git\trunk\AngleSharp\Network\Default\HttpRequester.cs

ln 137
-_cookies.SetCookies(_http.RequestUri, cookieHeader);
+_cookies.SetCookies(_http.RequestUri, cookieHeader.Replace(';',','));

see:
https://social.msdn.microsoft.com/Forums/en-US/0e777111-aae4-4224-8538-5c38b50d5ea7/there-is-a-bug-in-cookiecontainersetcookies-getcookieheader?forum=winappswithcsharp

**Comment by FlorianRappl** [comment]
This seems to be a bug in the cookie container (according to your source). I don't know if this bug has been fixed for some platforms (this may happen, one never knows). 

Also I have my doubts in this "fix". What if semicolons are used in values? This change would replace them (and potentially render the values invalid from the target's perspective).

If this is really the case, then the only thing we can do is to "rewrite" cookie container with the right behavior. Alternatively, one may parse the cookie resulting in the same string with the changed delimiters.

**Comment by Franc2731** [comment]
The Cookie class accept values with ';', but when you put that cookie into the CookieContainer it throws a CookieException: part Value of cookie is invalid.

es:
CookieContainer cc = new CookieContainer();
cc.Add(new Uri("htttp://123.com"),new Cookie("p1","sadsa;"));

**Comment by Code-Grump** [comment]
It's hard to nail down a specification for cookies, but [RFC6265](http://www.ietf.org/rfc/rfc6265.txt) is probably the best we have right now. In cookie values can have alpha-numerics and any of these `!#$%&'()*+-./:<=>?@[]^_`{|}~` characters. You can also have leading and ending quote characters which oddly become part of the value rather than just encoding, but you cannot have quote characters anywhere else in the value.

Semicolons aren't valid in cookie names or values.

I believe splitting on a character outside this set solves the problem acceptably, unless you want to support cookies which are outside the scope of the standard?

**Comment by FlorianRappl** [comment]
Fixed, see PR #338.
