### ISSUE TITLE
MemoryCookieService expires all previously set cookies when a new cookie is set

### ISSUE THREAD

**Issue by Code-Grump** [AngleSharp/AngleSharp#280]
As the title says, when `MemoryCookieService` sets a cookie, it expires all previously set cookies. This causes a problem when using cookies for login, then setting a different, unrelated cookie later causes the client to "forget" its login.

Looking at the service, it seems there's explicit code to expire cookies - not sure I understand why.

**Comment by FlorianRappl** [comment]
The reason was that you can't remove cookies in the `CookieContainer`. These cookies are removed by explicitly setting the expiration status.

This way only the currently transmitted cookie is set. I am not sure if this is the ideal behavior. I considered the case where a server wants to delete a cookie set in response _A_ and therefore does not transmit it in response _B_. After response _B_ the `CookieContainer` should be consistent with the server.

However, as #274 I am not really satisfied with the `CookieContainer` from .NET anyway. I guess cookies are an essential part of the web, hence it would make sense to provide something better in AngleSharp (as, e.g., with `Url`, which is better than `Uri`).

**Comment by FlorianRappl** [comment]
Anyone who wants to work on a good cookie container / cookie storage solution? Would be much appreciated and solve #274, #278 (and this one).

**Comment by Code-Grump** [comment]
If a server wants to "delete" a cookie, it can send a Set-Cookie header with an expiration in the past. It may also set the cookie to have no value. If you run through a logout scenario, this is what browsers typically do.

I created a simple implementation by removing the explicit cookie removal, which was sufficient to test my scenarios.

**Comment by FlorianRappl** [comment]
Fixed, see PR #337.
