### ISSUE TITLE
Make an implementation of IHtmlCollection public

### ISSUE THREAD

**Issue by brianfeucht** [AngleSharp/AngleSharp#293]
Is there any reason why all implementations of IHtmlCollection are private?

I'm trying to write unit tests using IHtmlDocument and several of the properties return IHtmlCollection.  Since all of implementations of IHtmlCollection are private, I'll end up needing to implement or mock the IHtmlCollection interface as well.  

I'd be happy to submit a PR to make those public, but I wanted to see if this was done intentionally before I do.

**Comment by FlorianRappl** [comment]
Yes, it is intentional. There have been two important reasons:
1. Do not confuse users that there are multiple implementations (why are there multiple? what's there purpose? do I need to cast to a specific one?).
2. Make it impossible to depend on these implementations, which may or even will change.

I understand your need, but coming up with a basic `IHtmlCollection` that is suitable for tests is certainly not much work.

Maybe its possible to meet in the middle, e.g., open the most standard / default implementation (which is just a plain wrapper around an `IEnumerable<T>`, where `T` implements `IElement`).

**Comment by Code-Grump** [comment]
Would it be possible to provide a factory to return instances of `IHtmlCollection`? I'm thinking along the lines of something in the manner that an `XmlReader` is composed using the `Create` method and a specification of the features needed so the factory method can choose the appropriate implementation for the caller's needs without ever exposing the types publicly.

**Comment by FlorianRappl** [comment]
Added the `ToCollection` extension method. There are actually just three collections namely
- `HtmlAllCollection`, which is just a wrapper around the ordinary `HtmlCollection` to fulfill the DOM specification -- it is only used by the `IDocument` and implicitly includes all children (recursively). _no need to make this available_
- `HtmlFormControlsCollection`, which is a specialized wrapper around the `HtmlCollection` - specialized for form controls and with additional (form control specific) properties. _only useful with forms, where it can already be found_
- `HtmlCollection<T>`\* - basically just wrapping an `IEnumerable<T>`, where `T : IElement`. _this is now available via an extension method_

So no explicit factory was required. Instead, a LINQ-style extension method `ToCollection` was introduced.

**Comment by FlorianRappl** [comment]
Implemented, see PR #373.
