### ISSUE TITLE
DefaultRequester - 'HttpWebResponse' memory leak

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp#31]
Hi
There is a 'HttpWebResponse' memory leak, as this not disposed. I think you are holding onto to 'Content" stream.  The current implementation does not scale beyond few external link requests to, say, style sheets.

I modified thus:

<pre>

             DefaultResponse GetResponse()
            {
                if (_response == null)
                    return null;

                var result = new DefaultResponse();
                var headers = _response.Headers.AllKeys.Select(m =&gt; new { Key = m, Value = _response.Headers[m] });
                result.Content = new System.IO.MemoryStream(); 
                _response.GetResponseStream().CopyTo(result.Content);
                result.Content.Position = 0;
                result.StatusCode = _response.StatusCode;
                result.Address = new Url(_response.ResponseUri);

                foreach (var header in headers)
                    result.Headers.Add(header.Key, header.Value);

                _response.Dispose();
                _response = null;
                return result;
            }</pre>

**Comment by FlorianRappl** [comment]
Copy from my answer at CodeProject:

Yeah I see. Thanks for the hint, however, while the issue is correct, the proposed fix is unfortunately not desired. The reason is simple: The response stream is not accessed asynchronously in this scenario, and the resulting stream is already in memory. Therefore the whole concept of async parsing, when parsing is done while the page is still being downloaded, is not working. I think a better fix would be to make the <code>DefaultResponse</code> disposable and to dispose the response once parsing is finished.

I will investigate this more closely and come up with a proper solution. Thanks again for noticing!

**Comment by mediabuff** [comment]
Thank you. Overall it’s a great piece of work. If you please don’t mind, I’ll report issues as I am beginning to use the lib heavily.

Agreed, the fix is not optimal. I wanted a quick fix, so that I could move with rest of my stuff 😊 This could lead to large memory footprint.

Yes, the overall async model may need a review and reimplementation. Right now, we have islands of async not connected. Thus if you are a caller waiting for a document to load completely - along with say all external style sheets, there is no mechanism to “await”.

Some suggestions, you may want to move your design to task-based rather than event-based. Esp. DefaultRequester/RequestAsync and HTMLLinkElement/TargetChanged.

Because of this I had to make ‘TargetChanged’ synchronous. Thus added:

```
_current =request.LoadAsync …..
```

   _current.Wait()

This will make the top-level call deterministic (from DocumentBuilder ..), when the caller to needs to have all assets loaded.

This fix is also a temporary hack. Thanks for the help.

Sent from Windows Mail

From: Florian Rappl
Sent: ‎Sunday‎, ‎November‎ ‎9‎, ‎2014 ‎3‎:‎32‎ ‎AM
To: FlorianRappl/AngleSharp
Cc: Sekkappa Nagappan

Copy from my answer at CodeProject:

Yeah I see. Thanks for the hint, however, while the issue is correct, the proposed fix is unfortunately not desired. The reason is simple: The response stream is not accessed asynchronously in this scenario, and the resulting stream is already in memory. Therefore the whole concept of async parsing, when parsing is done while the page is still being downloaded, is not working. I think a better fix would be to make the DefaultResponse disposable and to dispose the response once parsing is finished.

I will investigate this more closely and come up with a proper solution. Thanks again for noticing!

**Comment by FlorianRappl** [comment]
Yeah I agree - some of this needs to be investigated. The issue with CSS is also on my mind for a while, especially since the default behavior in browsers is to wait for stylesheet downloads. Right now this is done asynchronously. Of course one wants this, e.g. in scripts, however, not when the parsing just started. So I'll have to come up with a solution. Another problem is the propagation of a CancellationToken. I guess there needs to be a (document) global way of doing a cancel. Maybe there have to be different ways, e.g. cancel all downloads, cancel all scripts, ... - up to cancel everything.

Yes, please keep reporting issues, I'll try to come up with solutions asap. Much appreciated!

**Comment by mediabuff** [comment]
I cannot believe it, your superfast response !!  thank you. This is absolutely great. Let me pull in these changes and take it for a ride.

Meanwhile, I have found other issues and areas that could be improved. When I get little bit more time, I'll "issue them out"

**Comment by FlorianRappl** [comment]
Thanks, that would be helpful. BTW: Do you have any reference case where I can see memory leaks (e.g. a proper document that contains a lot of stylesheet references etc. -- where the stylesheets are quite heavy weight). It would be good to have some kind of unit test. I guess such a unit test must use the HTTP requester, as this is the source of the problem. I already have a testpage online, that can be used for some test scenarios (e.g. testing form submit etc.). I could extend that one.
