### ISSUE TITLE
Where is the parsed html doc Uri exposed ?

### ISSUE THREAD

**Issue by Veverke** [AngleSharp/AngleSharp#319]
I have just posted the following question on SO: http://stackoverflow.com/q/36568892/1219280

Am copying it here:

Where AngleSharp exposes the parsed document's Uri ?

Consider the following snippet:

```
    HttpClient httpClient = new HttpClient();
    string htmlString = httpClient.GetStringAsync("http://www.stackoverflow.com").Result;

    HtmlParser htmlParser = new HtmlParser();
    var parsedHtml = htmlParser.Parse(htmlString);

    Console.WriteLine(parsedHtml.Url);
    Console.WriteLine(parsedHtml.DocumentUri);
```

it will print about:blank twice. The document is parsed, I can access properties such as Title, but I can't find a reference to its uri.

**Comment by dv00d00** [comment]
Faced same issue, is there a way to set base uri manually without touching BrowsingContext ?

**Comment by Veverke** [comment]
Just note that my question simply points out that a publicly exposed property is not available

**Comment by FlorianRappl** [comment]
Well, the use-case you are showing is actually covered by using a `BrowsingContext`. I don't know if v0.9.5 already exposes the `VirtualResponse` directly (I guess it does), but this is the way to do it.

The thing is that using an URL requires some steps that _shouldn't_ be done by the user (the user will usually do them wrong, also there are too many implementation details). It is much better to leave that work to, e.g., the `BrowsingContext`. There is a reason why it exists and there is a reason why it is nearly exclusively used in the examples.

Long answer short. If you want to load websites then use the `BrowsingContext`. If you want to parse HTML source code then use the `HtmlParser` directly.

**Comment by Veverke** [comment]
Isn't it something undesirable however - that the framework allows you to instantiate a parser - and when you do so - you make properties such as Uri and DocumentUri meaningless ?

**Comment by FlorianRappl** [comment]
Yes, which is why you can use the `BrowsingContext` to set them. The thing is... this is a read-only property. If you could change them at any time then you would most probably end up in an invalid state. Hence you need to supply them beforehand.

You just pass in a string. If I do that with the browser then it also does not know what URL to use. By W3C the initial URL is `about:blank`. This could be changed to some (more or less) random internal URL, but in this case it is not.

I advise you to use `BrowsingContext`, which gives you several advantages. I usually advise against using the `HtmlParser` directly as most use-cases are much better off by using a `BrowsingContext` instance.

`Uri` and `DocumentUri` are used as specified by the W3C - they are not meaningless. They are exactly used as intended.

**Comment by Veverke** [comment]
I would like to note that I on purpose have been using HtmlParser instead of BrowsingContext - because I want to have control over the http response status codes at each async request - hence I use my own GetAsync infra. Thanks for the explanations.

**Comment by FlorianRappl** [comment]
The browsing context offers a virtual response, where you can everything, from received headers (including status code) to the URL. You can use it with a string or stream as source.

Its the overload that accepts a callback, e.g.,

``` cs
// context is the current IBrowsingContext
context.OpenAsync(res => res.Content("<!doctype ...").Address("http://localhost").Status(201));
```

Hope this helps!

**Comment by Veverke** [comment]
Hmm... then I should have a look at it and... review my whole solution :-)
Thank you.
