### ISSUE TITLE
Problem with IUrlUtilities.Href

### ISSUE THREAD

**Issue by lvv83** [AngleSharp/AngleSharp#320]
Hello!

I have a simple console application project with AngleSharp.0.9.5 installed from nuget.

``` csharp
var html = 
@"<!DOCTYPE html>
<html lang='en' xmlns='http://www.w3.org/1999/xhtml'>
<head>
    <meta charset='utf-8' />
    <title>Test page</title>
</head>
<body>
    <ul>
        <li><a href='page01.htm'>Page 1 (same path)</a></li>
        <li><a href='/page02.htm'>Page 2 (domain root)</a></li>
        <li><a href='../page03.htm'>Page 3 (parent)</a></li>
    </ul>
</body>
</html>";

var parser = new HtmlParser();
var document = parser.Parse(html);

var anchors = document.QuerySelectorAll("a").OfType<IHtmlAnchorElement>();
foreach (var a in anchors)
{
    Console.WriteLine(a.Text);
    Console.WriteLine("Href = " + a.Href);
    Console.WriteLine("PathName = " + a.PathName);
    Console.WriteLine();
}
```

Look at console output. I think that value of Href property must be equal to href attribute value, but we have something strange - **about:///page03.htm** Why **about://** ?

I want use `UriBuilder` class, but I can't understand which url I should pass to constructor, cause I don't see any difference between paths and have no access to the raw href attribute value.

Thanks!

**Comment by FlorianRappl** [comment]
The problem in understanding is that `Href` is a computed property (see browsers). It actually transforms the `href` attribute to an _absolute_ URL. The URL is absolute to the page's base URL.

As you used the `HttpParser` directly (I would nearly _always_ prefer the \* BrowsingContext*, see #319) you couldn't specify the document URL, which is why it remained at `about:blank`, resulting in that strange URL you see.

So either access the `href` attribute (`GetAttribute("href")`) or use it with the right base URL. It depends on your use-case / desires.

**Comment by lvv83** [comment]
Thanks.

`GetAttribute("href")` solved my problem.
