### ISSUE TITLE
Change code to C# 6

### ISSUE THREAD

**Issue by FlorianRappl** [AngleSharp/AngleSharp#334]
Currently, the code uses C# 5 to work on any platform with most compilers. However, I think it is now time to move on and continue with C# 6. First, the move towards CoreCLR focuses on a more modern stack anyway (also requiring tools that know C# 6 anyway), second C# 6 compilers should now be available for every platform.

The features that will be used the most are certainly the conditional access operator ("Elvis" `?.`) and the `nameof` operator. Also `using static` may be handy in one or the other class.

This is merely an information such that developing AngleSharp could potentially require a toolset / compiler update soon. Anticipated for v0.9.8.

**Comment by aloisdg** [comment]
With C# 6, you can also replace all your `String.Format()` thanks to interpolation string. For example:

``` C#
public override String ToString()
{
        return String.Format("({0}) -- ({1})", _start, _end);
}
```

Will become:

``` C#
public override String ToString()
{
        return $"({_start}) -- ({_end})";
}
```

It is very handy!

[snippet](https://github.com/AngleSharp/AngleSharp/blob/dc85fd5f6329647b2a3577c57de90f5ff68f23a4/src/AngleSharp/TextRange.cs#L62)

**Comment by FlorianRappl** [comment]
Yep!

**Comment by qaqz111** [comment]
With C# 6, you can also replace all your `1-line methods` thanks to lambda expression body syntax. For example:

``` C#
public override String ToString()
{
    return $"({_start}) -- ({_end})";
}
```

Will become:

``` C#
public override String ToString() => $"({_start}) -- ({_end})";
```

It is very handy!

:laughing: :laughing: :laughing:

**Comment by FlorianRappl** [comment]
The expression body syntax is not really useful for methods (its adding a layer of inconsistency that brings more noise to the code than order).

However, the expression body syntax is most useful for computed properties, which should be one-liners by nature.

**Comment by qaqz111** [comment]
What does `a layer of inconsistency that brings more noise to the code than order` exactly mean?

I've peeked into IL disassemble of the 2 different syntax, there's not significant differences between them, and usually the expression body make a shorter IL code segment.

**Comment by qaqz111** [comment]
Oh I see, you just mean what they looks are, relative to those multiple lines methods that included in curly braces. 

Hmmmmmm, I think, this is just a personal habits?
I'd like to write the short 1-line methods in expression form, so that I can see what the method does without expand the `[+]` in VS editor.

So, whether use it or not is not very important! :smile:

**Comment by FlorianRappl** [comment]
Yes, I mean from the code's perspective - the generated code is definitely the same.

Consistency is important. You'll read code more often than you write it. It is the reason why style guides exist and why one needs to fix a single style for a project.

Of course its a personal opinion (as everything regarding code styles is). But fixing one style (no matter which one) is definitely a good thing and as most methods are beyond one-liners the expression body syntax does not make sense to be applied here.

Just using a feature because its there is definitely not very useful. You need to use a feature when it makes sense!

Independent of the discussion above, the syntax is (as I said) definitely used for computed properties. Thanks for the suggestion!

**Comment by qaqz111** [comment]
Yes of course a fixing style is definitely necessary, the only reason I use expression body method is that I can quickly understand what this method do.

To me, this feature does make sense, because I'd like to `Ctrl+M,M` when I open a source file at once, this is definitely a personal opinion at all :laughing:

And, in fact I'm not suggeting using expression body but just a **KEEPING THE FORMATION** from _[aloisdg's comment](https://github.com/AngleSharp/AngleSharp/issues/334#issuecomment-225454328)_ as you see :laughing: :laughing: :laughing: 

Anyway, I'm in support of your work! :+1:

**Comment by FlorianRappl** [comment]
Agreed :sunglasses: and thanks for the :+1:!
