### ISSUE TITLE
Get InnerText of items (like in HTML Agility)

### ISSUE THREAD

**Issue by Zeokat** [AngleSharp/AngleSharp#345]
Not sure about if im writing in the right place but... im trying to port a project from HTML Agility to AngleSharp and i can't find a way to get InnerText of items.

In Anglesharp i can see that exists **TextContent** but this gets also the text of all descendats _(and i dont need descendants)_.

I readed full documentation but couldn't find a solution by myself, maybe someone can point me to the right direction.

Thanks in advance and sorry for my bad english.

**Comment by FlorianRappl** [comment]
Why wouldn't you want to get also the text from the descendants? Usually, the text contained in child elements is not disconnected from the text in the selected element. Anyway, I don't think there is currently a build-in solution, but you could just do the following:

``` cs
var element = /* some element */;
var textOfElement = element.ChildNodes.OfType<IText>().Select(m => m.Text).FirstOrDefault();
```

Essentially, this will only give you the text assigned to the element, excluding text nodes from the children. You could make an extension method like

``` cs
public static String GetExclusiveText(this INode node)
{
    return node.ChildNodes.OfType<IText>().Select(m => m.Text).FirstOrDefault()
}
```

Hope this helps!

**Comment by Zeokat** [comment]
Thanks for the answer @FlorianRappl , get only the text of a single element is a common task in my opinion. I had to code a few scrappers/apps and some of them require this.

For example, in this project i need to select text of a single element because im doing a classification with scores and finally build a heat map. To analize each element one by one i need to get Innertext. 

I'm sure that you used and analized more parsing libraries than me, but the next libraries allow get InnerText of items (so maybe is demamnded): HTML Agility Pack and .net control webbrowser.

Anyway, thanks again for the answer :+1:

**Comment by FlorianRappl** [comment]
I can only think of examples, e.g.,

``` html
<li>You should <strong>know</strong> the answer</li>
```

Why would you want to only get "You should " as text? Does not make much sense to me. Also I am unsure how the libraries you mentioned behave in edge cases. For instance in the given one I can also concatenate all the top-level strings to receive "You should  the answer". I could also just take the last string (" the answer"). Taking all the strings is exactly how browsers do it (see AngleSharp's goals) and is not ambiguous.

If it wouldn't be ambiguous in the first place I would include such a helper (extension) method, but since its trivial to code for specifically coupled to one's requirements I won't include it.

BTW: The property you mention (`InnerText`) is not what you asked for and what I gave you in form of the LINQ expression. HAP's `InnerText` behaves very similar to AngleSharp's `TextContent`. It will also get the text of the descendants.

**Comment by Zeokat** [comment]
Yeah, you are completely right. After some new tests the problem is on my code logic.

Thanks for the answers, i could fix the stuff finaly :+1:

**Comment by FlorianRappl** [comment]
Perfect! Glad this helped you :+1:.
