### ISSUE TITLE
Support for Useragent default styles - style inheritance

### ISSUE THREAD

**Issue by mediabuff** [AngleSharp/AngleSharp#36]
I am trying to compare the computed styles from Chrome and IE with AngleSharp. Running into the above issue.

**Comment by FlorianRappl** [comment]
Yeah currently there is no default stylesheet. I am not sure if I want to supply one directly, however, at least the possibility of specifying a list of default sheets (one to many) should be given.

For a default sheet I have the following candidates:
- [Firefox](http://hg.mozilla.org/mozilla-central/file/tip/layout/style/html.css)
- [Webkit](http://trac.webkit.org/browser/trunk/Source/WebCore/css/html.css)
- [W3C CSS 2.1 (HTML4)](http://www.w3.org/TR/CSS21/sample.html)

I would prefer the last one, since it supplies everything one needs. It is also pretty lightweight. All in all a good starting point. In the end such default stylesheets shouldn't be too exotic.

**Comment by FlorianRappl** [comment]
I added a property to the engine interface. Every registered style engine may include a default sheet. The sheet (if available) will be used for style computation (not implemented yet). Since computed style is a CSS kind of thing, only CSS engines will be considered for the default sheet.
