### ISSUE TITLE
How to select elements by custom HTML5 data attribute?

### ISSUE THREAD

**Issue by IHNEL** [AngleSharp/AngleSharp#360]
Hi,
I try to parse some famous pages such as google.com, facebook.com and see that they use custom HTML data attribute. For eg, `data-sigil='some_thing'`. My question is: How can I select these elements by this custom attribute.

**Comment by FlorianRappl** [comment]
You can select them like with any other attribute, e.g.,

``` cs
// assuming document relates the `IDocument` instance
var elements = document.QuerySelectorAll("*[data-sigil='some_thing']");
```

Hope this helps!

**Comment by IHNEL** [comment]
I tried it before posted question here but it didn't work. I did debug and see that these attributes do not exist, although they do on web-browser. ( I debug with facebook.com)

Do you try it before close the issue?
Btw, I tried with the AngleSharp sample app, and It can't help to query these attributes.

**Comment by FlorianRappl** [comment]
If they don't exist then they could have been added by a script. AngleSharp itself does not come with a scripting engine.

If you think this is a bug then please come up with an MWE. Don't use a website, make a short HTML code and try it out to be sure. Note the expected behavior and the actual behavior. Also be sure to understand the HTML specification (i.e., try your sample in a webbrowser before you submit the bug).

A webpage my do several things (give you HTML due to the user-agent or some other browser-dependent header; use JavaScript; ...) that AngleSharp (by default) doesn't. Make sure you are comparing the right thing.
