### ISSUE TITLE
How to get full HTML and have HTML entities not escaped?

### ISSUE THREAD

**Issue by UweKeim** [AngleSharp/AngleSharp#361]
Using `HtmlParser`, I'm changing some nodes. E.g. I'm inserting something like `&mdash;` and other entities.

When accessing the `InnerHtml` property, the (e.g.) `&mdash;` is returned as `&amp;mdash;`. This is wrong in my scenario.

In contrast, the `TextContent` returns `&mdash;` correctly but omits all contained HTML tags.

**My question:**

Is there a way to get the full content of the `HtmlParser` without HTML entities being "destroyed"?

**Comment by FlorianRappl** [comment]
I am not quite sure if I understand everything correctly.

Let's start with the basics: The `&mdash;` entity is a legal HTML5 entity and available in AngleSharp. So if you have an HTML source that contains `&mdash;` it should be output as a long dash (`—`).

If you set anything in `InnerHtml` it will be parsed by the HTML parser. If you get anything from `InnerHtml` the corresponding DOM will be serialized (using the default serializer, i.e., `HtmlMarkupFormatter`. Here you should see the long dash.

If you set anything in `TextContent` it will be taken literally. If you get anything from `TextContent` it will only look at the `TextNode` children of the DOM. These will be concatenated.

So from your question I assume you set `&mdash;` in `TextContent` (i.e., taking it _literally_) and get the text via `InnerHtml` which transforms the literal `&` to its entity (`&amp;`) leaving the rest as it is.

Am I on the right track so far?

If so: Entities are always "resolved" (I guess this is what you mean by destroyed). They come from an entity service (which can be provided by you, however, a default implementation is initially provided). For HTML5 you can use the `HtmlEntityService`. Now it all depends on your scenario. In the (default) serialization (which follows the specification) only a couple of characters are transformed to entities (like the `&` is transformed to `&amp;`). You can now either provide your own serializer (potentially using the existing one, however, just outputting text differently with a greater entity resolution) or you could inject your own entity resolution, which would prevent the entity resolution and return the identity (enabling you to output the original in such scenarios).

I don't know your specific use-case, which is why I can't recommend which one (or which variation) to pick.

Hope this helps!

**Comment by UweKeim** [comment]
I'm modifying a string via the `NodeValue` member of the `INode` interface while iterating nodes and trying to replace text. (In the debugger, `INode` is shown as actually being `TextNode`).

So I want to insert something like e.g. `&mdash;` during node iteration and after iteration I want to read a full string of all the nodes and still have the `&mdash;` in-place.

(My full use-case is that I'm writing a simplified C# version of the [`texturize` WordPress function](https://developer.wordpress.org/reference/functions/wptexturize))

Probably my fault is that my initial iteration is the wrong way of trying to replace texts?!?

``` cs
var parser = new HtmlParser();
var document = parser.Parse(html);
var it = document.CreateNodeIterator(document);

INode node;

while ((node = it.Next()) != null)
{
     var before = node.NodeValue; 
     if (!string.IsNullOrEmpty(before))
     {
        var after = processOneNode(before); // ← Replacement is done here

        if (after != before) node.NodeValue = after;
    }
}

return document.DocumentElement.GetElementsByTagName(@"body").First().InnerHtml;
```

**Comment by FlorianRappl** [comment]
Thanks for giving me some context. Yes, from the snippet it seems that this is indeed the problem. The `NodeValue` is quite a generic property, which maps to nothing except for `CharacterData` nodes (e.g., comments or text nodes) and entities (which are not used in HTML as they are resolved directly; this is an historic type of node that is a left-over from XML). Hence you already set the literal text (same as setting `TextContent`).

Either you use the previously mentioned `HtmlEntityService` to do the conversion yourself, or you leave it up to a parser by parsing a fragment of the snippet you want to insert.

**Comment by UweKeim** [comment]
Danke, Florian 😃 

I've now solved it by using `WebUtility.HtmlDecode()` before passing my string to `NodeValue`.

E.g. in my above snippet, instead of:

```
...
node.Value = after;
...
```

I write:

```
...
node.Value = WebUtility.HtmlDecode(after);
...
```

This seems to work in my scenario (hopefully no side-effects).

Thanks again for you detailed, fast help. Always a pleasure working with your libraries and you! 👍

**Comment by FlorianRappl** [comment]
Thanks Uwe! I'm glad you found a workaround / solution for your problem. Always at your service!
