### ISSUE TITLE
Will there be support for .NET Core?

### ISSUE THREAD

**Issue by ghost** [AngleSharp/AngleSharp#362]
Seeing as it's a major, official release which introduces full-on open-source, as well as compatibility with many operating systems, it seems pretty logical that AngleSharp should eventually go on to support this. The question however is when?

**Comment by FlorianRappl** [comment]
It's already supported (see #270, #271, #283, #346). The thing that's missing is support for the release last Monday (AngleSharp has not been updated since Monday).

If you want to adjust the dependencies in the nuspec / project to the RTM then feel free to do so. Any PR on this is always much appreciated!

**Comment by FlorianRappl** [comment]
Done and ready to be in the next release, see PR #363.
