### ISSUE TITLE
Cookie lost on page redirect and other Cookie problems?

### ISSUE THREAD

**Issue by gkurt** [AngleSharp/AngleSharp#368]
Firstly, I thank you for this good project and appreciate the amount of time you put into it.
I don't know if this bug is caused by .Net or AngleSharp. The problem is when the request contains "Location" header and the request is redirected, cookies sent in the first request will not be sent to the redirected address. This causes my session to drop. There are many people reporting this for .Net's HttpWebRequest which AngleSharp uses. Is it possible to write a custom solution for redirects like in [Here](http://www.codeproject.com/Articles/49243/Handling-Cookies-with-Redirects-and-HttpWebRequest)
Another possible solution would be to use HttpClient and HttpClientHandler.

In my case I could work it around with storing cookie before making the request then setting it to document again and doing the request to the redirected page.

Another problem with the cookies is that it doesn't seem to match the Javascript implementation.In Javascript when you call "document.cookie='a=5'" it will add the key 'a' with the value '5' to cookies and old cookies will still be ther. But in AngleSharp doing so replaces all the cookies. I think this also causes a problem where only one cookie exists in the document but I am not sure. 

Note: I am talking about devel branch.

**Comment by FlorianRappl** [comment]
Hi @SirKurt, thanks for taking the time to report the issue. Your contribution is much welcome :+1:!

I think there are multiple things in this issue and I will try to separate them.

The first thing is about the HTTP requester. Of course, feel free to provide your own or integrate the existing AngleSharp.Io extension (find in on NuGet) to use in an implementation of `IRequester` using `HttpClient`.

AngleSharp could potentially intercept the redirects and place the right cookie container directly, however, I've decided the 3xx messages should still be handled by the HTTP requester. Maybe one could investigate how deep the problem is and if one could provide a solution within AngleSharp. Such an investigation / solution would be highly appreciated!

The second part deals with the inconsistency of assigning values to the `Cookie` value. This is indeed a problem and was not designed to be inconsistent intentionally. Actually, I usually tried to be precise, however, for the specific property I potentially relied to much on my gut feeling.

I will assign the tags "question" and "help wanted" regarding the first part and "enhancement" (I was also thinking about "bug", but I think an enhancement reflects the issue more accurately) regarding the second.

**Comment by gkurt** [comment]
I didn't know that I could change even the requester. I wasn't also aware of _AngleSharp.Io_.

Anyways `HttpClient` also has the same problem. The problem with 3xx status codes is that when redirecting, all header information is lost. Browsers does send same headers when redirecting. I tested this on _Chrome_ but it should be same for all browsers for the following reason:

It is common practice for some frameworks to use the redirecting in session logic. For example, you fill a form in an _ASP.NET_ site and post it, server processes the request and redirects you to another page. If you don't have the session cookies when this redirect occurs, you get redirected to the form page and start again. So for also practical reasons, it would be appropriate for redirected requests to include same headers as the original request.

I wrote a working `IRequester`based on [this gist](https://gist.github.com/joelverhagen/3be85bc0d5733756befa) with some changes (The author didn't include a license. Should I ask them if I could use it?).  

I also wrote a new `ICookieService`with the mentioned consistent behaviour.

I would like to contribute them. Would you prefer it in the _AngleSharp.Io_ or would you prefer modifying the default classes.

**Comment by FlorianRappl** [comment]
@joelverhagen is also the main author of AngleSharp.Io - so if you find this useful (and indeed it seems to be), you could ask him if you (or he) could add the presented logic to AngleSharp.Io.

I think AngleSharp.Io would be the best place for these changes. Also in the long run AngleSharp.Io will contain the sophisticated cookie management (with the possibility to also use persistent cookies, stored, e.g., on HDD).

Thanks for your contributions and work @SirKurt - much appreciated :+1:!

**Comment by FlorianRappl** [comment]
For a more detailed description see #385.

**Comment by FlorianRappl** [comment]
See PR #392.
