### ISSUE TITLE
Parsing third party (unknown) css properties

### ISSUE THREAD

**Issue by corliss** [AngleSharp/AngleSharp#37]
Can the css parser parse unknown properties and return them as simple string values to be handled by calling code? From my (very limited) look into AngleSharp, it seems that properties with unknown names are being discarded.

Alternatively, is it possible to pass in a handler for properties that AngleSharp does not know? The idea is the handler parses and instantiates the correct CssProperty subtype for properties it cares about.

**Comment by FlorianRappl** [comment]
Good idea. Yeah previously I had some `CSSUnknownProperty`, which stored basically the string it encountered. However, the W3C stated that such declarations are discarded.

Right now the CSS parser lacks the rich error reporting model that the HTML5 parser has. The reason is simple: The W3C defined all those errors for HTML, but not for CSS. However, it could be important (or interesting) to be notified about these errors.

For unknown properties the handler you described could be a nice way out. Maybe there is even an easier way: Giving users the possibility to add (or remove) properties to (from) the factory that constructs these properties. That way users could easily add custom properties, that might be picked up by AngleSharp.

There is just one problem: The implementation (`CSSProperty`) is currently internal. This is, however, used for all internal processing (the factory itself has `Func<..., CSSProperty>` instances). If users can provide their own properties, these properties need to derive from `CSSProperty`. I think I already know a way around, this issue I just have to see if it is appropriate. 

The question now is: What do you prefer? Having to setup a handler for such kind of issues (and being able to possibly handle everything), or having to include a way to construct a specific property?

**Comment by corliss** [comment]
Thinking about this a bit:
1) An important requirement for round tripping a css document (deserialization + serialization) is that nothing must be lost. Therefore it looks like regardless of whether a handler is allowed, there needs to be a placeholder for unknown properties (i.e. `CSSUnknownProperty`.)
2) A handler is useful in addition to the above because it allows properties to be evaluated at parse time, which is cleaner than adjusting them after the fact, which would mean removing a `CSSUnknownProperty` from the stylesheet DOM and replacing it with a more precise object.

So it looks like the first is necessary, the second is very nice to have (but only in addition to the first, not instead of.)

p.s. is there any other data which is being silently dropped? We have an important requirement of being able to round trip documents. (Maybe I will open a separate issue about round tripping.)

**Comment by FlorianRappl** [comment]
See #38 - round-tripping is a.) no requirement and b.) not defined by W3C. But I know what you are after and I am searching for a solution that
- does not violate official (W3C) rules
- gives you the required information (such as position in the original source, original span etc.)

And yes: Rules can also be silently dropped if they are unknown.

**Comment by corliss** [comment]
Do you happen to have the old `CSSUnknownProperty` code around? If not, I can try to make this change and send a pull request. But it will take some time to get familiar with the code base.

**Comment by FlorianRappl** [comment]
As mentioned in the other thread I guess I will bring it back. It will be marked invalid and thus being excluded from standard serialization. But it will be available. I am currently rewriting the whole value model anyway, since the old one is not much fun to work with and results in bloated value checking algorithms. The new one is much easier to maintain and read. Both should be available here tonight.

**Comment by corliss** [comment]
BTW I hope these issues are being taken in the right spirit. I think AngleSharp has great potential. It has been written with high code quality and is very well tested, so congratulations on what you have already achieved :)

**Comment by FlorianRappl** [comment]
Thanks! I think this discussion is actually very valuable. I am also not really happy with the authoring abilities. Even though it was not my original intention, I have some projects, where I would need more information on e.g. placement of the object in the original document. In my case the scenario appeared in HTML, but it is basically the same in CSS. Therefore I search for a good (practically no loss in performance, not confusing, no / not much memory increase) way to connect the OM with the original source.

**Comment by corliss** [comment]
Thanks - that's very helpful.

The other issue we discussed - #38 - is needed for my project so I'll wait till we make some progress on that. My project relies on knowing what changed in the CSS so that undo and redo work. It effectively functions as a css editor through user actions in a WYSIWYG UI but without displaying the raw css.

Have you been able to think further about that?

Cheers

**Comment by FlorianRappl** [comment]
Yes, I'll implement it as I proposed I guess. There will be another option besides simply generating a CSSOM, which will give you a tokenized version of the document. There you'll get everything you need to make connections to a CSSOM, get type information etc. 
The only thing that is remaining is the question if this option will make it to v0.8. There are a couple of other things with slightly higher priority that are must-haves for v0.8. Let's see what I can do in the next few days. But its definitely on the list and it will be integrated in the next couple of weeks.
