### ISSUE TITLE
Line Number

### ISSUE THREAD

**Issue by wcypierre** [AngleSharp/AngleSharp#374]
Is there a way to get the line number of the matched html tags?

**Comment by FlorianRappl** [comment]
If "matched html tags" refer to "HTML elements in the DOM" then I think the answer is no. However, once it was proposed for a DOM upgrade. Potentially, it can still be included (I can't make it in v0.9.8 though).

Questions that have to be answered then:
- What about dynamically added elements?
- Should it be just a position (start) or range (start to end)
- What about attributes? Should their position be supplied (somehow) as well

All in all this is also a performance question. Storing, e.g., 12 bytes (index, row, column) per element adds up to 12N more bytes. Since some DOMs have O(10^4) elements it would be quite heavy. On average I think we deal with O(10^2) elements and thus this means around 1kB more memory consumption per page (on average).

**Comment by wcypierre** [comment]
Yes. I am referring to that. I'll explain a bit of my use case to get us on the same line. I'm developing a program to refactor inline css from the source code. Regarding your question:
- What about dynamically added elements?
  For my use case I do not dynamically add elements, I do only the refactoring part (which most likely will stay on the same line in most cases)
- Should it be just a position (start) or range (start to end)
  I would need only the position, the purpose is just to aid the reviewer into being able to look at which line is the inline css at (I'll programmatically call VS with the filename, and line number so it will open that file on that particular line) before doing the refactoring. 
- What about attributes? Should their position be supplied (somehow) as well
  I do not need the position of the attributes, reason is the same as the above (it is good enough for the reviewer to be able to see which line is it at). 

Performance wise it is doesn't affect my use case much because it will only be loaded once most of the time. Although I do get your concern about the memory, and performance issue. 

Anyway, this is more of a question more than a feature request, if it is not feasible technically then I'll just fallback to HtmlAgilityPack in some parts of the code.

**Comment by FlorianRappl** [comment]
The questions have been of general nature and not tied to your use case (sorry for the confusion). If something like this (which was proposed earlier and which I wanted to have for a longer time) should be introduced the full scope has to be understood, i.e., applying the MoSCoW principle to know the feature and its boundaries.

**Comment by wcypierre** [comment]
then I guess that I'll look back into this when its done then.
