### ISSUE TITLE
Stack OverFlow Exception

### ISSUE THREAD

**Issue by efij** [AngleSharp/AngleSharp#381]
when visiting this url:
http://www.europarl.europa.eu/sides/getDoc.do?type=COMPARL&reference=PE-583.901&format=PDF&language=EN&secondRef=01

the code doesn't handle mimetype == application/pdf 
please your urgent advice/fix

**Comment by FlorianRappl** [comment]
Version? OS / .NET Framework?

**Comment by efij** [comment]
Tested on windows 2012 server x64 and windows 7 x64.

.net framework 4.5.1

**Comment by efij** [comment]
Tested on windows 2012 server x64 and windows 7 x64.

.net framework 4.5.1

**Comment by FlorianRappl** [comment]
More important is the version number. Which version of AngleSharp did you use?

**Comment by FlorianRappl** [comment]
> the code doesn't handle mimetype == application/pdf 

Please note that AngleSharp is an HTML library. For convenience, AngleSharp is also handling plain text (transformed as a browser would), XML, and SVG, however, handling PDF is way out of the scope of this project.

**Comment by efij** [comment]
I use the latest version.
We are on the same page regarding  the recognition of the problem.
In order for me to solve this issue i can download the webpage and check for the mime-type myself before using AngleSharp.
The thing is it affect dearly on the performance and robustness of using AngleSharp. From performance perspective  AngleSharp is being use generally in scraping system where there are intensive network usage to many different webpages anyway. Adding another test for mine-type prior AngleSharp is performance penalty.
In terms of robustness, one would expect that AngleSharp would handle anyurl, meaning if it is out of the scope in terms of parsing at least let the consumer know about it rather than crash the entire system with stackoverflowexception.

Therefore i find it extremely beneficial to solve this issue by adding to the initial harvest of the webpage inside   AngleSharp a mine-type check and verification against basic whitelist of mime-type and if this specific mine-type is not supported let the consumer know about it.

**Comment by FlorianRappl** [comment]
It won't work like this. There is a factory for documents that works against the mime-type. I agree that one should be able to integrate handlers for this, and it is certainly in scope for the next release, however, "notifying the user in case of an invalid mime-type" is not. What is an invalid mime-type? There are too many necessary requirements / definitions missing for this.

> Adding another test for mine-type prior AngleSharp is performance penalty.

It's just the header. So if you want to work against that you can just include a requester wrapper, which will call the original requester and only return the response if a certain mime type is matched. The performance penalty is _very minimal_. Requesters are not used very often and the time spent in the abstraction layer / additional call is negligible compared to the actual data transfer.

> In terms of robustness, one would expect that AngleSharp would handle anyurl [...]

Well, define "handle". It should not crash, yes (see the label: bug), but it definitely should not be able to make something reasonable about it.

I will fix the issue in the upcoming release.

Final note: If you use AngleSharp and rely on it / want it to improve then consider giving it a star. Otherwise, projects that are not starred will be abandoned some point in time (lack of interest does not motivate any further improvements).

**Comment by FlorianRappl** [comment]
Apparently, there is no SO exception. At least my test on `devel` shows that. Anyhow, the enhancement to allow registering custom handlers will still be included in relation to this issue.

**Comment by FlorianRappl** [comment]
See PR #389.
