### ISSUE TITLE
Big difference with CSS parsing in newer version

### ISSUE THREAD

**Issue by D92130** [AngleSharp/AngleSharp#395]
We used to use AngleSharp version 0.8.6,  with the following code:

```
        string css = "<html><head><style type='text/css'>p { background-color: yellow; } .dsip { display: block; }</style></head></html>";

        var cssParserOptions = new AngleSharp.Parser.Css.CssParserOptions();
        cssParserOptions.IsIncludingUnknownDeclarations = true;
        cssParserOptions.IsIncludingUnknownRules = true;
        cssParserOptions.IsToleratingInvalidConstraints = true;
        cssParserOptions.IsToleratingInvalidValues = true;

        var styleSheet = new AngleSharp.Parser.Css.CssParser(cssParserOptions).ParseStylesheet(css);

        var parsedCss = styleSheet.ToCss();
```

  The output of the parsedCss is:

".dsip { display: block; }"

After upgrade AngleSharp to the latest version 0.9.8, the output of parsedCss changed to:

"<html><head><style type='text/css'>p  { background-color: yellow }\r\n.dsip { display: block }\r\n</style></head></html> { }"

What change has caused the big difference here?  The old version CSS Parser seems handle the non-css content in the css better.

**Comment by FlorianRappl** [comment]
Woot, yes there have been a gigantic amount of changes since the version you've mentioned. I think the CSS parser has been completely rewritten since then.

From the example you've mentioned the CSS seems rather valid and  `p` rule is just fine (and seems to be correctly parsed). Do I miss anything here?

**Comment by D92130** [comment]
Thanks for your quick response.  

Looks like the html tags in my post get removed and the result of the new version output is totally messed up.

Here is actually the output of the newer version parser:

`"<html><head><style type='text/css'>p  { background-color: yellow }\r\n.dsip { display: block }\r\n</style></head></html> { }"`

It actually treats everything as an unknown selector with empty definition.  Which is weird here.

**Comment by FlorianRappl** [comment]
Well, the CSS specification does not go into much details regarding error handling. The unknown selector handling can be deactivated (and is by default deactivated, however, _you've decided_ to active it). Usually, the parser would throw it away (as the browser would do it). Otherwise, what do you expect? A CSS parser ain't no HTML parser.

**Comment by D92130** [comment]
Understood your point.

I am just reporting the discrepancy between two versions with the same exact parse options.  
My testing shows the one parse option makes the difference is actually  cssParserOptions.IsToleratingInvalidValues  
If I set it to false, the new version will generate the same old result.

If no alert is raised and everything work as intended, please feel free to close this thread.

**Comment by FlorianRappl** [comment]
Alright, glad we clarified this! 👍
