### ISSUE TITLE
Wrong value of alfa channel background property after parsing

### ISSUE THREAD

**Issue by dmbogomazov** [AngleSharp/AngleSharp#40]
AngleSharp returns wrong value of alfa channel If content has specified `background` property in rgba format.
Example:
`<table style="border:none;border-collapse:collapse;">`
`<tr>`
`<td  align="right" valign="top" style="border: 1px solid #000;background:rgba(128,128,128,255);">`
`Test`
`</td>`
`</tr>`
`</table>`

**Comment by FlorianRappl** [comment]
So I put your example into code:

```
var document = DocumentBuilder.Html(@"<table style=""border:none;border-collapse:collapse;"">
<tr>
<td style=""border: 1px solid #000;background:rgba(128,128,128,255);"">
Test
</td>
</tr>
</table>");

var td = (IHtmlElement)document.QuerySelector("td");
var color = td.Style.OfType<ICssBackgroundColorProperty>().First().Color;
Console.WriteLine(td.Style.BackgroundColor);
```

What I find is that the color is `rgba(128,128,128,1)` - as it should be. Since the last value is the alpha channel (ranging from 0 to 1, i.e. 0% to 100% opacity) your value of 255 is cropped. 100% is maximum, therefore you'll just end up at 100%.

Everything is correct here - browsers do also truncate the value to fit between 0 and 1.

**Comment by FlorianRappl** [comment]
Please note that the CSS syntax for RGBA (3 values ranging from 0 to 255, 1 number between 0 and 1) is different than the constructor. However, even though the `Color` structure stores transparency internally as a byte (ranging from 0 to 255), it also exposes the value ranging from 0 to 1 as a double precision floating point unit.

![image](https://cloud.githubusercontent.com/assets/1766191/5186632/e073ebd4-74c7-11e4-90dc-6f55c0b502ac.png)

Hope that this resolves the issue.
