### ISSUE TITLE
Parsing exception when text contains unicode null

### ISSUE THREAD

**Issue by StubbyCat2** [AngleSharp/AngleSharp#426]
Why is exception thrown in this case? I could not find any evidence that nulls are illegal. Using other Unicode control characters is fine (bell character for example). The exception is thrown if Unicode null is a numeric character reference or if its simply a literal.

```
var options = new HtmlParserOptions();
options.IsStrictMode = true;
options.IsEmbedded = true;
var parser = new HtmlParser(options);

// throws HtmlParseException or CharacterReferenceInvalidCode
parser.Parse(@"<html><body>&#0;</body></html>");

// throws HtmlParseException or HtmlParseError.Null
parser.Parse("<html><body>\0</body></html>");

// does not throw
parser.Parse("<html><body>\a</body></html>");
```

**Comment by FlorianRappl** [comment]
By the HTML specification a null character (that's different to the unicode null - here no null character enters the scanner) has to result in a parse error. Since you set `IsStrictMode` to `true`, these errors will result in exceptions.

**Comment by StubbyCat2** [comment]
Thank you for such a quick reply and for your work. Could you point me to the part in specification that says that?

**Comment by StubbyCat2** [comment]
I'm not sure I understand, which should result in parse error? UTF byte(s) that represent Unicode null code point (`\0`)? Or numeric character reference: `&#0;`. Or both? Could you please point me to the part of the spec that says this? Thank you in advance.

**Comment by StubbyCat2** [comment]
Also, I've updated original issue with error codes that appear when not in strict mode.

**Comment by FlorianRappl** [comment]
See https://www.w3.org/TR/html/syntax.html#data-state (8.2.4.1. Data state, U+0000 NULL case).

**Comment by StubbyCat2** [comment]
Your rock! That explains UTF byte representing Unicode null. But what about second error (CharacterReferenceInvalidCode) if I have a numeric character reference. Why would that result in an error?

**Comment by FlorianRappl** [comment]
See https://www.w3.org/TR/html/syntax.html#consume-a-character-reference (8.2.4.69. Tokenizing character references, U+0023 NUMBER SIGN (#) case -- look at the table).

That is also emitting a parse error, however, due to a different reason (this is an invalid character reference, as stated in the actual error code).

The original statement still holds: If you want to get rid of these exceptions, then don't use strict mode. Strict mode is not a real HTML mode - it was introduced as convenience (by popular demand). HTML is quite tolerant and will happily go on even with these errors (the specification clearly describes what to do in these cases).

**Comment by StubbyCat2** [comment]
This is great thank you. Its too much to ask, but why do you think they designated these specific code points? Why did they not include other Unicode control characters, like a Bell?

**Comment by FlorianRappl** [comment]
Most of the spec was driven by historic decisions, e.g., how browser vendors in the past (mostly Netscape) decided to handle such undefined behavior.

Since browsers started diverting a common spec needed to be designed. The majority usually won (i.e., one behavior was more common than others and thus became part of the HTML5 specification).

**Comment by StubbyCat2** [comment]
Thank you, you were very helpful and made my day. Have a good one!
