### ISSUE TITLE
Pseudo-class :has() not properly selecting children

### ISSUE THREAD

**Issue by daveaglick** [AngleSharp/AngleSharp#439]
Using `:has(> p)` will return any element that contains a `p` descendant instead of just those elements that contain `p` as a direct child.

Here's a failing test:

```
[Test]
public void HasSelectorChild()
{
        var source = @"<div><div><p>Hello in a paragraph</p></div></div>";

        var document = source.ToHtmlDocument();
        var selector = "div:has(> p)";
        var result = document.QuerySelectorAll(selector);
        Assert.AreEqual(1, result.Length);
        Assert.AreEqual(document.Body.ChildNodes[0].ChildNodes[0], result[0]);
}
```

I'm taking a look at this now and am going to attempt a PR. Might need some help depending on how far I get into the parser code.

**Comment by daveaglick** [comment]
Now that I'm digging into it, I think the problem is deeper than just getting children nodes correctly. For example, the following test also fails:

```
[Test]
public void HasSelectorFollowing()
{
    var source = @"<div><div><p>Hello in a paragraph</p><p>Another paragraph</p></div></div>";

    var document = source.ToHtmlDocument();
    var selector = "p:has(+ p)";
    var result = document.QuerySelectorAll(selector);
    Assert.AreEqual(1, result.Length);
    Assert.AreEqual(document.Body.ChildNodes[0].ChildNodes[0].ChildNodes[0], result[0]);
}
```

In both cases I _think_ it's because the `:has()` pseudo-class is missing some context about its parent node. Still digging...

**Comment by daveaglick** [comment]
As I go down the rabbit hole, I think this might be blocked by #352, specifically support for setting a real `:scope`.

What I think it missing is the ability of the inner selector to reference a particular scope element as the starting point. For example, in the selector `div:has(> p)`, the nested selector `> p` should be evaluated for every `div` using it as the scope. Just as `:scope` only points to `:root` right now because there's no way to set a scope for a given selector, `:has()` is broken due to the same limitation.

I'm sure you already know this, but I'll throw it in here for my own reference. I think the [relevant specification text](https://drafts.csswg.org/selectors-4/#relative) is:

> Certain contexts may accept relative selectors, which are a shorthand for selectors that represent elements relative to a :scope element (i.e. an element that matches :scope). In a relative selector, “:scope ” (the :scope pseudo-class followed by a space) is implied at the beginning of each complex selector that does not already contain the :scope pseudo-class. This allows the selector to begin syntactically with a combinator. However, it must be absolutized before matching.

Not sure how to proceed at this point. I'd love to help resolve this, but I'm quickly getting in over my head. Any pointers?

**Comment by FlorianRappl** [comment]
The major issue here is that the CSS selectors have been designed to be stateless. This was (and still is) important. However, now I think the following needs to be done:

Instead of providing a `Match` method that is as simple as the current one, the current one should be a specialized version of a `Match` method carrying the state of "matching". For state-aware selectors that could include, e.g., the scope. Others would just ignore given state.

All in all this will need some refactoring and redesign. When implementing / looking at the implementation of `:scope` I figured out that would be something I will take care of in the CSS extraction / CSS selector redesign (i.e., opening up the selector API and making it also much easier to extend the selector factory).

Maybe this is the right time to do it. Currently, I am mostly doing the CSS extraction. CSS selectors will still be a part of the core though (as you may or may not have seen from the current code base).

Summary: You are on the right track and your observations match my initial analysis, however, I am currently too far away from the matter to be really helpful. From what I've read you seem to be _at least_ as deep into the topic as I was when I touched it.

Thanks for your efforts here already!

**Comment by FlorianRappl** [comment]
I think PR #440 fixes this, right?

**Comment by daveaglick** [comment]
:thumbsup: Yep, this is resolved with the merge - there's tests in the PR to verify.
