### ISSUE TITLE
Nuances playing around with AngleSharp and Jint

### ISSUE THREAD

**Issue by dimio5** [AngleSharp/AngleSharp#44]
First of all, let me congratulate you for AngleSharp. It's a true .net gem with clear goals, roadmap and implementation.

I was playing around with AngleSharp 0.7 and Jint, trying to get an existing website to run a specific javascript which creates an iframe on the document.
I finally did not make it work, probably because 0.7 or the "master" branch are not js ready yet. Despite that, I am summarizing below the items that troubled me and that I see are not changed for the upcoming release:
1. The Navigator property of the AnalysisWindow can't be set as there is no setter. This forced me to specifically implement IWindow.Navigator ontop of AnalysisWindow just to put some value there.
2. The ContentWindow of the IHtmlInlineFrameElement can't be set too. This could not be overridden so I did some monkey workaround in DomFunctionInstance.Call to return the content window of the parent document.
3. Events are implemented in "master" but I see there is no "new Event()" implementation. According to MDN, every browser but IE has it. I am not sure this is in the standard or not.
4. Trying "window.foo = 'bla'; console.log(window.foo);" results in javascript error because of the way window is set as the context in JavaScriptEngine.Evaluate. I worked around this by not returning a new DomNodeInstance from "ToJSValue" in DomFunctionInstance.Call if the "_method.Invoke" result is reference equals to "node.Value". Instead I returned node.Value directly.
5. DomNodeInstance does not have a prototype nor set as extensible nor declares its own Class name. This results in some weird Jint exceptions.
6. The conversions in AngleSharp.Scripting.Extensions.cs  are too type safe. A simple "window.setAttribute('allowfullscreen', true)" instead of 'true' results in type cast exception.
7. Finally, I did not find a way to raise the readystatechange event, so I gave up!

I know most of these are not there because I was exploring a half implemented area, however I felt it would be useful to write them down and let you know. I don't consider these bugs so I wouldn't be surprised if you closed this ticket all together as being premature.
Again, thank you for this wonderful project. I don't know the eta nor the milestones of the upcoming release but I am looking forward to it!

**Comment by FlorianRappl** [comment]
This is certainly a really useful list. Thanks a lot for writing it all down!

The AngleSharp.Scripting project is currently just a proof of concept, however, I will definitely continue to improve it. This will fix some of your problems, others will have to be solved in the core library. It is definitely on my list, since one of the goals I have for 0.9 (not the next, i.e. 0.8, release) is to run html5test.com, which requires a lot of JavaScript. Then eventually jQuery should also run out of the box. This will be an interesting moment.

Now to all your bullets (some of my thoughts):
1. You are totally correct. There must be a way of injecting missing interfaces. I already thought about this, because I realized that I can't provide all interface (implementations) and also I probably should not provide all. The `IService` interface is a hint where I am going with this, but more structure and more thinking is needed to come up with something really useful. The navigator object is also required for the html5test.com.
2. I think the official interface does not allow that, but it may be one of the APIs where AngleSharp could be more useful than browsers / APIs. I could decorate the JavaScript / DOM API to be getter-only and provide an additional setter for .NET.
3. Yes, the "new" way of doing things is with an event constructor. Until now AngleSharp implemented the old way, which was using a factory method on the document (`createEvent`) in combination with a special `initEvent` (this name is different for specialized events, but it is always init*, where \* is the name of the interface) method. AngleSharp will also open up the constructor in v0.8.
4. Do you think this is generally the better way? I mean I coded the whole AngleSharp.Scripting library in a couple of hours and it is far away from being perfect. It was just meant as a starting point / proof of concept. I would happily see someone trying to improve it / fix such bugs. What you did seems like a good addition and should definitely be merged into the project.
5. I guess 4.) also applies here. Extensible should definitely be set and the rest as well.
6. Yeah you are right. Here the value should be transformed via some `toString` (maybe not the .NET `ToString()`, but rather a Jint wrapper, or something that behaves similarly) as a JS engine would do it.
7. Hm the readystatechange event should be raised automatically at the end of the document loading. Either the document has already finished loading or something weird happened. I'll have a look!

Again thanks for letting me know. If you have any useful additions to the Scripting project (as the ones noted above), then I would be more than happy to accept pull requests.

**Comment by dimio5** [comment]
Thank you for your response. 
Regarding the "fixes" for the Scripting library, please feel free to include them when you think it's better timing. Since it's a proof of concept project, I don't think there is any point in pulling in a request.
Also, no, I don't think my fixes are the "better way". It's just enough to have a working context on a window object!

As for the readystangechange, don't bother searching for a bug: I evaluated the javascript manually, after the dom was parsed, and that's why I wanted to raise the event myself.

Keep up the good work. I'll be definitely looking forward to 0.9 ;-)

**Comment by FlorianRappl** [comment]
I am closing this issue. It has been completely moved to the AngleSharp.Scripting repository. There the issue has been decomposed into smaller items. These items will be handled step by step.
