### ISSUE TITLE
UWP not support Windows-1252 encoding

### ISSUE THREAD

**Issue by quycao** [AngleSharp/AngleSharp#453]
I test some website with Google Translate and it has encoding is Windows-1252. UWP is not support this encoding so we need have option to set encoding for UWP.

Now I see it will use UTF-8 if website encoding is Windows-1252 but it is not correct in many case.

```
private static Encoding GetEncoding(String name)
        {
            try
            {
                return Encoding.GetEncoding(name);
            }
            catch
            {
                // We use a catch em all since WP8 does throw a different
                // exception than W*.
                    return Utf8;
            }
        }
```

**Comment by FlorianRappl** [comment]
I think there won't be a fix for this. AngleSharp can't fix the .NET framework. I know that you want to specify the encoding somewhere, but in such cases the solution is to wrap the responses in a transformed stream (where you transform from some source encoding to a target encoding).

The snippet above works quite alright in 95% of the cases. Of course, there are differences between the wanted encoding (which is not UTF-8) and UTF-8. But this is by definition (otherwise they would both represent the same encoding). So differences are to be expected when the fallback occurs.

Question: What would be the encoding you would set? I don't think you _can_ have an answer to that. Since you are on UWP the desired encoding is obviously not available. So which one will you choose? There are encodings which are more similar to one encoding (e.g., Windows-1252) than others, but overall there won't be a perfect match.

(this is a "no fix" at the moment, but if you can suggest a good solution that has no complexity or performance penalty and works reliably then I would happily try to implement it)
