### ISSUE TITLE
Provide option to avoid consuming character references during parsing

### ISSUE THREAD

**Issue by daveaglick** [AngleSharp/AngleSharp#494]
There are times when, as part of a longer pipeline process, we need to manipulate HTML via AngleSharp while persisting character references to the output. It looks like `HtmlTokenizer.AppendCharacterReference()` consumes all character references during the parsing phase so the original text content is lost.

I propose adding an option in `HtmlParserOptions` (and corresponding property in `HtmlTokenizer`) similar to `IsStrictMode` called `ConsumeCharacterReferences`. The default value would be true. If set to false, character references will be parsed as text content.

The `HtmlTokenizer.AppendCharacterReference()` method would be changed as follows:

```
private void AppendCharacterReference(Char c, Char allowedCharacter = Symbols.Null)
{
    if (c.IsSpaceCharacter() || c == Symbols.LessThan || c == Symbols.EndOfFile || c == Symbols.Ampersand || c == allowedCharacter)
    {
        Back();
        StringBuffer.Append(Symbols.Ampersand);
    }
    else if(ConsumeCharacterReferences)
    {
        var entity = default(String);

        if (c == Symbols.Num)
        {
            entity = GetNumericCharacterReference(GetNext());
        }
        else
        {
            entity = GetLookupCharacterReference(c, allowedCharacter);
        }

        if (entity == null)
        {
            StringBuffer.Append(Symbols.Ampersand);
        }
        else
        {
            StringBuffer.Append(entity);
        }
    }
    else
    {
        StringBuffer.Append(Symbols.Ampersand);
    }
}
```

If this sounds okay conceptually, and the suggested code changes sound reasonable, I'll submit a PR.

**Comment by FlorianRappl** [comment]
Yes, but if you submit a PR - please change / indicate two things:

- Performance impact (I guess there is one; especially measureable on the w3c page benchmark); I suppose its their but should not be severe so this would not be a blocker
- Reverse the flag. Remember the options are a struct and usually the default variant is picked. So all fields will be initialized w/o any constructor call, which is why the default (`false`) has to be chosen. Call the field, e.g., `IsUsingLiteralReferences` or similar

The major problem, however, with the PR will be that leaving the references as-is I see a problem in serialization. Usually, when you obtain a `&` character you know it was coming from an `&amp;`. Now you guess that it was coming from setting your option. Also: You need to parse / identify these references on your own.

As long as the performance is not impacted and the convention with the default for the options are followed I see no problem with the PR - indeed I think it would be great and solve some issue that arise in particular scenarios.

Thanks!

**Comment by FlorianRappl** [comment]
Landed in `devel` (see option `IsNotConsumingCharacterReferences`).

**Comment by daveaglick** [comment]
Ended up working [another use case](https://github.com/statiqdev/Statiq.Framework/issues/213) where I was hoping I could keep AngleSharp from consuming character references. Searched the issues and much to my surprise, I found an exact match...written by me 🤯. Even better, I missed you running with this and getting the support in! Thanks a ton!

This makes addressing my scenarios much easier - I do a lot of AngleSharp processing before sending stuff through Razor, so being able to encode (and keep encoded) `@` symbols (or not, depending on intent) is really important since Razor treats them as code blocks.
