### ISSUE TITLE
Cannot modify a relative URL in an anchor element

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#53]
The task is to change a bit some of the relative URLs in the document.

``` C#
var document = DocumentBuilder.Html("<a href='project/part2'>text</a>");
var a = (IHtmlAnchorElement)document.Body.FirstElementChild;
a.Href += "/1";
Console.WriteLine(document.Body.InnerHtml);
```

Expected output: `<a href="project/part2/1">text</a>`
Actual output: `<a href="about:///project/part2/1">text</a>`

Is it supposed to be like this? What's the best way to work this around?

**Comment by FlorianRappl** [comment]
The problem is that AngleSharp always tries to work with an absolute URL (just like a real browser would). However, if the document was created from a string, then no URL is given. The default URL (required by the specification) is `about:blank`. This will obviously result in wrong URLs.

You could either provide another "base URL" (there is an overload for the `DocumentBuilder.Html` method that takes a base URL), or access the `href` attribute not via the `Href` property, but its attribute value. Please note that in browsers you will also get a difference in accessing the attribute directly, or via the property. The latter will give you a "normalized" representation, while the first one will always result in the given URL.

There are two more options: The first one is that you create a new `Url` from the `Href` string. Then you can easily extract the relative part. The other one is not (yet) available to you, but I could extend the `IHtmlAnchorElement` interface with a property that is not W3C specified, but makes sense: It would basically allow direct access to the underlying `Url` type. Here you could directly access the relative part.

**Comment by thorn0** [comment]
I see, nice explanation. I ended up with the following solution:

``` C#
if (anchor.Origin == null && anchor.HostName == "") { // is the URL relative?
    anchor.Href = ModifyItSomehow(anchor.PathName);
}
```

**Comment by FlorianRappl** [comment]
Yeah that works. But I think its rather ugly. This is nothing against your code - but I think we need a better solution (in AngleSharp) and I will therefore expose the property that carries the real URL object. If you see other cases where working with the object could be made better (there are certainly a lot of cases -- right now most exposed parts are the ones from the W3C specification, hence they are verbose and very string-focused), then don't hesitate to name them here. I will try to improve all that for v0.9.

**Comment by thorn0** [comment]
You mean this real URL object will be an instance of AngleSharp.Url? Got it, makes sense.

Okay. If I find some other inconvenience or inconsistency, I'll submit an issue.

**Comment by thorn0** [comment]
BTW, in the browser, the same rules apply to the `src` property of images as to the `href` property of anchors.

``` js
var img = document.createElement('img');
img.src = 'foo';
console.log(img.src); // "http://localhost/foo"
```

But AngleSharp doesn't work like this:

``` C#
var document = DocumentBuilder.Html("");
var img = document.CreateElement<IHtmlImageElement>();
img.Source = "foo";
Console.WriteLine(img.Source); // "foo"
```

**Comment by FlorianRappl** [comment]
That's true. Should also behave like that! I consider it a bug and I will rework this to make it consistent.
