### ISSUE TITLE
Parse selector into more details models

### ISSUE THREAD

**Issue by jpoehls** [AngleSharp/AngleSharp#560]
I'm trying to use AngleSharp for parsing CSS but I need to access more details of the selector that what appear to be exposed by AngleSharp.

For example, I need to model the pseudo classes and attribute filter that are used in a selector like this:

```
var parser = new CssParser();
var result = parser.ParseStylesheet("div:has(a[href~='google.com']) {}");
```

Currently it looks like only the high level "chunks" of the selector are exposed.

![image](https://cloud.githubusercontent.com/assets/72149/26015783/f59e3558-3727-11e7-8f2e-393ce7cea30a.png)

Is there an API for getting deeper into the selector model than this or is this planned or being worked on?

Thanks!

**Comment by FlorianRappl** [comment]
Yes there is - see #352. This feature is ready, however, since it is in the v0.10 container which is currently paused it is also postponed.

If you are interested how the API looks like see #487. Essentially, it uses a visitor pattern to allow the user to walk through all object details without bothering much about the exact structure or type.

**Comment by jpoehls** [comment]
Great, thanks! I'll go ahead and close my question then.
