### ISSUE TITLE
Unable to select HTML elements of type HtmlFrameElement

### ISSUE THREAD

**Issue by RyanONeill1970** [AngleSharp/AngleSharp#580]
I'm trying to follow the links to frames in a document by using the following code;

```
var frames = document.All.Where(e => e.LocalName == "frame");
```

This yields a collection of HtmlFrameElement but I'm unable to cast any of the list items to this as the class is sealed. I can see in the Immediate window in Visual Studio that the list items have a Source property that is properly resolved to a full URL, taking account of the base document URI. It's this I'm after, not the relative URL that is held in the HTML source.

I have also tried HtmlFrameSetElement, HtmlFrameElementBase and IHtmlInlineFrameElement. They won't cast because the types are not visible outside the package.

I'm having problems pasting the HTML here but it is effectively;

```
frameset
  frame target="main" src="a.htm"
  frame target="main" src="b.htm"
/frameset
```

**Comment by FlorianRappl** [comment]
So from the top of my head there is no `IHtmlFrameElement` interface to cover your needs. Of course, we could create one (but it would not be of much use for you - due to the unknown release of v0.10).

As an intermediate workaround I suggest doing it the manual way, retrieve the elements and obtain the "src" attribute. Finally use `Url` with the two argument constructor. Since you already looked at the source you will recognize that this is pretty much what would happen underneath anyway. It is little bit inconvenient though (sorry!).

Maybe someone else knows a better/simpler way...

**Comment by RyanONeill1970** [comment]
There is an IHtmlFrameElement but I'm unable to cast to it.

I'll work around it with reflection or the approach you suggested for now, thanks Florian.

**Comment by FlorianRappl** [comment]
> There is an IHtmlFrameElement but I'm unable to cast to it.

Are you sure? Don't you mean the `HtmlFrameElement` class, which is internal?
