### ISSUE TITLE
Unexpected about:// protocol added to AnchorElement href property

### ISSUE THREAD

**Issue by duncanawoods** [AngleSharp/AngleSharp#583]
Unexpected about:// protocol added to AnchorElement href property:

```
    var html = "<html><body><a href='/page.html'>page</a></body></html>";
    var doc = new HtmlParser().Parse(html);
    var anchor = doc.QuerySelector("a") as IHtmlAnchorElement;
    Console.WriteLine("Href property " + anchor.Href);
    Console.WriteLine("Href attribute " + anchor.GetAttribute("href"));
```

Prints

> about:///page.html
> /page.html

**Comment by FlorianRappl** [comment]
This is by design. Your page apparently has no base URL, thus the relative links are still absolute to the default URL (which is - by specification - about://blank). Also the Href will always normalize links - this is also specified. You get the original via GetAttribute (which is what you do).

You could use the browsing context and set the proper base URL. Actually, using the HTML Parser directly is not recommended (only for experts / specific use cases), as it limits you drastically.
