### ISSUE TITLE
how do I build AngleSharp.css from devel

### ISSUE THREAD

**Issue by vivekjMSFT** [AngleSharp/AngleSharp#586]
How do I get the "AngleSharp.Css"? I got the AngleSharp devel branch but it doesn't seems to have AngleSharp.Css build separately.  Also, is there a way to get the non-portable assembly built for angelsharp. 
Sorry for the nuisance questions.

**Comment by FlorianRappl** [comment]
1. https://github.com/AngleSharp/AngleSharp.Css
2. What you mean non-portable? AngleSharp is a portable library (or .NET Standard 1.0 compatible - for that matter). There are builds for SL50 and NET40, which you can trigger from Visual Studio or via the command line. (If you write non-portable you should specify the platform, otherwise I can't help you much.)
