### ISSUE TITLE
Unicode Noncharacter Stops Parsing

### ISSUE THREAD

**Issue by douglasg14b** [AngleSharp/AngleSharp#590]
As the title says `GetElementById` doesn't seem to work on this page. The appropriate element ID definitely exists on the page, JQuery finds it no problem.

The element: `<span id="ctl00_cphRoblox_PostView1_ctl00_Pager">`

### Example HTML File: 

[testhtml.zip](https://github.com/AngleSharp/AngleSharp/files/1220247/testhtml.zip)

### Example Code:

```csharp
string testHtml = File.ReadAllText("testhtml.html");
HtmlParser parser = new HtmlParser();
IHtmlDocument document = parser.Parse(testHtml);
IElement element = document.GetElementById("ctl00_cphRoblox_PostView1_ctl00_Pager");
```

The `IElement` will be null. This may have to do with unicode characters elsewhere on the page? If I save the html as a `.txt` file which removes unicode characters this works fine.

**Comment by FlorianRappl** [comment]
Nah. Please look at the things first in the browser. The page contains some clear errors with JS escaping, thus there is no body nor the element you are looking for.

This is not an AngleSharp problem, but a problem with the page (at least in the form/format you've saved it).

![image](https://user-images.githubusercontent.com/1766191/29248402-a9e3626c-8017-11e7-9009-7cd71b10be5d.png)

![image](https://user-images.githubusercontent.com/1766191/29248405-b7bf0832-8017-11e7-91ff-1c41dd53f136.png)

**Comment by douglasg14b** [comment]
@FlorianRappl I don't believe this is invalid..... your library parses these pages perfectly fine EXCEPT for this one.

The page parses just fine if you convert that `html` file to a `.txt` file, which removes a host of unicode characters (At least in windows notepad), this is where my assumption comes from. Similarly, I've successfully parsed ~35 million other pages with the same escaping issue using AngleSharp, this page is unique for some reason.

Here is the actual webpage: https://forum.roblox.com/Forum/ShowPost.aspx?PostID=37319487

### Here is the `getElementById` working:

![image](https://user-images.githubusercontent.com/1400380/29279879-1dc9d61e-80ce-11e7-9643-7c275cc269b1.png)

Similarly, if I (poorly mind you) remove non-ASCII characters programmatically using the provided HTML file, it works. This is why I am suggesting a potential issue with AngleSharp.

### Example Code That Works:

```csharp
string testHtml = File.ReadAllText("testhtml.html");
testHtml = Regex.Replace(testHtml, @"[^\u0020-\u007E]", string.Empty);
HtmlParser parser = new HtmlParser();
IHtmlDocument document = parser.Parse(testHtml);

IElement element = document.GetElementById("ctl00_cphRoblox_PostView1_ctl00_Pager");
```

**Comment by FlorianRappl** [comment]
I've tested the page in an actual browser. This is the same result. I did not change the HTML file. The result is above - the browser only sees a head and no body. Therefore I believe in a problem in the HTML file itself.

Here is what I suggest:

1. Verify first that a browser is able to handle the HTML and give you the DOM you expect. Maybe the file you gave me here is corrupt.
2. Come up with a MWE to reproduce the issue. The page contains way too many stuff that is not / won't be required to reproduce the issue, if it exists. Keep it as short as possible.

Also for 1. I remind you that any effects introduced by JS need to be taken away (the page contained quite some JS tags, hence I am not sure if the result differs with JS being active - but since you are using the plain parser I assume you are not considering JS.

**Comment by douglasg14b** [comment]
@FlorianRappl 

Here are two minimal examples that the browser can handle, and that `document.getElementById` works in.

The first has the unicode characters, and AngleSharp cannot work with, the 2nd has those removed and AngleSharp works with it just fine.

[test html.zip](https://github.com/AngleSharp/AngleSharp/files/1223400/test.html.zip)

**Comment by FlorianRappl** [comment]
Can you post them directly? They are not minimal if I need to download a zip.

**Comment by douglasg14b** [comment]
@FlorianRappl

Github does not allow you to attach .html files to issues, which is why they are in a zip, it's utilized as a container. I am not sure if posting them directly will alter the content after githubs sanitization (or their DB schema encoding...etc), which is the reason for the zip file. But I will anyways.

Edit: It did alter the content.

### Non-Working:

```html
<html>
    <body>
        <table>
            <tbody>
                <tr>
                    <h2 id="ctl00_cphRoblox_PostView1_ctl00_PostTitle" CssClass="notranslate" style="margin-bottom:20px">￿￿ A great group for sale￿￿</h2>
                </tr>
                <tr>
                    <span id="ctl00_cphRoblox_PostView1_ctl00_Pager">
                </tr>
            </tbody>
        </table>
    </body>
</html>
```

### Working

```html
<html>
    <body>
        <table>
            <tbody>
                <tr>
                    <h2 id="ctl00_cphRoblox_PostView1_ctl00_PostTitle" CssClass="notranslate" style="margin-bottom:20px">A great group for sale</h2>
                </tr>
                <tr>
                    <span id="ctl00_cphRoblox_PostView1_ctl00_Pager">
                </tr>
            </tbody>
        </table>
    </body>
</html>
```

May I ask why you are being so confrontational? I'm trying to address what seems to be a bug, hoping you as the author might provide some insight. Typically I would fix bugs I find myself and submit a pull request, but your library is pretty large, I wouldn't know where to start.

**Comment by FlorianRappl** [comment]
Confrontational? Rather constructive. I mean there are plenty of issues and plenty of requests, but time is an issue. Thus any item needs be well prepared and its just (and should be understandable) normal to require a least amount of work in preparation by the submitter of any report (this is the infamous MWE I am requesting).

Your example works for me - https://dotnetfiddle.net/1VtmAB, but I guess the encoding issue you are after is not present there since you posted plain text (what I suggest you to do is a mixture of plain text with a byte array).

> I'm trying to address what seems to be a bug, hoping you as the author might provide some insight.

Potentially your issue lies somewhere else. I am still investigating if this is a bug at all. Hence the reason I am keen on a MWE to reproduce the issue and exclude other possibilities such as misuse.

In your original code you are doing

```cs
string testHtml = File.ReadAllText("testhtml.html");
```

This is an ill start. When you insert a string in AngleSharp no encoding detection will be performed (thus is .NET infers the wrong type of encoding then AngleSharp has to deal with strange characters). The string is already UTF-16 (this is the .NET encoding). You should either present a stream or a byte array with the original unmodified content.

**Comment by douglasg14b** [comment]
@FlorianRappl 

Gotcha. It just sounded rather confrontational than constructive from my end. I understand time is precious, I didn't consider that initially. That aside though:

I went ahead and used a FileStream instead and the issue persists:

```csharp
FileStream testHtml = File.OpenRead("testhtml1.html");
```

If I add this character to the html it seems to no longer be parsed as expected: [Unicode Noncharacter](http://www.fileformat.info/info/unicode/char/ffff/index.htm)

Can you try the examples in my zip? The pasted text is altered and the characters were replaced by replacement characters (�). As soon as I remove those characters everything seems hunky dorey.

**Comment by FlorianRappl** [comment]
I remember an ambiguity regarding non-characters (to be treated as EOF). I am unsure if / when it was resolved. To be sure we are not re-solving a problem just a question: Have you tried to parse the same page with the latest version of the lib (from `devel`, i.e., AngleSharp v0.10)?

**Comment by douglasg14b** [comment]
@FlorianRappl 

Just tried it, built for .net 4.5, issue is the same.

**Comment by FlorianRappl** [comment]
Alright convinced. This is indeed a problem and it is definitely not fixed yet.
