### ISSUE TITLE
Would a "Fragments Mode" be feasible?

### ISSUE THREAD

**Issue by deanebarker** [AngleSharp/AngleSharp#594]
Are there any plans in the roadmap to allow AngleSharp to parse HTML as _fragments_, without forcing the creation of a full, valid HTML doc?

I originally brought this up in #398, and I'm seeing more and more situations -- especially in web content management scenarios -- where we're dealing with _known_ HTML fragments that we have no intention of forming complete documents out of. In these cases, it causes problems when AngleSharp creates `HTML`, `HEAD`, and `BODY` tags and then moves HTML tags around to the "correct" location.

Any plans to perhaps have a "Fragments Mode" or something for AngleSharp where we'd tell the library that we _know_ this is an invalid fragment of HTML and should _stay_ a fragment without a surrounding document or any attempt to move tags around?

As an FYI, here's a comment from one of my tools which attempts to explain around this --

    /*
    
    This method returns something odd, and here's why...

    AngleSharp is a very "correct" parser. It emulates HTML5, all the way down to "fixing"
    structural problems in your HTML. What this means is that AngleSharp will form a
     _complete_ HTML document, which might involve moving tags that normally go in the
    HEAD of your document to that location in its final HTML document. So, depending on
    what the outer tag structure was, your fragment might end up in the HEAD or BODY
    of the resulting HTML document.

    This is by design with AngleSharp, and we didn't figure this out until deep into the
    integration of it as the core HTML parsing library of Ellis.
    (See: https://github.com/AngleSharp/AngleSharp/issues/398)

    Consequently,  we never really have any idea if your HTML fragment ended up in the
    HEAD or the BODY of the HTML document, and all we can really do is concatenate
    them and hope for the best. In most all situations, it will be in one or the other -- so the
    BODY will have something and the HEAD will be empty, or vice-versa. But this isn't
    always true, and we're really sorry about that.
    
    */

    return string.Concat(
      ParsedContent.Owner.DocumentElement.QuerySelector("head").InnerHtml,                    
      ParsedContent.Owner.DocumentElement.QuerySelector("body").InnerHtml
    );

**Comment by FlorianRappl** [comment]
There is already a fragment mode. It returns a `NodeList`. Other than that the problem is a difficult one in general, though an easy one in special (i.e., ordinary) cases.

The general difficulty arises from the different modes that are taken into account by an HTML5 parser. As such your HTML fragment may only be valid in a certain mode - in the fragment mode this can be corrected by specifying a specific context element.

I wonder if you checked out fragment parsing and if your requirements go beyond this possibility.

**Comment by deanebarker** [comment]
Is this new? Did I miss this in the discussion in #398?

**Comment by FlorianRappl** [comment]
The fragment parsing is there since... I don't know when exactly, but it must be somewhere around the first releases of the lib. I'm not sure why it was not discussed in #398, but I think I did not see that you wanted to have a fragment parsing back then. All I saw was the insertion of head, body, etc. - which happens in the full parsing and is according to the spec. The fragment parsing is also defined in the W3C spec and AngleSharp follows that specification closely (e.g., with the possible modes being activated by the right context element).

Does that help you?

**Comment by deanebarker** [comment]
So, I tried this:

    var p = new HtmlParser();
    var doc = p.ParseFragment("<script>deane</script><div>deane</div>", null);
   
But `doc.OuterHtml` still contains an entire HTML document, complete with `HEAD` and `BODY` tags. And the `SCRIPT` tag has been moved into the `HEAD`.

    <html><head><script>deane</script></head><body><div>deane</div></body></html>

Is this the correct behavior for a fragment?

**Comment by FlorianRappl** [comment]
What you get back is a NodeList (I am surprised you call it a document, but of course the name does not matter). Since you did not specify a context element the context was not used and the parsing is as if you are in a blank document. The OuterHtml should not bother you - it is just one possible form of serialization.

What you see is the correct behavior. If order to trigger some other mode (see my earlier comment) please specify a proper context element (parsing HTML is complicated and always requires a context to enable the right parsing rules).

**Comment by deanebarker** [comment]
Okay, I think I might have it.  Something like this?

	var fragment = "<script>deane</script><div>deane</div>";
	
	var p = new HtmlParser();
	var dom = p.Parse("<html><body></body></html>");
	var nodes = p.ParseFragment(fragment, dom.Body);

	var sw = new StringWriter();
	nodes.ToList().ForEach(n =>
	{
		n.ToHtml(sw, XhtmlMarkupFormatter.Instance);
	});
	return sw.ToString();

That returns:

     <script>deane</script><div>deane</div>

Which appears to be what I'm looking for. Am I on the right track?

**Comment by deanebarker** [comment]
More concise:

	var sw = new StringWriter();
	nodes.ToHtml(sw, XhtmlMarkupFormatter.Instance);
	return sw.ToString();

**Comment by FlorianRappl** [comment]
Yes, looks good to me. Potentially the code can be even simplified by setting InnerHtml (which also does invoke the fragment parsing) and serializing using the ChildNodes property.

Some code to show you the idea:

```cs
dom.Body.InnerHtml = fragment;
return dom.Body.ChildNodes.ToHtml(XhtmlMarkupFormatter.Instance);
```

**Comment by deanebarker** [comment]
One problem: `INodeList` does not appear to be "queryable".  I found some extension methods in `QueryExtensions.cs`, but that class is internal, so I can't get at it.

How do I run a query on a `NodeList`?

**Comment by FlorianRappl** [comment]
Just start from the given "root", e.g., in the example above from the body. The issue is that you need a single point of entry. The extension works around it by taking every item of the node list as an entry point.

**Comment by dcasso** [comment]
I would love to comment on this one, because this one caused me to have to use CSQuery for a part of my codebase.

First of all, great product you build.

I have a case where I need to parse a string containing content similar to:
`<tr><td>abc</td><td>def</td></tr><div>value</div>`

When this is run with angle sharp, it removed the tr and td and result is 
`abc def<div>value</div>`

and I am try to extract for example second td, this will not give any result with AngleSharp.

Whereas CSQuery has a fragmentloader allowing you to parse the above as it is, and give back def.

It is of course not something many needs, but it is a very valuable function.

**Comment by FlorianRappl** [comment]
Hi @dcasso have you checked out the fragment parsing of AngleSharp? What it needs, however, is a context root. In your case you'll need to have a `tbody` to ensure proper parsing. AngleSharp is W3C conform and thus will follow the HTML5 parsing rules. HTML is full of edge cases and rules and the interpretation of a certain substring is fully dependent on the environment where this snippet is placed in.

At the moment I do not know how feasible the interpretation of your string would be - it sounds more like XML / raw tag interpretation is what you want. If we assume that we are always in a table then some other snippets may not work correctly.

Usually, however, for such a substring you already know the context (e.g., the string should be the `InnerHtml` of some existing node). In this case you can fully apply fragment parsing (which is btw implicitly applied when setting something like `InnerHtml` or `OuterHtml`).

Hope this helps!
