### ISSUE TITLE
How to send cookies

### ISSUE THREAD

**Issue by realLiangshiwei** [AngleSharp/AngleSharp#595]
Hi 
AngleSharp is good Project, I've been using it all the time, I wonder how How do I add a cookie to a browerContext,This puzzled me for a long time
thank you

**Comment by FlorianRappl** [comment]
Hi @ShiWei-L , thanks for your question.

AngleSharp uses an `ICookieProvider` interface to get/set cookies. Cookies are retrieved before sending an HTTP request (only domain-matching cookies are being sent). Likewise, after receiving an HTTP response cookie for the respective domain are being set.

So for your particular questions there are multiple answers:

- You could wrap or rewrite an HTTP requester (by implementing the `IRequester`) - thus circumventing the usual cookie resolution and just sending whatever cookie you'd like to
- You could manipulate the cookie container instance (similarly, you can either use the existing simple MemoryCookieProvider or roll your own one), thus ensuring that the cookie you want to send will be sent
- You could also set the cookie of the document you have - requests to the same domain will be fired with the given cookie

In order to determine which approach suits your use case best you need to be a little bit more specific what scenario you have in mind. Thanks!

**Comment by realLiangshiwei** [comment]
I read the source code and found what I needed。In the end Hopefully there will be a complete document
Thank you
