### ISSUE TITLE
Set position to zero when parsing a stream

### ISSUE THREAD

**Issue by Hazzamanic** [AngleSharp/AngleSharp#611]
When passing in a stream to the html parser, it doesn't set the position to zero before parsing. 

Though it does serve as a reminder to block heads such as myself, that they really ought to go learn about streams before playing with streams.

**Comment by FlorianRappl** [comment]
This is intentional. First of all not all streams can randomly set their position (e.g., an unbuffered network stream cannot be played back) plus you may have, e.g., a raw HTTP response that is already at the body part (the headers should not be parsed by the HTML parser). There are multiple other examples that provide a valid use case for not modifying the stream unnecessarily.

Unfortunately, AngleSharp cannot possibly know if your stream should be reset. I guess the "inconvenience" to modify the stream manually is worth the extra scenarios it offers.

**Comment by Hazzamanic** [comment]
Ah makes sense. Thanks for the explanation. I really do need to learn more about streams haha
