### ISSUE TITLE
How to get width and height for img tags

### ISSUE THREAD

**Issue by Sicos1977** [AngleSharp/AngleSharp#616]
This probably sounds like a very stupid question but how do I get the parsed values for an image without downloading the actual image. The reason why I need this is because I need to know if an image is going to fit on a page (for example a letter) and I want to avoid downloading every image when it is not needed.

I want to detect the width and height for the image in the following cases:

- the width and height is declared like this `<img src="example.jpg" width="200px" height="300px">`
- the width and height is declared with a class like this
```
...
<style>.image {width: 100px; height 200px}</style>
...
<img src="example.jpg" class="image">

```
- the width and height is declared in the style attribute like this `<img src="example.jpg" style="width: 400px; height:300px">`

I already tried things like this:
```
            var config = Configuration.Default.WithCss();

            var parser = new HtmlParser(config);
            var document = parser.Parse(webpage);
            
            // ReSharper disable once PossibleInvalidCastExceptionInForeachLoop
            foreach (var htmlImage in document.Images)
            {
                // The local width and height attributes always go before css width and height
                var attributeWidth = htmlImage.Attributes.GetNamedItem("width");
                var attributeHeight = htmlImage.Attributes.GetNamedItem("height");
                var attributeStyle = htmlImage.Attributes.GetNamedItem("style");
                if (attributeStyle != null)
                {
                    var css = parser.Parse(attributeStyle.Value);
                }

                if (htmlImage.ClassList != null)
                {
                    if (htmlImage.ClassList != null)
                    {
                        foreach (var value in htmlImage.ClassList)
                        {
                            var css = document.QuerySelector(htmlImage.TagName + "." + value);
                        }
                    }
                }

```

**Comment by FlorianRappl** [comment]
The CSS one will be difficult (besides the obvious case that you mentioned - which is indeed trivial - it may be a lot harder when relative units, inheritance, and other things come into play).

Now approaching the problem in two steps:

1. What can be done from the DOM? We have `DisplayWidth` and `DisplayHeight` properties on an `IHtmlImageElement`. These are already computed and give us either the value from the width / height (if correctly specified) or of the responsive image (if given). So this is the easy case.
2. The `style` property already contains a parsed representation of the inline style. I am not sure why you parse it again. Also you should use `BrowsingContext`. `HtmlParser` is a low level construct. In any sense - what would be most useful here is something from the `IWindow` context, which is accessible via the `BrowsingContext` instance (property `Current`). Every `IWindow` has a `GetComputedStyle` method. Using this like `context.Current.GetComputedStyle(myImageElement)` will give you the computed style. Now you could look for width and height declarations, but with the limitations / edge cases given in the introduction.

Hope this helps!

**Comment by Sicos1977** [comment]
Thanks for the quick response.

This part of the code was just to see if I could parse the style attributes to a list that way... never used AngleSharp before so that was just to see what it did.

```
                if (attributeStyle != null)
                {
                    var css = parser.Parse(attributeStyle.Value);
                }
```

For the rest I'm just a noob regarding AngleSharp. Never used it before because I always used HtmlAgilityPack for HTML related things. But that one can't handle HTML 5 documents so that is why I switched to AngleSharp. IMHO AngleSharp has a much better object model to work with the DOM

**Comment by gayratv** [comment]
Thanks for reply,
according to this topic, I have next question (I'm noob also and use AngleSharp for HTML parsing).
Because I can't find full documentation, I'm read this threads, WIKI, examples, but some methods don't described :)
Many peoples uses Configuration
var config = Configuration.Default.WithCss();
var config = Configuration.Default.WithDefaultLoader(requesters: new[]{requester}).WithJavaScript().WithCss().WithCookies();

Also people work with css:
var cssStyleEngine = new CssStyleEngine();

Where I can read more information about AngleSharp (configuration, CSS parce and so on) ?

**Comment by FlorianRappl** [comment]
There have been efforts to write a complete documentation, but since community (support) was missing it was pretty much abandoned. Obviously, there is no money in OSS development (no problem with that), but if even essential support / engagement is missing then motivation and prioritization is going down. If you want to start something (and may it just be a collection of all the questions that come to your mind - it would indeed be a helpful starter) then we could at least end up with a "cookbook" style documentation (incl. general introduction, recipes, and FAQs). 🍻

**Comment by FlorianRappl** [comment]
On a general note:

- The DOM being used in AngleSharp uses the W3C proposal with some custom extensions (usually provided in form of extension methods to have a clear separation). That way the knowledge gained here is easily transferable to a browser (or if one already worked with the DOM in the browser the other way round is already given).
- Configuration is used to determine the inner workings of contexts, parsers, the created (CSS/D/x)OM.
- A browsing context is a representation of a "headless tab" so to speak. So if you see a tab in your favorite browser then think of it as an AngleSharp BrowsingContext + some renderer + obviously a lot more stuff (e.g., JS engine, plugins such as Flash, ...).
- The different parsers are either called implicitly or explicitly (implicit if, e.g., we activate CSS parsing and a style sheet is found during an HTML parse; explicit if, e.g., we trigger loading a page). They sometimes have some set up to determine some rules (e.g., CSS parser may drop unknown rules which could be unwanted due to a custom DSL or CSS flavor - or a limitation in the CSSOM).

**Comment by Sicos1977** [comment]
Can BrowsingContext also just accept text like the parser does? I'm behind a proxy server so that is why I'm asking.

```
            var webpage = _sourceUri.Scheme == "file"
                ? File.ReadAllText(_sourceUri.OriginalString)
                : DownloadString(_sourceUri);

            var parser = new HtmlParser(config);
            var document = parser.Parse(webpage);

            var config = Configuration.Default.WithCss().WithDefaultLoader(c => c.IsResourceLoadingEnabled = true);
            var context = BrowsingContext.New(config);
            var document = context.OpenAsync(new Url(_sourceUri.ToString())).Result;
```

**Comment by Sicos1977** [comment]
Also another thing.

_What can be done from the DOM? We have DisplayWidth and DisplayHeight properties on an IHtmlImageElement. These are already computed and give us either the value from the width / height_

These are always 0.

I have a very simple test file like this:
```
<html>
<head>
	<style>
		.image {
			width: 200px;
			height: 300px;
		}
	</style>
</head>
<body>
<img src="https://fthmb.tqn.com/mRwKaN0ZnLf5ZVl4lihy0jYc2_M=/960x0/filters:no_upscale()/a0047-000145-56a2bce25f9b58b7d0cdf7cf.jpg" width="1000px" height="890px"><br/>
<img src="https://i.amz.mshcdn.com/-DMwDOUQaMCsiNpGJb6GVl5fkM4=/fit-in/1200x9600/https%3A%2F%2Fblueprint-api-production.s3.amazonaws.com%2Fuploads%2Fcard%2Fimage%2F533525%2F987d31df-2a7e-4ed9-838f-c0b92bf494d4.png"><br/>
<img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/Hamster_057eue.jpg" class="image"><br/>
</body>
</html>
```

And when I load that one with the parser like this
```
            var parser = new HtmlParser(config);
            var document = parser.Parse(webpage);
```

Then the result is always  0
![capture](https://user-images.githubusercontent.com/6692947/33832769-9e85eaec-de7d-11e7-8045-ab805e3385e8.PNG)

**Comment by Sicos1977** [comment]
Uhm... it seems AngleSharp doesnt like px in a width tag. Yes I know this is not standard but since we have very old html files overhere that needed to be parsed I added it anyway.

**Comment by FlorianRappl** [comment]
Hm according to the spec the value is an integer - thus no (CSS) units are expected.

The other question regarding an already given string is answered with

```cs
Task<IDocument> GetFromSource(string source) {
  // such as var source = "<body>...</body>";
  var context = BrowsingContext.New();
  return context.OpenAsync(m => m.Content(source));
}
```

Note: only used this function for illustration. Not much sense giving an additional wrapper to `OpenAsync` otherwise.

Pro Tip: The callback variant of `OpenAsync` is quite powerful. It can be chained for further manipulation. What it actually does is creating a "fake response", i.e., a response object such as-if a real request to a server was sent earlier. Examples include

```cs
m.Content(source).Address(myAddress).Header("name", "value").Header("name", "value").Status(201)...
```

**Comment by Sicos1977** [comment]
For now I cooked this up to get the width and height. Only need to figure out how to get the width and height from an inline or external css element.... any tips? I'm planning only to support px values nothing else.

```
            var config = Configuration.Default.WithCss();
            var context = BrowsingContext.New(config);
            var document = context.OpenAsync(m => m.Content(webpage)).Result;

            // ReSharper disable once PossibleInvalidCastExceptionInForeachLoop
            foreach (var htmlImage in document.Images)
            {
                // The local width and height attributes always go before css width and height
                var width = htmlImage.DisplayWidth;
                var height = htmlImage.DisplayHeight;

                if (height == 0 && width == 0)
                {
                    var attributeStyle = htmlImage.Attributes.GetNamedItem("style");
                    if (attributeStyle != null)
                    {
                        var parts = attributeStyle.Value.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
                        foreach (var part in parts)
                        {
                            var subParts = part.Split(new [] {':'}, StringSplitOptions.RemoveEmptyEntries);
                            var name = subParts[0].ToLowerInvariant().Trim();
                            var value = string.Empty;
                            if (subParts.Length == 2)
                                value = subParts[1];

                            if (value.EndsWith("px"))
                            {
                                switch (name)
                                {
                                    case "width":
                                        width = ParseValue(value);
                                        break;
                                    case "height":
                                        height = ParseValue(value);
                                        break;
                                }
                            }
                        }
                    }
                }

                //if (htmlImage.ClassList != null)
                //{
                //    if (htmlImage.ClassList != null)
                //    {
                //        foreach (var value in htmlImage.ClassList)
                //        {
                //            var css = document.QuerySelector(htmlImage.TagName + "." + value);
                //        }
                //    }
                //}


                Image image = null;
                // If we don't know the image size then get if from the image itself
                if (width <= 0 || height <= 0)
                {
                    image = GetImage(new Uri(htmlImage.Source));
                    width = image.Width;
                    height = image.Height;
                }

                if (width > maxDimension.Width || height > maxDimension.Height)
                {
                    var extension = Path.GetExtension(htmlImage.Source);
                    var fileName = GetTempFile(extension);

                    // If we did not load the image already then load it
                    if (image == null)
                        image = GetImage(new Uri(htmlImage.Source));

                    image = ScaleImage(image, maxDimension.Width);
                    image.Save(fileName);
                    htmlImage.DisplayWidth = image.Width;
                    htmlImage.DisplayHeight = image.Height;
                    htmlImage.Source = new Uri(fileName).ToString();
                    changed = true;
                }
            }

            if (!changed) return true;
            outputFile = GetTempFile(".html");
            using (var textWriter = new StreamWriter(outputFile))
                document.ToHtml(textWriter, new AutoSelectedMarkupFormatter());
            return false;
```
