### ISSUE TITLE
Lower-level access to the CSS parser

### ISSUE THREAD

**Issue by thorn0** [AngleSharp/AngleSharp#62]
I'd like to examine the original value of the `style` attribute of an element as key-value pairs. However, `element.Style` doesn't allow exactly this. For example, if I parse this element

``` html
<span style="color:yellow;  text-decoration: underline;/*background-color:red*/">﻿</span>
```

and check `element.Style.ToDictionary(x => x.Name, x => x.Value)`, this dictionary will have 4 elements: `text-decoration-line`, `text-decoration-style`, `text-decoration-color`, `color`. That's nice for many scenarios, but I need to work with the original two entries: `color` and `text-decoration`. As far as I can see, AngleSharp doesn't provide any support for this, does it?

**Comment by FlorianRappl** [comment]
Unfortunately no - the values are directly parsed and expanded according to the specification. However, see #38, there will be another possibility in the future, which will also be accessible publicly.

**Comment by corliss** [comment]
I didn't realize that AngleSharp had such a serious limitation. As such I'd like to also comment that this makes it unusable for me at present (in addition to the round-tripping issue in #38.)

Rather than use the term "the specification", I'd suggest referring to the precise one.
CSS has many specifications. 

The [CSS OM specification](http://dev.w3.org/csswg/cssom/#introduction) - which is the one I think you're referring to - says this: "The core features of the CSSOM are oriented towards providing basic capabilities to author-defined scripts to permit access to and manipulation of style related state information and processes." This is in their own description, a "basic" set of capabilities. I personally don't think this is a well-conceived document. It does not even describe the scenarios it intends to address. In any case, it is _not_ definitive. It is simply one way of accessing CSS.

What's ironic is that this "basic" OM is far more complicated, and far less powerful, than a straightforward recursive descent CSS parser would be. It exposes all kinds of complicated operations (including the one this issue is about) that few people really want. A parse tree provides all the power _and_ simplicity needed for virtually any scenario, IMO.

My suggestion is to revisit the goals of AngleSharp rather than simply adopting the CSSOM. If you look at the CSS community there are all kinds of css tools - parsers, munglers, minimizers, editors, and of course web browsers. The CSSOM fails at almost all these tasks, whereas a good parser is the foundation for all.  

The [CSS 2.1 specification](http://www.w3.org/TR/CSS21/). This is the last "complete" CSS specification. CSS3.0 and higher use modular specifications - of which there are now dozens - to describe various aspects of CSS. This is why I still refer to this one a lot. This specification is the definitive one in terms of describing the source language (at the 2.1 level). Providing an API that exposes the CSS source in a direct way with source round-tripping is much more important, IMO, than providing an API that is just an implementation of the CSS OM. 

Therefore I'd suggest:
1) Please mention which specification you are referring to at all times.
2) The CSS OM is not as important as you might think. A complete, accurate representation of the CSS source is key. (These are not in conflict however, as the implementation proposed in #38 shows.)

**Comment by FlorianRappl** [comment]
1) For the CSSOM there is just one specification, hence there is no need for clarification (I will always refer to the latest / or one of the latest versions; otherwise take the recommendation as base). The URL is given on many occasions, but just to have it one more time: http://dev.w3.org/csswg/cssom/

2) The goal of AngleSharp was, is and will also be in the future, to bring the same API and same behavior as we can find in the most common browsers to C# - without requiring any native bridge. If the API would behave differently or if the API would be completely different, than people would be required to learn just another API.

I am sorry that AngleSharp does not fit your needs, but writing a CSS parser for your needs seems to be fairly easy and straight forward (as you already found out - the CSSOM complicates things a lot). Hence I suppose you can just do it yourself.

**Comment by corliss** [comment]
1) The suggestion was simply - do you mean the CSSOM specification or some other specification. It may be obvious to you that the CSSOM specification is meant, but many of us read the other CSS specifications frequently as well. Hence "the specification" is a bit unclear.

2) By straightforward, I mean _conceptually_. As we both know there's a lot in CSS, so writing a good parser for .net is a worthy challenge. AngleSharp has most of the code, but does not have it exposed the right way. Both thorn0 and I seem to have hit similar limitations, so that's feedback for you.
