### ISSUE TITLE
The ConditionalWeakTable becomes a bottleneck with parallel html processing

### ISSUE THREAD

**Issue by tommymonk** [AngleSharp/AngleSharp#637]
We've tried master and devel with production work-loads and found that we aren't able to utilize more than ~50% of the CPU.

Our use-case is parsing and running CSS selectors on millions of HTML documents each day. We noticed that no amount of parallelism would allow the majority of the CPU to be utilised.

I decided to try and track down the limitation, the attached code spins up some threads that each parse and query the same html document.

When I profile the application I see that the hot and contentious parts of the code all involve the ConditionalWeakTable used by Node.cs

I'm unable to think of an optimization that would either reduce contention or improve performance.

[cpu_perf_test.txt](https://github.com/AngleSharp/AngleSharp/files/1634853/cpu_perf_test.txt)

**Comment by FlorianRappl** [comment]
There are several things in there to remark.

1. The conditional weak table is obviously also synced / held consistent. So running with multiple simultaneous accessors will obviously have an impact on performance.
2. In real world scenarios IO would be more interesting (i.e., the waiting time to download the page).
3. The question is if running on a single core would actually fully utilize the single core (i.e., 1 thread = 1 / n of the CPU, where we have n cores).

Potentially, the conditional weak table could be replaced with something else. I will need to look into the details, where it is actually used and what impact a replacement would have on the code.

**Comment by tommymonk** [comment]
1) Agreed, I think that the ConditionalWeakTable will have some overhead with high GC.
2) Our application is offloading IO tasks, so this analogue of processing documents continuously is fairly representative.
3) Running on an i7-6700 (4 core, 8 with HT) I see a steady 13% usage which implies it is able to fully utilize the thread

The ConditionalWeakTable seems well suited to it's task, but I wonder how some other collection such as ConcurrentDictionary would compare. It would obviously produce a managed leak should someone forget to dispose documents properly.

**Comment by FlorianRappl** [comment]
> It would obviously produce a managed leak should someone forget to dispose documents properly.

I think this was the original reason for it (not sure anymore though). In the best case there may be some other option that does not come with the described disadvantage.

**Comment by Joe118** [comment]
@FlorianRappl yes, it was indeed the original reason.

There shouldn't have to be a super-global table for the weak links table. You could take advantage of the locality of these weak links (i.e. always pointing to elements in the same parse tree). That would make it possible for each parse tree to have its own table. As it is now, the cost of incorrect usage (usage that would violate the assumption of locality) is paid by EVERY use; instead it would be better to make only those uses that violate the assumption expensive. :)

**Comment by comdw** [comment]
I looked at ConditionalWeakTable usage in Node.cs (the main contention hotspot) and couldn't find any reason not to simply use a backing field for the Owner property instead of this table (at least for this use case and for the purpose of isolating ConditionalWeakTable from further performance tests).

Having tried this approach with the example attached in the first post, single-thread performance improves by around 50% but there is still a bottleneck preventing any multi-threaded gains (in fact measurements for Release built code show that using a single-thread yields the fastest rate of document parsing).

The contention profiler in VS now highlights StringBuilder.ToString() called from BaseTokenizer.FlushBuffer(), along with other new object creation occurring in various places.  With the idea that excessive GC could be a reason why these new object allocations could cause contention (new object allocation triggering GC often), I also looked at some perfmon .NET memory counters when running this test using 8 threads to parse 1000 documents and found:

% Time in GC : Averages around 49% with the ConditionalWeakTable and 63% without (both quite high in terms of detriment to performance)
\# Total committed Bytes: During execution is 77MB with CWT and 280MB without.

Use of the ConditionalWeakTable appears to give better memory usage at the expense of performance - this test completed more than twice as fast without CWT than with.  Also noted that there were 6 times as many (expensive) Gen2 collections when using CWT - I'm not sure of the relevance of that at this point however.

Finally, running the memory profiler with only 100 document parse calls shows over 7 million memory allocations, perhaps there are efficiencies that can be made on this front...

**Comment by comdw** [comment]
I should have mentioned above that I work with Tommy... anyway we had somewhat of a breakthrough by enabling [GC server mode](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element) in our application's app.config. 

CPU utilisation with multiple threads is now much closer to 100%.  And the performance gains are more pronounced:

(Total time taken for 8 threads parsing 1000 documents in total)
Unmodified code, Server GC disabled : 79.43 sec
Unmodified code, Server GC enabled : 33.92 sec
Modified code (no CWT), Server GC disabled : 37.30 sec
Modified code (no CWT), Server GC enabled : 9.13 sec

There is some more detail on server vs workstation GC [here](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/fundamentals#workstation_and_server_garbage_collection).  Our understanding is that Server GC is enabled by default only for specific application types like ASP.NET web sites.  The user experience should typically be better with workstation GC for the average UI/app as GC pauses are avoided, however this kind of workload gets much better overall throughput with Server GC.

**Comment by Joe118** [comment]
That's a really amazing improvement comdw!

We need to hear from FlorianRappl what scenarios he had in mind when introducing the CWT and whether these are also safe  when using a field to remember the owner.  Would the Owner property backing field still work when the DOM is mutated and a node is moved from one DOM tree to another?

**Comment by comdw** [comment]
@FlorianRappl, any thoughts on this? We've been running our forked version for a few weeks now with no issues.  I could submit a PR?

As to your question @Joe118, I believe the unit tests cover these scenarios (and all pass), though I don't have any experience with the code base as a whole and would expect this to be covered in the PR review.

**Comment by FlorianRappl** [comment]
Ho @comdw yes please make a PR. As `devel` is still blocked with 0.10 - let's just make the PR against master. 🍻

**Comment by comdw** [comment]
@FlorianRappl, just to add regarding devel branch, I also noticed unhandled exceptions from the CLR when running in debug which was down to some RequestProcessors returning null instead of a Task.  See [this commit](https://github.com/cogenta/AngleSharp/commit/d72c1c354b14e14da369657c228bd891fb1c69d9) and consider including this in devel or let me know if you want a PR for that too.

**Comment by FlorianRappl** [comment]
Where that the exception appear? I ask because `null` was returned intentionally - so other parts may break if it is not `null`. Another PR would be good, but first we need to understand the exact issue.

**Comment by comdw** [comment]
I see hundreds of them flooding the debug output window.  The problem in this case was that StyleSheetLinkRelation.LoadAsync is awaiting the Task returned by StyleSheetRequestProcessor.ProcessAsync which was null and you can't await null.  My understanding is that methods returning Task should never return null.

The exception is handled by the framework so its fairly benign, just probably shouldn't be happening at all.

**Comment by FlorianRappl** [comment]
> My understanding is that methods returning Task should never return null.

That depends. In a world where we would have strict nullable it should be the case for any object (not only tasks), but not for optionals. However, in such a case we would be hinted what would otherwise get lost.

My case here is not that `Task.FromResult(false)` (prefer boolean instead of anything else here, if you want a plain task and not some specific `T`) is wrong, but just that we need to check first if anything is dependent on the current behavior (to return `null` in the abort case). Otherwise we should go for returning a task of course.
