### ISSUE TITLE
Taking control of resource loading process

### ISSUE THREAD

**Issue by ossaltu** [AngleSharp/AngleSharp#64]
Currently AngleSharp api resource loading process is kind of automatic: you set requester object in configuration and api makes sure that all resources related to document are loaded automatically, which is great in most scenarios.
But I realized that in my case I need to control the loading process: at some point of html parsing algorithm I find that it would be good to load some css files to inspect styles of some elements, but now I do not have any convenient way to do this. 
What I need is some way to control external resource loading process, e.g. I could call LoadStyle  method on the "link" element.

**Comment by FlorianRappl** [comment]
Yes, that's definitely a good idea. I am thinking of resource loading interfaces / extension points. Right now most resource loading just uses the requester, but does everything automatically - as you found out.

In the future the fetching (and all other scenarios building upon the requester) will be done in an interface, which you can just implement and provide to AngleSharp. Unfortunately I could not make that happen for v0.8, but its definitely on the list for v0.9.

I will try to come up with a concept, especially around the scenario you are interested in. I will write down the proposal in this issue, such that we can discuss it.

**Comment by ossaltu** [comment]
Thanks for the response, I'll be looking forward for the concept.

**Comment by FlorianRappl** [comment]
So basically the new setting is to distinguish between navigation and resource requests. The former is the simple demand for new documents, while the latter represents requests to resources such as stylesheets, images, objects, ...

Instead of relying on the registration of `IRequester` objects directly, the library now looks for a particular service: `ILoaderService`. The service offers two methods:
- `CreateDocumentLoader` to create a proper document loader for navigation requests (or return `null`, if no such loader is provided)
- `CreateResourceLoader` to do the same with resources

You can write your own implementation of the `ILoaderService` or you use the `LoaderService` class from the `AngleSharp.Services.Default` namespace. The class gives you the "classic" abilities: Add some requesters to enhance AngleSharp's loading capabilities. Additionally you can disable (or enable) a particular kind (document or resource) of requests. You can also inherit from this class and override the methods. The choice is yours.

So what's so different besides the separation of request-types? Well, the request that is send to the specific loader also depends on the request type. Resource requests will not only contain basic information, such as the target URL and the origin ("referer" [sic]), but also the source element of the request. Navigation requests will contain the source node, which could be nothing (navigated directly), a document (loading request), an iframe / frame element, a form element, ...

In general this should not only provide an increased flexibility, but also be easier to maintain.
