### ISSUE TITLE
Can't seem to login when site requires __RequestVerificationToken

### ISSUE THREAD

**Issue by dotnetshadow** [AngleSharp/AngleSharp#641]
Hi there

Thanks for your library. I do have an issue where I'm trying to login to an asp.net mvc website that has __RequestVerificationToken. It seems if I disable antiforgery token I'm able to login.

So basically 
1) Request a page
2) Navigate to the login page
3) I can see the __RequestVerificationToken coookie
4) I then submit the form with username and password 
5) I get the error: Empty or invalid anti forgery header token

I'm using the ASP.NET Bolierplate. I think it submits forms using ajax is that a reason why it's not working?

**Comment by FlorianRappl** [comment]
Well, usually these pages do not require JS, so I just assume that this is not the reason.

I cannot see your configuration (please make sure to submit a MWE in order to be helpful), therefore I cannot comment, but if you, e.g., don't include cookies this cannot work (I assume you know why - so I skip anti forgery token basics).

Hope this helps!
