### ISSUE TITLE
Load HTML and wait for AJAX requests by JavaScript?

### ISSUE THREAD

**Issue by AsValeO** [AngleSharp/AngleSharp#672]
Hello!
Is there a way to load main HTML and then wait for all AJAX subrequests initiated by JavaScript to finish?

**Comment by FlorianRappl** [comment]
No direct way, but you can access the tasks (and status) of all pending requests. That way you could actually be notified when all / wanted resources are loaded.

HTH!

**Comment by JZeravik** [comment]
Hi, I really like AngelSharp, it's fast, well structured and beautiful, but there are still small issues when you want to use it as web scrapper. I'm facing the same problem as AsValeO. I have a web page with auto refreshing elements using AJAX for refresh of it's content. Can you give me an idea how I can check if AJAX elements was generated? Would be possible to get a notification/ fire event for particular html element when is changed element's innerHTML?

**Comment by FlorianRappl** [comment]
Have you had a look at mutation observers?

e.g., https://code.tutsplus.com/tutorials/html5-mastery-dom-mutations--cms-24847 or https://developer.mozilla.org/de/docs/Web/API/MutationObserver

They are implemented - maybe they cover your case.

**Comment by JZeravik** [comment]
The mutation observer looks good, I have tried to observe elements, but problem is probably somewhere else, because the element I looked for was't generated. 

The problem occurs On this page: https://www.sazka.cz/kurzove-sazky/hokej/nhl 
I'm not able to acces to element: <div id="updatableWindowsContainer" class="content">. It's not loaded via AngleSharp, but do not know why. I'm just guesing, but when tried debug the code some exeptions were thrown in EngineInstance.cs in method:

public JsValue RunScript(String source, JsValue context)
 {
       _engine.EnterExecutionContext(Lexicals, Variables, context);
       _engine.Execute(source); <---exception: {ReferenceError: Sys is not defined}
      _engine.LeaveExecutionContext();
      return _engine.GetCompletionValue();
 } 


`source= //<![CDATA[Sys.WebForms.PageRequestManager._initialize('manScript', 'form', ['tctxM',''], [],[],90,'');//]]>`
