### ISSUE TITLE
Build on VS2017

### ISSUE THREAD

**Issue by atlastodor** [AngleSharp/AngleSharp#679]
Would it make sense to convert the projects and the build script to VS2017 and .Net Standard Library instead of the deprecated PCL?

I have already branched "devel" branch locally and converted the projects to VS2017 and the cake script (otherwise it wouldn't build). It works for .Net 4.5 and the tests are green. The other platforms are compiled, but I can't say for sure if they work correctly. Also, I can't say if the cake script works on AppVeyor or compiles on non-Windows platforms. This fixes the Nuget version-hell problems. One disadvantage is that VS2017 does not support Silverlight 5 - is this still needed?

Anyways, is there interest to in integrating those changes into the branch? If so, what should I do? I am not used to working on open-source projects on Git-Hub.

**Comment by FlorianRappl** [comment]
Hi @atlastodor thanks for the request. Yes, what you describe is the ~long term~ goal (actually it was, now it should be feasible). There are reasons for the current approach (namely broadest possible compatibility, incl. .NET 4.0 and SL5), however, the downsides etc. are just too high. As a consequence what you describe is wanted (**yes**, we drop support for .NET 4.0 and SL5 and go to a higher .NET Standard than 1.0).

A PR would be appreciated (especially if its from the current `devel` snapshot). Thanks!

**Comment by tbolon** [comment]
Hi,

I have started working on migrating this project to the new csproj format & vs2017.

I just created a PR for the WIP, and would like some feedback from the mainteners of this project.

Known issues:

**some tests are failing**. Two when running using VS 2017, 126 on commandline/appveyor. Need to discover why.

**netstandard 2.0 is the minimum standard version this project can target**. This project can't can't target netstandard1.0 because HttpWebRequest is only available starting [netstandard2.0](https://apisof.net/catalog/System.Net.HttpWebRequest). The previous project was referencing the netcore nuget package which is not recommended (can cause lot of troubles for library consumers. I have targeted both netstandard2.0 and net45 so we need to decide if lower standard must be supported (by changing code to use HttpClient (available on netstandard1.1 for example).

**Need appveyor testing** I can't test an appveyor build for now. Need maintainer help.

**Comment by tbolon** [comment]
Ok found the difference: using command-line, 2 tests fails on Debug configuration, 122 on Release.

**Comment by tbolon** [comment]
Some tests are skipped on my machine, because of the network detection algorithm: "Message: No network has been detected. Test skipped."

**Comment by tbolon** [comment]
Ok, there is an issue with some tests, which requires to be ran on net462 platform. Most of the `DocumentEncodingTests` do some "magic" to detect the encoding which must be used to read the document. On .net core 2.1platform it does not work and the test falls back using UTF8 encoding, which results in tests failing. Seems related to #534

**Comment by FlorianRappl** [comment]
Encoding in .NET is unfortunately not very well done imho. Not only is the API rather bad, even worse is the implementation situation (see results here). I do not regard this as a blocker for now.

Thanks for the work - much appreciated!

We should use this and go to .NET Standard 2.0 with v0.10. It makes sense and it unblocks a lot of the issues we've faced earlier. This is the right time for the move.

**Comment by alexanderuv** [comment]
This has been addressed by #715 and #724

**Comment by FlorianRappl** [comment]
You are right @alexanderuv - thanks for the reminder! 🍺
