### ISSUE TITLE
`querySelectorAll('head link[href]')` inconsistency between Chrome and AngleSharp

### ISSUE THREAD

**Issue by kspearrin** [AngleSharp/AngleSharp#681]
The following HTML shows an inconsistency between Chrome and AngleSharp's `document.querySelectorAll` for the following website's HTML and document query:

Website HTML

https://www.k-rauta.ee/

Chrome

```
document.querySelectorAll('head link[href]')
    NodeList(7) [link, link, link, link, link, link, link]
```

AngleSharp

```
var doc = await parser.ParseAsync(html);
var links = doc.QuerySelectorAll("head link[href]");
// links.Length is only 3
```

**Comment by FlorianRappl** [comment]
Analyzing the payload I don't think it has anything to do with `QuerySelectorAll`. I think this spots a problem with the parser (to be more specific I guess the tokenizer makes a mistake here somewhere).

I would need to debug this further to get the full picture, but I am almost sure QuerySelectorAll is not the one to blame here.

**Comment by kspearrin** [comment]
@FlorianRappl Just a FYI, I am using `var parser = new HtmlParser();`

**Comment by FlorianRappl** [comment]
Actually, it turns out AngleSharp is right.

The crucial difference here is that a `noscript` element was wrongly used in the given source. If you activate scripting (thus ignoring the content of the `noscript` effectively) the result is 7.

I guess you are not affiliated with the owner of the website. Otherwise, it would be good to report such bugs (e.g., in the given case the page would be pretty much unusable if `noscript` *is* applied).

To get around your issue I recommend:

```cs
var parser = new HtmlParser(new HtmlParserOptions { IsScripting = true });
```

**Comment by kspearrin** [comment]
Thanks.
