### ISSUE TITLE
Memory leak when disposing Document objects.

### ISSUE THREAD

**Issue by jlchmura** [AngleSharp/AngleSharp#683]
In my app that opens and disposes millions of document objects, I'll start to get OutOfMemory exceptions in various places. I believe it is caused by the `ToPool()` methods in Pool.cs.  Don't we need a size check on the underlying stacks?  Otherwise they'll just continue to fill up until .NET runs out of memory (especially in a 32-bit process). 

```
Exception of type 'System.OutOfMemoryException' was thrown.
at System.Text.StringBuilder.set_Length(Int32 value)
   at AngleSharp.TextSource.Dispose()
   at AngleSharp.Dom.Document.Dispose()
... truncated ...
```

**Comment by FlorianRappl** [comment]
Good question. Usually, the pool should be reused and there are size limitations afaik. I'll look into it / improving it!

**Comment by indy-singh** [comment]
@jlchmura Can you post a reproducible example please?

**Comment by Limzz** [comment]
@jlchmura , Are you sure Anglesharp is actually causing the memory leak rather than it just being the unfortunate victim of memory leak in a different part of your application?

The StringBuilderPool is limited by the _count field and ToPool does ensure the current number of StringBuilders is less than _count before adding a new one. ToPool is the only method that adds StringBuilders to the pool and all the work is done inside of a mutex block so multithreading isn't going to cause an issue. I ran some quick tests to check these assertions and everything worked as expected.

I also used a memory profiler (https://memprofiler.com/) to try to find the object being leaked using the following test code.

```csharp
static void Main(string[] args)
{
    // perform action that is suspected to cause leak
    // do this once before the real test to make sure all Singletons are initialized and
    // don't appear in graph of newly created objects during the real test
    ParseDocuments();

    // pause program here - save the curent state of the profiler as a baseline - this forces the GC to run
    Console.WriteLine();

    // perform action that is suspected to cause leak again
    ParseDocuments();

    // pause program here - save the current state of the profiler to see the test results - this forces the GC to run
    // any objects with a memory leak should still exist because we just ran the GC
    Console.WriteLine();
}

// parse a large html document 400 times and save the results in a list as we go
// then dispose of all 400 IDocuments in a loop and clear the list
// everything created in this method should be garbage collected assuming no memory leaks
static void ParseDocuments()
{
    // input.html includes all the html from https://en.wikipedia.org/wiki/C_Sharp_(programming_language)
    string document = File.ReadAllText(@"~\input.html");
    var parser = new HtmlParser();
    var doms = new List<IDocument>();
    for (int i = 0; i < 400; i++)
    {
        var dom = parser.Parse(document);
        doms.Add(dom);
     }
     foreach (var dom in doms)
     {
         dom.Dispose();
     }
    doms.Clear();
}
```

When examining the profile I didn't see any AngleSharp objects that weren't garbage collected.

This bug report could be an edge case that only presents itself on certain input, but I think we need a reproducible example to determine if this bug is valid.

**Comment by FlorianRappl** [comment]
I'll close this one due to inactivity.

If a reproducible test comes out or someone finds something to improve feel free to bump the issue. 👀
