### ISSUE TITLE
How get access to the CSSOM?

### ISSUE THREAD

**Issue by alexanderuv** [AngleSharp/AngleSharp#686]
Hi
I am loving this project so far! I'm trying to get information about the CSSOM for a parsed document and I'm wondering how do I even get to it? I couldn't find any documentation related to it.

**Comment by FlorianRappl** [comment]
Hi @alexanderuv thanks for the question - the CSSOM is pretty much divided into the following areas:

- `Style` property for inline styles
- On `link` and `style` DOM elements via `Sheet` property
- To get the computed style via the window (`getComputedStyle`)

Hope that helps!

Remark: The CSSOM is not very extensive and should vastly improve once the new release incl. AngleSharp.Css is out. Unfortunately, I did not have much time "recently", which is why this is postponed indefinitely... The implementation of `getComputedStyle` is "pragmatic" / "experimental", i.e., very simple.
