### ISSUE TITLE
NOSCRIPT tags being pulled into document head

### ISSUE THREAD

**Issue by jordankasper11** [AngleSharp/AngleSharp#694]
If you execute the following command:

`new HtmlParser().Parse("<noscript><img /></noscript>").DocumentElement.OuterHtml`

You will receive the following output:

`<html><head><noscript></noscript></head><body><img></body></html>`

As you can see from this trivial example, the noscript tag is no longer wrapping the img tag but has instead been moved to the head. I am currently working on a project that requires me to process all img tags that are not descendants of a noscript tag and this is preventing me from querying correctly.

According to the [W3 specifications](https://www.w3.org/TR/2011/WD-html5-author-20110809/the-noscript-element.html), noscript is valid inside the body tag.

Thanks for any help you can provide!

**Comment by FlorianRappl** [comment]
This is all according to specification.

1. You are evaluating with noscript mode (i.e., there is no scripting engine, so the content of noscript is not raw, but will also be included in the DOM tree)
2. You lack a body - as you already noted `noscript` is valid in the `body` - but did you know that it is also valid in the `head`? As its your first node it will be placed in the `head`.

Alright so when we have 2 and know 1 we can conclude that the behavior is right (otherwise the image would not be shown; `img` is not valid in `head`).

You can check this behavior with your favorite browser.

I guess what you want instead is to set some options to be in script mode:

```cs
var parser = new HtmlParser(new HtmlParserOptions { IsScripting = true });
```

In this mode the content of `noscript` is raw and thus `img` won't leak.

HTH!

**Comment by jordankasper11** [comment]
Hi Florian,

Thank you for the quick response! However, I'm still running into issues with this. I created the following sample test:

```
[TestMethod]
public void NoScriptTest()
{
    var options = new HtmlParserOptions() { IsScripting = true };
    var htmlParser = new HtmlParser(options);
    var output = htmlParser.Parse("<noscript><img /></noscript>").DocumentElement.OuterHtml;
}
```

When I run this, I get the following value for output:

`<html><head><noscript><img /></noscript></head><body></body></html>`

While the img tag no remains inside noscript, it should not be in the head, as you noted earlier it is not valid there. However, if I modify my input to wrap it in html and body tags, it stays in the correct place.

Is AngleSharp only intended to process an entire document or should it be possible for me to do this with a fragment as well?

Thanks for your help!

**Comment by FlorianRappl** [comment]
AngleSharp follows the HTML5 specification - thus your question is not related to AngleSharp, but rather to HTML.

What you need to understand, is that in the mode that you give now (scripting) `noscript` has no effect on the content. Thus you do not have an `img` element in the head, you have just raw text inside. This is not processed (e.g., you cannot query select `head img`). The output you receive is only a representation (a serialization). If you look in the structure you would see that the `noscript` element has only a text node child - with text content `<img />`. That this is text you can btw already see (if it would be a real `img` element it would be represented as `<img>`).

So this is the correct place.

Everything here is happening according to the spec and as any browser would process it.

Finally, you want to know about a fragment mode - yes AngleSharp can do that. `ParseFragment` will help you (e.g., in a `body`). but why not just write then prepend `<body>`?
