### ISSUE TITLE
AngleSharp destroyes non-html-tags

### ISSUE THREAD

**Issue by MartinDemberger** [AngleSharp/AngleSharp#695]
In my application I use AngelSharp to normalize all sorts of html-Texts. The application uses additional tags which aren't html.

When I use the HtmlParser it mixes this tags.

My input is:
`<html><body><TextComplement MarkLbl="51" Kind="Owner"><ComplCaption><p /></ComplCaption><ComplBody><p>in Beton dauerhaft befestigt</p></ComplBody><ComplTail><p>.</p></ComplTail></TextComplement></body></html>`
which is mixed up to
`<html><head /><body><textcomplement marklbl="51" kind="Owner"><complcaption><p><complbody /></p><p>in Beton dauerhaft befestigt</p><compltail><p>.</p></compltail></complcaption></textcomplement></body></html>`
As you can see the complbody is now inside complcaption.

I create the HtmlParser with
`new HtmlParser(Configuration.Default.WithDefaultLoader().WithCss().WithLocaleBasedEncoding());`

**Comment by FlorianRappl** [comment]
This has nothing to do with AngleSharp. Have you tried running your example in a browser? Its the same behavior.

The issue is that you insert `<p />`. According to the HTMl spec you cannot have self-closed paragraphs.

Change the source to:

```html
<html><body><TextComplement MarkLbl="51" Kind="Owner"><ComplCaption><p></p></ComplCaption><ComplBody><p>in Beton dauerhaft befestigt</p></ComplBody><ComplTail><p>.</p></ComplTail></TextComplement></body></html>
```

I think this is what you want. If you cannot control the source maybe you should switch to XML parsing instead of HTML.

HTH!
