### ISSUE TITLE
Form SubmitAsync() sends Expect: 100-continue header

### ISSUE THREAD

**Issue by tmldsousa** [AngleSharp/AngleSharp#700]
HttpWebRequest sends Expect header by default when the request is a POST.

There is a way of disabling this behavior, by setting:
``` csharp
var req = (HttpWebRequest) WebRequest.Create(...);
req.ServicePoint.Expect100Continue = false;
```

There are other options to do this globally (the only one that worked for me was using web.config), but this isn't a good option for me.

Is it possible to override this behavior in AngleSharp? Something like:
``` csharp
var requester = new HttpRequester();
requester.Expect100Continue = false;
var config = Configuration.Default.WithDefaultLoader(requesters: new[] { requester });
```

**Comment by FlorianRappl** [comment]
Yes, what you outline can be done. The `DefaultHttpRequester` can be manipulated a bit, but I don't think to the level you want.

I see three options:

1. Make a proposal (and please submit a PR) for a better configuration of the default HTTP requester.
2. Just copy the code of the default HTTP requester and instantiate that one in your code with your desired settings.
3. Use the requester from `AngleSharp.Io`, which is actually more modern and should not come with such quirks (otherwise, please file an issue in that repo).

Thanks!

HTH!
