### ISSUE TITLE
IndexOutOfRangeException at AngleSharp.Url.ParseScheme

### ISSUE THREAD

**Issue by Gordory** [AngleSharp/AngleSharp#711]
Hi there.
I'm using your tools to parse html files to find some hrefs and found very strange bug (getting OutOfRangeException at one of random internet pages (this: view-source:http://www.salongusar.ru/ ).

I've tried to find what's wrong and found this case:
`<html> <base href="http://some.domain.com"> <img src="http:"> </html>`

You've got something strange at this point inside your code (red-marked):
![image](https://user-images.githubusercontent.com/6717523/45864589-a6787b00-bda4-11e8-883c-8d1ae0865f87.png)

Exception throws only when `<base href>` url and `<img src>` url have the same scheme.
I have no Exception when I tryed remove `base` tag or schemes are different or I use `<a href>` instead of `<img src>`. 

I'm sorry, but I can't fix this myself, it's hard to understand why this working that way.
Maybe if you explain this behaviour to me, I'll try to fix it and make a pull request.

**Comment by FlorianRappl** [comment]
Thanks for reporting this issue and the effort to pin it down. Your case indeed seems to hit an edge case that needs to be handled better.

My gut feeling is to not even go into this case if we are already at the end of the URL - I consider this an invalid URL. I will need to investigate and come back on this one.

In the meantime if you want to get into URL parsing please see the [WHATWG Spec](https://url.spec.whatwg.org). Please note that this is a living document, it advanced since the time of implementation (nevertheless, most parts are still 100% the same).

**Comment by Gordory** [comment]
Thanks! I'll read this when I go back to that question at the start of next week.
I'll be grateful if you will check this bug and explain to me how this works later :)
