### ISSUE TITLE
Can AngleSharp minify html output of a document?

### ISSUE THREAD

**Issue by radud** [AngleSharp/AngleSharp#745]
Is it possible to use AngleSharp and minify the HTML output of a document?
After building the document I return:   return document.DocumentElement.OuterHtml;
It would be great if I would be able to return a minifyed version to avoid the usage of another tool. 

Many thanks,
Radu

**Comment by FlorianRappl** [comment]
Yes it is possible.

Right now no such formatter (i.e., serializer) exists afaik, but writing one should be straight forward. Maybe I have time this weekend to show you the code here (I think it would be pretty much the standard formatter except dropping quotes of attributes if possible, reducing a standard whitespace at most instead of multiple (other) whitespace symbols and using optimized closing rules (e.g., no need to close p, button, ... in certain contexts).

What you would return is `document.ToHtml(yourFormatter)`, where `yourFormatter` would point to an instance of the minification provider. You could also try the existing formatters already.

**Comment by FlorianRappl** [comment]
Landed in `devel`.

**Comment by jfoshee** [comment]
For other travelers, what @FlorianRappl is referring to is `AngleSharp.Html.MinifyMarkupFormatter`
