### ISSUE TITLE
AngleSharp 0.10.1 no longer works with LinqPad

### ISSUE THREAD

**Issue by alexholy** [AngleSharp/AngleSharp#751]
I have been using AngleSharp with LinqPad in the past, however this no longer seems to work with 0.10.1

I have rebuild the script, I've cleared and then manually cleared LinqPads local NuGet cache - but the problem stays. Even the most simple one-liner throws an exception:

void Main()
{
   var parser = new HtmlParser();
}

fails with "The type initializer for 'AngleSharp.Configuration' threw an exception."

The inner exception Message is "Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

LinqPad version is most recent, which is v5.36.03(Any CPU)

**Comment by FlorianRappl** [comment]
Problem right now (with v0.10.1) is that the .NET FX release has a peer dep on the encoding codepages (this is not the case with .NET Core).

So in order to fix the issue you will also need to install one more NuGet package - `System.Text.Encoding.CodePages` (see #750, #746, #740).

Hope this helps and sorry for the inconvenience!

**Comment by alexholy** [comment]
Thank you so much!! (and thanks for the great AngleSharp package!)
