### ISSUE TITLE
Ability to get index of an element inside the source code

### ISSUE THREAD

**Issue by selman92** [AngleSharp/AngleSharp#754]
In **HtmlAgilityPack** it is possible to get start index of an element in the source code. Although it's stored in the private fields but still usable.

I could not find anything that corresponds to this in AngleSharp. There is an `Index` method in `NodeExtensions` but it's not what I'm looking for. I need the start index of the element in the source code, not in the parent collection. Is there any chance this support can be added?

**Comment by FlorianRappl** [comment]
I'm not sure what the index in the source code should refer to (my guess is that you refer to the starting text position of an element in the original source stream).

There are many indices we can talk about here, e.g., the index of a node in the child nodes collection, the index of an element in the child elements, the index of a text node among all other text nodes, etc.

Any kind of HTML + expected behavior using this HTML would be appreciated.

(if my assumption above is correct there is no way to get this information directly; you could get it via the tokenizer, but then you are working on the decoded stream already, not the raw bytes.)

**Comment by selman92** [comment]
Your assumption is correct, I meant the starting position of the element in the HTML source code:

Example:
`<html><p>some paragraph</p></html>`

`p.StartIndex` should be 6.

This is a very useful feature we use in HtmlAgilityPack, we are thinking of porting existing code to use AngleSharp, but there are some missing features, this is one of them.

**Comment by lvkins** [comment]
+1.  I miss this feature from HtmlAgilityPack. Sadly, there is currently no way to get the stream distance between two elements (how far (character count) is one element from another).

I will be watching for this feature.

**Comment by FlorianRappl** [comment]
This landed in `devel`. Excerpt from the documentation:

---

By default AngleSharp will throw away the "tokens" that associate the element with a position in the source code. This is mostly done due to the required memory consumption. The tag tokens transport not only the position, but also some additional fields like the name, flags and other meta information, as well as attributes. These tokens, however, can be preserved.

Currently, there are two ways to do this (both accessible via the `HtmlParserOptions`).

1. For one-time scenarios during parsing the `OnCreated` callback can be used. The first argument is the `IElement` instance. The second argument received by the callback is a `TextPosition` value.
2. For retrieval at a later point in time the `IsKeepingSourceReferences` option could be set to `true`. This way the `SourceReference` property of all parser-created `IElement` instances will be non-null. Currently, the referenced `ISourceReference` only contains a `Position` property.

In code for option 1 this looks as follows:

```cs
var bodyPos = TextPosition.Empty;
var parser = new HtmlParser(new HtmlParserOptions
{
    OnCreated = (IElement element, TextPosition position) =>
    {
        if (element.TagName == "BODY")
        {
            bodyPos = position;
        }
    },
});
var document = parser.ParseDocument("<!doctype html><body>");
```

The code for option 2 looks as follows:

```cs
var parser = new HtmlParser(new HtmlParserOptions
{
    IsKeepingSourceReferences = true,
});
var document = parser.ParseDocument("<!doctype html><body>");
var bodyPos = document.Body.SourceReference.Position;
```

In both cases the position we care about will be stored in `bodyPos`.

**Remark**: As `SourceReference` may be empty (e.g., when we omit the provided option or if we select an element that came in *after* parsing) we advise of using `SourceReference?.Position`, where we would end up with a `Nullable<TextPosition>`. Ideally, we then just use `TextPosition.Empty` as the fallback, e.g., in the code above:

```cs
var bodyPos = document.Body.SourceReference?.Position ?? TextPosition.Empty;
```

---

Hope this helps!

**Comment by fedesasso** [comment]
Sorry to chime in three years later, but could I request to implement it also for other node types?
SourceReference is available only for Elements, but it would be very useful to get source coordinates for other nodes as well like comments, text nodes, and so on (btw, HAP does it).
If keeping the whole HtmlTagToken is too much a burden on the memory footprint, you could simply sport a nullable INode.TextPosition attribute.

**Comment by FlorianRappl** [comment]
> If keeping the whole HtmlTagToken is too much a burden on the memory footprint, you could simply sport a nullable INode.TextPosition attribute.

Hm - that's not how memory works. These positions are anyway structs (and usually ~8 bytes as we have two 16 bit length fields and a single 32 bit field). 8 bytes - or 64 bit - is also the size of a pointer on 64 bit systems - so a nullable attribute would consume the 64 bit already. The size of an object is not determined by what is contains, but how its model looks like.

> Sorry to chime in three years later, but could I request to implement it also for other node types?

Yes you can - but this would definitely require either an external contribution or a sponsorship to support development.

**Comment by schaakverslaafd** [comment]
Thx for the awesome library!
I am also interested in source coordinates of text nodes. And I was wondering if there might be an 'easy solution' for this.
Would it be an option to raise an event like OnCreated for consumed tokens?
(If appreciated I would like to provide a pull request for this.)

**Comment by FlorianRappl** [comment]
Let's discuss this. Ideas from my side:

- Evaluate how much perf hit we get if we'd make this consistent (i.e., `SourceReference` on `INode`, specifically for text nodes)
- Evaluate how much perf hit we'd get for an optional `OnToken` event raised by the DOM builder upon consumption
- Evaluate how feasible it would be to "store" / "retain" the tokens; this way allowing something like "get position of this token in the token chain" for "grabbing the succeeding text token" would be possible

Thoughts?

**Comment by schaakverslaafd** [comment]
Ok!

In my case I would also like to get the end position of the token / textnode. And I think that would be more of a hassle when all `INodes` have a `sourceReference` with only a start position. That's why I did not look into the performance hit for the first point.

So I tried to measure the performance hit of an optional OnToken event. I would not expect much impact of a null check (when OnToken is not provided). However when I ran the benchmarks the deviation between runs was quite large, so I could not really confirm this. I added a pullrequest with the code I used for the test.

Regarding the last question. I think it's possible to store / retain the token from the OnToken event? Is that what you meant?

**Comment by FlorianRappl** [comment]
> I think it's possible to store / retain the token from the OnToken event? Is that what you meant?

Well, surely it's "possible" - the question is how much perf. impact that has. So if those tokens are just kept (if opt-in) in a store or list then retrieving a token's index and getting the adjacent nodes or something else would be possible, too. But that means we'd need to have this kind of structure (could be as simple as a list) and store the tokens there instead of throwing them away.
