### ISSUE TITLE
Feature request: Extendable AngleSharp.Html.Parser.HtmlTokenizer

### ISSUE THREAD

**Issue by hyspace** [AngleSharp/AngleSharp#803]
### Description

Current `HtmlTokenizer` is a sealed Class:

```cs
sealed class HtmlTokenizer : BaseTokenizer
```

I need to modify some states to add support for [conditional comment](https://www.quirksmode.org/css/condcom.html) for my own usage.

Today I need to have a full copy of `HtmlTokenizer` since I can not extend it.

Would you mind removing the `sealed` modifier so that it is extendable?

**Comment by FlorianRappl** [comment]
The only thing we can think about is an interface for the tokenizer (`IHtmlTokenizer`), which is then used as a service (it will pretty much have just a single method - to obtain the next token). Then you could write a wrapper tokenizer which checks for the conditional comment and otherwise grabs the next token from the official tokenizer.

Like many others this class is `internal` and `sealed` on purpose (the `sealed` should not be the big blocker here; you cannot access the class anyway right now - and even if you could - no method can be overwritten ...). There is no wanted / desired extensibility here as giving meaningful broad use cases without much impact on standard use cases is quite impossible.

**Comment by hyspace** [comment]
Got it.

`IHtmlTokenizer` is not helping here. the logic need to be inside the state machine. I will give up using public package.

**Comment by hyspace** [comment]
Reopening this issue for some help.
As I explained, I have to do some change on Tokenizer layer and the change can not be done on upper layer - the conditional comment need to change the parsing state back to `data state`. But I really want to avoid having a fork of AngleSharp.

I think this type of need is quite common. Today there are millions of machines running outdated system and there are practical need to support them. Instead of making `HtmlTokenizer` public, do you have any idea how can we give developer the ability to do some change on Tokenizer layer?

**Comment by FlorianRappl** [comment]
As explained there is no chance of doing so (even if we would "open" it up - despite all performance concerns - the complexity inside is way too high to have *any* useful impact).

One chance I see (and this happened in the past) is to add some option to the `HtmlParser`, which is then used by the `HtmlTokenizer` to trigger a new mode, i.e., bringing in some (optional) branches / mode which can be unlocked via an opt-in from the outside.

In this scenario I think another option called `IeCompatibility` with some `enum` `IeCompatibilityMode` that contains values such as `None`, `Ie6`, `Ie7`, ...`Ie9` could make sense.

Besides this way the other way I think could be viable would be an extension to the comments creation (similar to `meta` element hooks). I think what would be needed here is to essentially parse the document fully, then walk over all comment nodes which have a specific shape (essentially evaluating the conditional comments or ignoring them if parsing fails / or is not fulfilled), extract the body of the conditional comment and perform a fragment parsing with the context being the parent. This way could already work today / you could do that *after* the full parse (which - if it works - could then be also done *during* parsing).

**Comment by hyspace** [comment]
I don't quite understand the *high complexity* you are talking about here. Yes, making change on Tokenizer layer is dangerous and complex, but I'm asking here means I understand its complexity. Before I found AngleSharp I have implemented a full tokenizer to help me understand the spec. For AngleSharp, I don't see any harm for the project to "open" it. AngleSharp should keep focusing on providing what living standard have, and the developer who need to use a highly "customized" AngleSharp, like me, is responsible to deal with the complexity inside Tokenizer themselves.

`IeCompatibility` is not only about `conditional comment`. I did not suggest to use anything like `IeCompatibility`, since it is a big hole and IE is not open-sourced. It is something that should not appear on the road map of AngleSharp,  so I have not even considered to contribute those code back to AngleSharp. Beside that, `conditional comment` is not only for IE, it is also used in Word, Excel and other windows or office component.

Something like meta element hooks is not going to work here. Trust me, it is only possible to be done within the state machine. After the source string inside the comment is converted to text in the comment token, information will be lost.
Consider this input:
```html
<!--[if ie]>
&lt;p&gt;
<[endif]-->
```
after the comment token is built, the text in token will be:
```
[if ie]>
<p>
<[endif]
```
Is the `<p>` coming from `&lt;p&gt;` or it is coming from `<p>`? or even `<p&gt;`? There is no way to know, unless we use the `Position` and we re-parse from the source. However, what it is coming from is so important: if it is coming from `<p>`, it is a part of HTML Tag, but if it is coming from `&lt;p&gt;` it is just a piece of text. The only way to have correct output, is to return the comment token after `>` and go back to `data state`.

What you described about fragment parsing does not apply here either.
There was a very common usage of `conditional comment` in early 2000's:
```
<div class="container">
  <!--[if ie]>
  <div class="special-container">
  <[endif]-->

    <p>Main content</p>

  <!--[if ie]>
  </div>
  <[endif]-->
</div>
```
The content inside conditional comment is part of whole document, not its parent.

**Comment by FlorianRappl** [comment]
Ok then let's short circuit the discussion here: AngleSharp is HTML5 spec conform and what you are suggesting here does not follow the spec. Therefore we will not implement it directly.

That you refuse to see the high complexity inside the tokenizer does not bring value to the table. Also just opening it would not bring any benefit to anyone right now (there is a way to get the stream of tokens - and that is about everything you could do with it right now anyway).

> AngleSharp should keep focusing on providing what living standard have, and the developer who need to use a highly "customized" AngleSharp, like me, is responsible to deal with the complexity inside Tokenizer themselves.

Please keep such comments from here. This is exactly what AngleSharp does - but sacrificing performance for *all* users just to allow *a single* (not very often taken) scenario is not what we want.

Before continuing the discussion bring a proposal on *how to* open the tokenizer (API, performance considerations, usage scenarios, ...). Right now I see no real proposal, just a pain point that you wish to solve somehow without telling *how* (I still do not understand the *why*, but that is something different - if we can solve it efficiently we will certainly go for it).

Another suggestion from my side to focus on the real topic: A hook could still work, because you can also write on the document text source (there are more options than just fragment parsing - this was one example).

**Comment by hyspace** [comment]
After I tried to come up with a proposal (PR), now I agree with you.

It is not about performance. I don't see any performance issue to make classes from `internal sealed` to `public`.

It is about design. To make it possible for me to extend `HtmlTokenizer`, not only `HtmlTokenizer`, I have to change modifier of many internal classes, including some HtmlTokens and some of the structs as well. They are all designed to be not accessible in AngleSharp. Making all of them public is a proposal to completely change this design and I don't see any potential use case other than mine.

Thanks for the patient explanation.

**Comment by FlorianRappl** [comment]
Okay, sorry to hear that. Did you try to follow:

> Another suggestion from my side to focus on the real topic: A hook could still work, because you can also write on the document text source (there are more options than just fragment parsing - this was one example).

because to me that sounds like it could work?! Or maybe I am just missing something like the fragmented input that you noted earlier...

**Comment by hyspace** [comment]
It may work, but it does not change my position here, I still need to fork the project. To make my proposal simple, I did not explain it completely. I need to skip the tree construction phase completely -- since we do not need that and it contribute to 4/5 of the run-time of parsing HTML.

(I'm aware of the complexity here, tree construction will overwrite the tokenization state in some cases.)

I'm so insist to parse `conditional comment` the way I described, is to aligned with IE behavior. Any other option sounds like a "work around". As long as I still have the option to fork the project, I will stick with it.
