### ISSUE TITLE
WithDefaultLoader(requesters: new[] { requester } giving a compiler error

### ISSUE THREAD

**Issue by Rodrobi** [AngleSharp/AngleSharp#816]
I am trying to logon to Schwab.com so (hopefully) I can scrape data off a couple pages on their site.

Every time I logon with SubmitAsync, I get “invalid User name or Password.   I know what I am passing, is correct. As result, I thought it was due to a missing header.  

When I use the following code to add the header, I get a compile error.   Can you tell me what I’m doing wrong?

    var requester = new DefaultHttpRequester();
    requester.Headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0";

    var context = BrowsingContext.New(Configuration.Default.WithDefaultLoader(requesters: new[] { requester }));
            
**Error	CS1739	The best overload for 'WithDefaultLoader' does not have a parameter named 'requesters'**

**Comment by FlorianRappl** [comment]
Which version of AngleSharp are you using? 

Since v0.10 the `requester` is not given as a requester array, but just via inclusions in the configuration. So there is no parameter called `requesters` for `WithDefaultLoader`.

```cs
var requester = new DefaultHttpRequester();
requester.Headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0";
var config = Configuration.Default.With(requester).WithDefaultLoader();
var context = BrowsingContext.New(config);
```

Hope that helps!

**Comment by FlorianRappl** [comment]
Remark regarding the "original" issue (cannot login):

Since logging in to a page requires quite often some kind of state I would also include cookies `WithCookies` in the configuration (normally this is already true for the login itself - there are mechanisms such as an anti-forgery token to prevent "plain form submission").

Of course, websites could be sensitive to the user-agent, but (if they are engineered well) usually they don't. That would also be disastrous for long-term compatibility. Hence my assumption would be that  this header is irrelevant (hopefully, I am wrong). The other possibility is that the login already depends on JavaScript. If this is the case scraping could be difficult. Yes, there is `AngleSharp.Js`, but so far its still experimental and it will not work for "complex" (i.e., real-world) JS apps. Maybe the required scripts are "simple enough" to work, but there is no guarantee.

In any case, if you still have problems logging in to the particular site - don't hesitate to follow up here or create an issue at StackOverflow. I'll look there periodically and other folks are quite active there, too.
