### ISSUE TITLE
CreateHead().InsertRowAt().InsertCellAt() is creating td than th

### ISSUE THREAD

**Issue by kernel-coder** [AngleSharp/AngleSharp#818]
I think the issues is because CreateHead() is creating HtmlTableSectionElement which is creating td even for thead than th.

**Comment by FlorianRappl** [comment]
Yes, sounds like a bug to me. Do you want to make a PR or should I take care of it?

Thanks for reporting the issue! :beers:

**Comment by campersau** [comment]
Note that browsers also insert `<td>` elements in `<thead>`. `<th>` have nothing to do with `<thead>`.

```js
document.createElement("thead").insertRow().insertCell(); // returns <td></td>
```

**Comment by kernel-coder** [comment]
@FlorianRappl  Not sure about me, probably I'll be able to give a try over weekend if that works for you. 

But what do you think about @campersau comments? He seems right, so we need to decide whetehr we should consider it as bug or not.

**Comment by FlorianRappl** [comment]
I think @campersau is definitely right. If this is the browser's behavior we should actually remove the bug flag.

Now the only question is if this issue is invalid, or if we, e.g., provide some additional logic (like a `insertHeaderCell`). We follow the spec, but we can add some things that are only there in C# / our API.

What is your thought @kernel-coder ?

**Comment by kernel-coder** [comment]
@FlorianRappl  I think there should be another method or at least an argument in InsertCellAt (e.g. isTdCell, defaulting to true) to provide creation of **_th_** tag.  This way, user will be allowed to create th tag in head/foot or body. Or any other way you think best, I believe there should be at least a way to create th cell in table.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
