### ISSUE TITLE
Cannot remove all rows from the HTML table

### ISSUE THREAD

**Issue by NiceStepUp** [AngleSharp/AngleSharp#838]
# Bug Report
Cannot remove all rows from the HTML table
## Prerequisites

I am trying to remove all rows in table. [I've read this documentation](https://anglesharp.github.io/docs/Questions.html#how-can-i-remove-all-elements-matching-a-certain-selector), however, rows are not removed.

My code looks like this:
`   public void DeleteRows(IElement table)
    {
        foreach (var row in table?.QuerySelectorAll("tr"))
        {
    	    row.Remove();
        }
        var legnthAfterDeletion = table?.QuerySelectorAll("tr")?.Length;
    }
`

- [ ] Are you running the latest version of AngleSharp?
      Version=0.13.0.0

For more information, see the `CONTRIBUTING` guide.

## Description

Rows are not removed from the HTML table.

## Steps to Reproduce

```cs
    public void DeleteRows(IElement table)
    {
        foreach (var row in table?.QuerySelectorAll("tr"))
        {
    	    row.Remove();
        }
        var legnthAfterDeletion = table?.QuerySelectorAll("tr")?.Length;
    }
```

**Expected behavior:** 
I expect that all rows will be deleted

**Actual behavior:** 
Rows are not deleted

**Comment by FlorianRappl** [comment]
I'm not sure if its a bug - I rather think its a misconception of the iterator.

Your code is equivalent to

```cs
for (var i = 0; i < table.ChildElementCount; i++)
{
  table.Children[i].Remove();
}
```

This is the old problem why you should not forward iterate, but rather backwards (you'll modify the list, i.e., you'll skip every second one).

To solve this in the standard loop:

```cs
for (var i = table.ChildElementCount - 1; i >= 0; i--)
{
  table.Children[i].Remove();
}
```

So I think if you'll run the following code it should work:

```cs
    public void DeleteRows(IElement table)
    {
        var rows = table?.QuerySelectorAll("tr").ToArray();
        foreach (var row in rows)
        {
    	    row.Remove();
        }
        var legnthAfterDeletion = table?.QuerySelectorAll("tr")?.Length;
    }
```

Instead of taking the "live" view (with the underlying iterator) we take a snapshot and iterate over this one.

Hope that helps!

**Comment by NiceStepUp** [comment]
Yeah, you right, it is not a bug! It works now! I am sorry for so silly mistake! Thank you very much! :)
