### ISSUE TITLE
Get PDF after submit a form

### ISSUE THREAD

**Issue by mariohik** [AngleSharp/AngleSharp#843]
Hello,

I'm using AngleSharp to submit various forms and, on the last one, I'm receiving a PDF ("application/octet-stream") on the document.

```cs
var document = await form.SubmitAsync();
```

How I can access this PDF? Maybe a ByteArray or a Stream?

**Comment by FlorianRappl** [comment]
Actually I think `AngleSharp.Io` may be helpful here (https://github.com/AngleSharp/AngleSharp.Io). You can configure it to be notified when certain mime types are found. Then you can, e.g., store them somewhere.

There is also a `DownloadAsync` extension method for URL containing elements (such as `<a>` elements).

The other option that I see is to use `GetSubmission` instead of  `SubmitAsync`. It will just give you a `DocumentRequest`. That you can directly use in an `IDocumentLoader` (such as the `DefaultDocumentLoader`) to get the `IDownload` with the `IResponse`.

Hope that helps, otherwise I'll craft a small example.

**Comment by mariohik** [comment]
@FlorianRappl Thank you!

To help others in the future, I'm posting my solution for this problem:

```cs
var request = form.GetSubmission();
var ddl = new DefaultDocumentLoader(context);
var response = await ddl.FetchAsync(request).Task;
return File(((System.IO.MemoryStream)((AngleSharp.Io.DefaultResponse)response).Content).ToArray(), "application/pdf");
```
