### ISSUE TITLE
How to download a additional file?

### ISSUE THREAD

**Issue by jogibear9988** [AngleSharp/AngleSharp#866]
# Bug Report

I tried the following Code from here: https://anglesharp.github.io/docs/Questions.html#how-to-download-a-picture

            var download = context.GetService<IDocumentLoader>().FetchAsync(new DocumentRequest(Url.Create(allWorkersScript.Source)));

but the file is not requested (I checked via Fiddler).

I also use: 

     .WithDefaultLoader(new LoaderOptions { IsResourceLoadingEnabled = true })

but it would be nice if this could be skipped. Cause I don't want that AngleSharp downloads anything additional automatically, but I want to use the context cause I need the Cookies.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version of AngleSharp?
- [ ] Did you check the FAQs to see if that helps you?
- [ ] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [ ] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.
## Possible Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Hm not sure where the bug is.

1. You use a document loader. Enabling the resource loader only has an impact on the `IResourceLoader`, not on the `IDocumentLoader`. So in the given scenario this is already as you wish.
2. I just tried this (which version are you using? Latest? That's at least what I used) and could download a document just as promised. Sure its, e.g., not an HTTPs problem? What's the URL you are trying to reach?
3. The question refers to downloading an arbitrary resource. Using the `IDocumentLoader` will result in a document (e.g., HTML, XML, SVG, ...) being loaded and parsed. Not sure if this is what you want. The link talks about downloading a binary like an image.

**Comment by jogibear9988** [comment]
I did it wrong...
I used a relative Url from a script, see:

            var allScript = resultCalendar.Scripts.Where(x => x.Source != null && x.Source.EndsWith("all.js")).First();
            var download = context.GetService<IDocumentLoader>().FetchAsync(new DocumentRequest(Url.Create(allScript.Source)));

I fixed it now like this:

           var download = context.GetService<IDocumentLoader>().FetchAsync(new DocumentRequest(new Url(baseUrl, allScript.Source)));

**Comment by FlorianRappl** [comment]
Alright, thanks for the heads up!
