### ISSUE TITLE
How to inject custom headers?

### ISSUE THREAD

**Issue by riddlemd** [AngleSharp/AngleSharp#883]
It would be nice to be able to send custom headers per request. Right now anything that's protected behind a jwt bearer token authorization is completely blocked from being accessed by AngleSharp without handling the requests outside the library...

Also there are tons of other uses for being able to set custom headers pre request.

**Comment by FlorianRappl** [comment]
You can do that already with a filter.

Example:

```cs
var config = Configuration.Default.WithDefaultLoader(new LoaderOptions
{
	Filter = request => {
		request.Headers.Add("x-foo-bar", "qxz");
		return true;
	}
});
var context = BrowsingContext.New(config);
var document = await context.OpenAsync("https://httpbin.org/headers");
var content = document.Body.ToHtml();
```

where `content` is

```plain
<body><pre style="word-wrap: break-word; white-space: pre-wrap;">{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "AngleSharp/0.14.0.0", 
    "X-Amzn-Trace-Id": "Root=1-5ecf610b-c47d372873116300a141e7df", 
    "X-Foo-Bar": "qxz"
  }
}
</pre></body>
```

Hope that helps!

**Comment by riddlemd** [comment]
How does that help me when I already have a context with cookies and what not? I need it on a per request level. I need to be able to read the action out of a form and submit it with custom headers like an ajax request can.

**Comment by FlorianRappl** [comment]
I am not sure I follow you. Did you see the `request` coming in? It has all the context you should need. Otherwise, just place a marker and follow up on that.

If you think a different way is possible, too then just place a proper proposal followed up by a PR.

Demanding features without contribution is not how OSS works. Sorry to disappoint.

**Comment by FlorianRappl** [comment]
Note for the AJAX request its actually super trivial. You can *always* use AngleSharp to build your own *IRequest*  instance. With that you can do whatever you want.

```cs
var form = document.QuerySelector<IHtmlFormElement>("form");
var request = form.GetSubmission();
// Change headers or whatever and submit ...
```

**Comment by riddlemd** [comment]
I'm not demanding a feature, I'm just upset at a dismissal of my suggestion by giving me a literal cookie cutter response that's not what I asked for.

Having said that, I do appreciate the work put into this project and will look into spending some time getting this feature implemented and will send a pull request.

And to clarify the request was to send different headers for an existing browser context.

**Comment by FlorianRappl** [comment]
> I'm just upset at a dismissal of my suggestion by giving me a literal cookie cutter response that's not what I asked for.

Its exactly what you asked for - sorry that you cannot see that. Did you look at the code? Especially, that you can create for a form a custom request instead of submitting. In the browser you also cannot alter the request headers. You'd need to build your own request. AngleSharp is the same, but comes with obvious conveniences on top (like `GetSubmission`).

Appreciation for projects start with starring them. If you don't sponsor projects that's fine, but at least show a minimum appreciation by starring projects that you actively use.
