### ISSUE TITLE
Can't install nuget package, because of unresolved  Microsoft.Bcl.Async (≥ 1.1.168) depedency

### ISSUE THREAD

**Issue by rufanov** [AngleSharp/AngleSharp#89]
I can't install AngleSharp NuGet package, because it has unresolved depedency - it requires Microsoft.Bcl.Async of version ≥1.1.168.

But there is no such package - https://www.nuget.org/packages/Microsoft.Bcl.Async/ - 1.0.168 is lastest.

It's mistype in nuspec?

**Comment by FlorianRappl** [comment]
Yes - its a mistype. I will fix it; sorry for the inconvenience.

**Comment by FlorianRappl** [comment]
New package is available; the typo is fixed. What was your platform? I am just curious because with the latest change any .NET >= 4.5 should get the PCL version and thus avoid the Microsoft.Bcl.Async dependency.

**Comment by rufanov** [comment]
@FlorianRappl , target framework is .NET Framework 4.5.2. No, it's always requires Microsoft.Bcl.Async, even if i change target to .NET Framework 4.5.

Also now i can't install AngleSharp package to PCL library, because of this error:

> install-package : Could not install package 'AngleSharp 0.8.4.1'. 
> You are trying to install this package into a project that targets '.NETPortable, Version=v4.0, Profile=Profile46', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by FlorianRappl** [comment]
That is strange since for me it works (tested on .NET 4.5 and .NET 4.5.2). Sure there are no caching problems? Which version of VS are you using?

The other error should have existed before. The PCL target of AngleSharp is different (profile 259). Maybe with NuGet v3 this all will improve; right now I am quite dissatisfied with the available options.

**Comment by rufanov** [comment]
@FlorianRappl,  i have Visual Studio 2015 RC and Visual Studio 2013 installed - same problem in both.  

I will try to debug package installation process to understand why this happends.

About other error - you right, my mistake. Changed profile to 295, and now it works.

**Comment by FlorianRappl** [comment]
VS 2015 RC has lots of NuGet problems (most of the problems have their origins in caching issues). I tried with VS 2013 and everything works fine.

My procedure in VS 2013 was: Open a new project (I've chosen a WPF application with .NET 4.5 and in another approach .NET 4.5.2). Go to the NuGet package manager and install AngleSharp from the official NuGet feed. I've seen no dependencies being installed. I've also checked the _packages.config_ file and the packages folder. Both only contained the AngleSharp package; no Microsoft.Bcl.Async was listed or downloaded.

If you could find out where the problem is and / or optimize the NuGet package - that would be of great help!
