### ISSUE TITLE
Trailing Slashes in HTML

### ISSUE THREAD

**Issue by bjornri** [AngleSharp/AngleSharp#899]
Hi!

When using AngleSharp in one of my projects I noticed the following behavior.

A client is sending "bad" HTML to our system, which looks like this:
``` html
<p>Hi!<br\ />Lorem ipsum blablabla...</p>
```

When parsing this with AngleSharp, the <br\ /> elements are treated as a start tag which causes our program to process it incorrectly. 

I made a small example program to illustrate this behavior:

``` c#
static void Main(string[] args)
{
  var html = "<html><head></head><body><span>Line 1<br\\ />Line 2</span></body></html>";
  var parser = new HtmlParser(new HtmlParserOptions(),
    BrowsingContext.New(new AngleSharp.Configuration()));
  var parsedDocument = parser.ParseDocument(html);

  Console.WriteLine("Original:");
  Console.WriteLine(html);
  Console.WriteLine("Parsed:");
  Console.WriteLine(parsedDocument.ToHtml());

  Console.ReadLine();
}
```

This prints:
``` html
Original:
<html><head></head><body><span>Line 1<br\ />Line 2</span></body></html>
Parsed:
<html><head></head><body><span>Line 1<br\>Line 2</br\></span></body></html>
```

I'd expect it to print:
``` html
<html><head></head><body><span>Line 1<br\ />Line 2</span></body></html>
```

As a final note, everything works as expected when we receive HTML tags that doesn't contain a backslash character.
Maybe we're doing something wrong - any input is appreciated.

**Comment by FlorianRappl** [comment]
This is all fine.

![image](https://user-images.githubusercontent.com/1766191/92384926-40ac6780-f111-11ea-9199-e9548bbe81fd.png)

I used the following code:

```html
<!DOCTYPE html>
<html>

<body>
<p>Hi!<br\ />Lorem ipsum blablabla...</p>
</body>

</html>
```

Please look into the representation of a real browser first.

AngleSharp does HTML5 parsing by the spec, and a tag `br\` is *not* the same as the special tag `br`. Thus its handled like a generic tag, which is just opened here and auto-closed via the closing paragraph.

Hope that helps!

**Remark**: Its the fault of the client, not your or AngleSharp's fault. This client would also be interpreted "wrongly" (from the point of view that `br` was originally meant, otherwise its all fine, of course) in the browser.

**Note**: There are no self-closing tags (`<foo />`) in HTML. There are a couple of elements such as `img` or `meta` which "accept" this XML notation, but even these should be used without trailing slashes as per-spec recommendation.

Even `<div />Foo` would yield `<div>Foo`. Trailing slashes are just ignored (with exceptions) as per spec.
