### ISSUE TITLE
Parser error with &_ in attribute

### ISSUE THREAD

**Issue by lanwin** [AngleSharp/AngleSharp#902]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

## Description

We got an html snippted copied from facebook which included a link witch contained an href url with `&__tn__` and which produces a parser error while the browser succeed with it. 

## Steps to Reproduce

Stripped down example:
```
new HtmlParser(new HtmlParserOptions
        {
            IsScripting = false,
            IsStrictMode = true,
            IsEmbedded = false
        }).ParseDocument("<!DOCTYPE html><a href=\"https://test.de/?foo&_\"></a>");
```

From my Tests the tricky part is only the `&_`

**Expected behavior:** [What you expected to happen]

Parse succeed 

**Actual behavior:** [What actually happened]

AngleSharp.Html.Parser.HtmlParseException: 'Error while parsing the provided HTML document.'

**Environment details:** 

AngleSharp: 0.14.0
Dotnet Core 2.1 Windows/Linux

**Comment by FlorianRappl** [comment]
Hi @lanwin thanks a lot!

Definitely looks like a bug to me. I'd be able to take care of it soon (e.g., early next week) unless somebody else wants to try it? Any help appreciated!

**Comment by FlorianRappl** [comment]
Actually, looking now at it I see that you activated `IsStrictMode`.

~~Since the given construct is actually an error, what else do you expect? Strict mode will throw in case of HTML errors. If you want errors to be silent (like browsers) then either do nothing (default) or set `IsStrictMode` to `false`.~~

Sorry I did not notice in the first place (i.e., I was confused by your comparison with browsers).

**Update**: Sorry, that was premature. Actually, this should not be an error. While we consume char references in attribute values, we should be rather lax here and never treat unterminated references are errors.

Fixed, and pushed to `develop`. Preview version released.

**Comment by FlorianRappl** [comment]
Please check using a tool of your choice, e.g., https://validator.w3.org/nu/#textarea

![image](https://user-images.githubusercontent.com/1766191/93940993-d1985b00-fd2d-11ea-8e9a-281d0020dfe5.png)
