### ISSUE TITLE
Where is HttpRequester?

### ISSUE THREAD

**Issue by Gavin-Williams** [AngleSharp/AngleSharp#908]
Hi,

I'm looking at the example code here: https://github.com/AngleSharp/AngleSharp/issues/718

I'm trying to look for elements on a dynamic page (with js) which contains a table of data, that the basic OpenAsync doesn't open.

But I don't see HttpRequester which is used in issue 718, VS can't find the package to add, I've searched github, there is nothing. I've got the following packages already...

AngleSharp
AngleSharp.Css
AngleSharp.Io
AngleSharpJs

Where is it?

**Comment by FlorianRappl** [comment]
Do you mean the `HttpClientRequester`? The original `HttpRequester` was renamed to `DefaultHttpRequester`. You don't need to add it explicitly though - its added internally anyway for you (when you use `WithDefaultLoader`).

Our recommendation is to use `AngleSharp.Io` with the `HttpClientRequester`. It uses `HttpClient` underneath, which has a better architecture / implementation than the classic `HttpWebRequest`.

Hope that helps!

**Comment by Gavin-Williams** [comment]
The page I'm trying to read is : https://www2.asx.com.au/markets/trade-our-cash-market/directory

I'm just trying to get the table data out, we've gotten it out with some very simple python code. But I just can't work out how to use AngleSharp.

Here's what I've got...

```cs
        private async void Button_ScrapeMC_Click(object sender, RoutedEventArgs e)
        {
            // source page
            string address = "https://www2.asx.com.au/markets/trade-our-cash-market/directory";
            
            // construct context and use default configuration
            IConfiguration config = Configuration.Default
                .WithDefaultLoader()
                .WithJs();
            IBrowsingContext context = BrowsingContext.New(config);

            // open document
            var document = await context.OpenAsync(address); // 1077 elements

            // dump document info
            Debug.WriteLine("Address = " + document.Origin.ToString());
            Debug.WriteLine("Element Count = " + document.All.Length);

            // define selector
            string s;
            s = "th";

            // get list of elements in document that match the selector (or selector group)
            IHtmlCollection<IElement> elements = document.QuerySelectorAll(s);

            // get the text
            IEnumerable<string> elementsText = elements.Select(m => m.TextContent);

            // debug dump
            Debug.WriteLine("MatchedElements = " + elements.Length.ToString());
            foreach (string text in elementsText)
                Debug.WriteLine(text);

            Debug.WriteLine("DONE");
        }
```
Output:

Address = https://www2.asx.com.au
Element Count = 1077
MatchedElements = 0
DONE

I must be missing something, because I just don't see the table data at all.

Any help is appreciated. I've been trying to solve this for a couple of days now with just no luck.

**Comment by FlorianRappl** [comment]
The page itself has no table. The table comes via JS.

AngleSharp.Js (its a different project / repository) is experimental and presumably does not work on the given page.

**Comment by Gavin-Williams** [comment]
Ah, OK. 

I hear about headless browsers; could I look at Microsoft's Chromium Webdriver or Selenium to completely evaluate the page or do you have any other recommendation for a way to do this (.net standard)?

And is it because that page is non-standard? Just so I understand why it doesn't work.

Also, is there a way to use another tool to get the full source and then pass that to AngleSharp for querying?

**Comment by FlorianRappl** [comment]
> And is it because that page is non-standard?

This has nothing to do with the page. As stated the thing you want is dynamically generated using JS (with a BE request). AngleSharp.Js is limited what it can do. Partially due to the Jint (the JS interpreter), partially, because it is not 100% connected to the DOM / AngleSharp does not expose all APIs required by more sophisticated web apps (e.g., some will try to use APIs exposed by the rendering engine, which is not given in AngleSharp.Core).

> Also, is there a way to use another tool to get the full source and then pass that to AngleSharp for querying?

That would not be very helpful as this other tool would need at least the same capabilities + full JS support; sounds like just using this tool then is what you want.

> I hear about headless browsers [...]  any other recommendation for a way to do this

There are two direct ways:

1. Why scrap the page anyway if all you want is in that table? This data you get *much* cheaper via a request to https://asx.api.markitdigital.com/asx-research/1.0/companies/directory?page=0&itemsPerPage=25&order=ascending&orderBy=companyName&includeFilterOptions=false&recentListingsOnly=false
2. Use the browser of your system (could be Chrome running in a Docker image) and automate it using the WebDriver protocol (WDP). Selenium is an option, too, but I'd always go for something more lightweight such as the WDP.

**Comment by Gavin-Williams** [comment]
Ahm, that's amazing (fetching that table data like that). I'm very new to this stuff so there's a lot I'm not even aware of. I'm sorry to ask more, but how did you construct that request link in option 1? 

What should I read up on so that I can understand what you just did?

**Comment by FlorianRappl** [comment]
> how did you construct that request link in option 1?

All I did was going to the website, open my browser debugging tools (in Chrome / Windows via CTRL+SHIFT+I, otherwise just right click and inspect element) and go to the network tab. Then I'll see all the requests that are made. If there is JS involved, high-chance its just pulling some data and displaying that.

The only reason for using browser automation for such scenarios is that the request requires a complicated interaction flow, which is based on information sent with the HTML. An example for that are login pages of e.g. Microsoft or Google. They have quite some security in place and just making a POST request will not get you the cookie you'd like. Here, the page needs to be evaluated and the form needs to be submitted properly.

> What should I read up on so that I can understand what you just did?

Hm, not sure if there is one resource to learn about that. Maybe these two links are helpful:

- https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools
- https://developers.google.com/web/tools/chrome-devtools/network

Hope that helps!

**Comment by Gavin-Williams** [comment]
Yes, thank you.
