### ISSUE TITLE
Accept header never changes

### ISSUE THREAD

**Issue by aidilumarov** [AngleSharp/AngleSharp#935]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

Accept header stays the same even if you set it manually when supplying a requester.

## Steps to Reproduce

1. Set a custom Accept header when creating a DefaultHttpRequester
2. Open a url using the context
3. Accept header always stays as "text/html,application/xhtml+xml,application/xml"

**Expected behavior:** Accept header should change to a desired value upon setting

**Actual behavior:** Accept header stays the same ("text/html,application/xhtml+xml,application/xml" by default)

**Environment details:** Windows 10, .NET 5, Console App

## Possible Solution

Default Accept header is set when creating a DocumentRequest. Instead, it should be set when DefaultHttpRequester is created.

**Comment by FlorianRappl** [comment]
The accept header is set by the used loader. For a document that is always pinned to what you wrote above. If its something else (e.g., for doing a generic `fetch` via JS) then this remains generic.

Any real browser sends the same accept header for document requests.

Sorry - I don't see the bug, this is by design. Explicit headers take precedence over default ones and the loader sets this header explicitly.

**Comment by aidilumarov** [comment]
@FlorianRappl I understand that it is a default header. But when you set a desired header explicitly, it should change, but it does not. This is why I marked it as a bug. I suggest moving default header creation out of this method to when the requester is created. I will show my suggestions via a pull request later.

**Comment by FlorianRappl** [comment]
It's not a bug - as written this is by design. Its not on the requester level, but in the loader. And as written a document loader only wants to get specific documents (e.g., HTML).

Use the requester directly or use request loaders for your purposes. Browsers also send this header with document requests.

Just to highlight your misunderstanding about the design:

> Default Accept header is set when creating a DocumentRequest. Instead, it should be set when DefaultHttpRequester is created.

No, because the accepts header is not a default header. For instance, when an image is requested we do not accept HTML documents. Documents are expected by the document loader, which is why this loader sets the header that way.

The initialization of the `DefaultHttpRequester` would leave two bad things:

1.) it would be used for *all* requests (bad)
2.) it would only be used for the `DefaultHttpRequester`, but not for some other (custom) requester (e.g., the one coming from AngleSharp.Io).

This is not a good design. This is also not how it should be done. Please, first take a minute to understand the design and why it was made like this. Thanks!

**Comment by aidilumarov** [comment]
@FlorianRappl alright. I got your point. How do I set a custom header for a particular document request? I have been trying to do it the whole day. I have tried to set a header on a requester level before each request, but all I get is a default header that is hard-coded on a document request level. I.e. when I want application/json, I am getting an xml.

**Comment by FlorianRappl** [comment]
> I have tried to set a header on a requester level before each request, but all I get is a default header that is hard-coded on a document request level. I.e. when I want application/json, I am getting an xml.

Because you use the wrong thing. If you want to have application/json then you don't want to load a document. You want to use the resource loader / the HTTP requester directly instead.

I actually don't understand your use case. Can you elaborate why you use AngleSharp / create a document request (for e.g., XML, HTML documents) when you want / expect JSON? If you outline your use case I may be able to help you.

**Comment by aidilumarov** [comment]
I am trying to write a scraper which authenticates on some website and does some things there. Their login page is not usual. First there is an html form with an email address. After you submit, the website sends a json with one property, whose contents are actually an html with the rest of the login form. Because I cannot set Accept: application/json, the website is just returning some html with the same page instead of sending me the rest of the form. Thus, I cannot log in.

**Comment by aidilumarov** [comment]
May be there should be an overload for OpenAsync, which accepts a dictionary of custom headers to use?

**Comment by FlorianRappl** [comment]
But then their login form is also unusable from the browser with deactivated JS as I guess they don't submit the form via the `form` directly, but indirectly by stopping `onSubmit` and then calling the API.

Why don't you do the same thing?

> May be there should be an overload for OpenAsync, which accepts a dictionary of custom headers to use?

That would not help much. This is the outside API - but it just creates a document loader, which - again - already knows what to expect. You should not load this document (because its not a document), but request the resource...

You can use `GetSubmission` on the form to get the actual `DocumentRequest` without requesting it. Transforming this to a `Request` is straight forward (`Method` -> `Method`, `Headers` -> `Headers`, `Body` -> `Content`) and you an add your header, too.

**Comment by aidilumarov** [comment]
Durectly calling the API is not possible because the rest of the form which is sent as json contains a token which should be sent back when you submit your password. Alright, I will try to do as you have described. Thank you very much for your help!

**Comment by FlorianRappl** [comment]
> Durectly calling the API is not possible because the rest of the form which is sent as json contains a token which should be sent back when you submit your password. Alright, I will try to do as you have described. Thank you very much for your help!

This is why you use `GetSubmission`. It contains all the info as the form request would have...
