### ISSUE TITLE
How to get all CSS rules?

### ISSUE THREAD

**Issue by trueromanus** [AngleSharp/AngleSharp#954]
Hi guys!
I want to get all CSS rules on pages.
I try to do it but I don't understand how to get it.

My code:
```csharp
var context = BrowsingContext.New(AngleSharpConfiguration.Default.WithCss());
var document = await context.OpenAsync(req => req.Content(content));
var sheets = document.StyleSheets.ToList().Cast<ICssStyleSheet>();
sheets.First().CssText //<-- contains only full rule as string (e.g. .class{ font-size: 20px })
```
I inspect this rule in debugging and uncover that implementation has SelectorText and few other helpful properties.
How can I get SelectorText from rule?

**Comment by FlorianRappl** [comment]
It's close.

```cs
var content = "<style>h1 { color: red } h2 { color: blue }</style>";
var context = BrowsingContext.New(Configuration.Default.WithCss());
var document = await context.OpenAsync(req => req.Content(content));
var sheets = document.StyleSheets.ToList().Cast<ICssStyleSheet>();
var sheet = sheets.First();
var rules = sheet.Rules;
var h1rule = rules.OfType<ICssStyleRule>().First(r => r.SelectorText == "h1");
var colorDeclaration = h1rule.Style.Where(m => m.Name == "color");
```

So the sheet follows the CSSOM, which is also fully defined by the W3C. Due to the static type nature of C# you'll need to check for types and use the right casts, e.g., a node in the CSS stylesheet that is a style need (consisting of selector + declarations) you'd get via the `ICssStyleRule` interface.

Hope that helps!

(Usually this issue would be moved to `AngleSharp.Css`, but I left it here since others may also stumble across the same question)
