### ISSUE TITLE
How do I use IApplicationCache 

### ISSUE THREAD

**Issue by Sicos1977** [AngleSharp/AngleSharp#999]
Hi,

First of all, thanks for the great work you have done on AngleSharp.

This is not a bug but rather a question about how to use IApplicationCache .

I want to add caching to AngleSharp to prevent it from downloading the same image over and over again. My main goal is to speed up the processing of html e-mails that have the same pictures in it over and over again.

Greetings,
Kees

**Comment by FlorianRappl** [comment]
Hi thanks for the question!

The `IApplicationCache` interface is the .NET representation the AppCache (https://www.w3.org/TR/2011/WD-html5-20110525/offline.html#application-cache-api). This would be used implicitly with an app cache manifest and thus would not be something you could (or should) use to speed up the download.

What I suggest instead is to integrate your own network cache logic. What you could do is to wrap the existing loaders (i.e., the default document loader https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/DefaultDocumentLoader.cs and default resource loader https://github.com/AngleSharp/AngleSharp/blob/devel/src/AngleSharp/Io/DefaultResourceLoader.cs) and to first look into a cache (maybe on disk) when `FetchAsync` is called. If you find something you could return it, otherwise you'd go with the base implementation.

To use your own loader you could do:

```cs
var configuration = Configuration.Default
  .With(new DefaultHttpRequester())
  .With<IDocumentLoader>(ctx => new MyDocumentLoader(ctx))
  .With<IResourceLoader>(ctx => new MyResourceLoader(ctx));
```

**Comment by Sicos1977** [comment]
Okey thanks I will look into that.
